/**
 * 🏭 GENERATED WITH features-generator
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution
 */

export const FEATURES: Array<{ en: string; cs: string; search: any; searchUrl: string }> = [
    {
        en: 'China',
        cs: 'Čína',
        search: { country: 'China' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=China',
    },
    {
        en: 'India',
        cs: 'Indie',
        search: { country: 'India' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=India',
    },
    {
        en: 'United States',
        cs: 'Spojené státy',
        search: { country: 'United States' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=United+States',
    },
    {
        en: 'Indonesia',
        cs: 'Indonésie',
        search: { country: 'Indonesia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Indonesia',
    },
    {
        en: 'Pakistan',
        cs: 'Pákistán',
        search: { country: 'Pakistan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Pakistan',
    },
    {
        en: 'Brazil',
        cs: 'Brazílie',
        search: { country: 'Brazil' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Brazil',
    },
    {
        en: 'Nigeria',
        cs: 'Nigérie',
        search: { country: 'Nigeria' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Nigeria',
    },
    {
        en: 'Bangladesh',
        cs: 'Bangladéš',
        search: { country: 'Bangladesh' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Bangladesh',
    },
    {
        en: 'Russia',
        cs: 'Rusko',
        search: { country: 'Russia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Russia',
    },
    {
        en: 'Mexico',
        cs: 'Mexiko',
        search: { country: 'Mexico' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Mexico',
    },
    {
        en: 'Japan',
        cs: 'Japonsko',
        search: { country: 'Japan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Japan',
    },
    {
        en: 'Ethiopia',
        cs: 'Etiopie',
        search: { country: 'Ethiopia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Ethiopia',
    },
    {
        en: 'Philippines',
        cs: 'Filipíny',
        search: { country: 'Philippines' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Philippines',
    },
    {
        en: 'Egypt',
        cs: 'Egypt',
        search: { country: 'Egypt' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Egypt',
    },
    {
        en: 'Vietnam',
        cs: 'Vietnam',
        search: { country: 'Vietnam' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Vietnam',
    },
    {
        en: 'DR Congo',
        cs: 'Dr. Kongo.',
        search: { country: 'DR Congo' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=DR+Congo',
    },
    {
        en: 'Iran',
        cs: 'Írán',
        search: { country: 'Iran' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Iran',
    },
    {
        en: 'Turkey',
        cs: 'krocan',
        search: { country: 'Turkey' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Turkey',
    },
    {
        en: 'Germany',
        cs: 'Německo',
        search: { country: 'Germany' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Germany',
    },
    {
        en: 'France',
        cs: 'Francie',
        search: { country: 'France' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=France',
    },
    {
        en: 'United Kingdom',
        cs: 'Spojené království',
        search: { country: 'United Kingdom' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=United+Kingdom',
    },
    {
        en: 'Thailand',
        cs: 'Thajsko',
        search: { country: 'Thailand' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Thailand',
    },
    {
        en: 'South Africa',
        cs: 'Jižní Afrika',
        search: { country: 'South Africa' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=South+Africa',
    },
    {
        en: 'Tanzania',
        cs: 'Tanzanie.',
        search: { country: 'Tanzania' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Tanzania',
    },
    {
        en: 'Italy',
        cs: 'Itálie',
        search: { country: 'Italy' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Italy',
    },
    {
        en: 'Myanmar',
        cs: 'Myanmar.',
        search: { country: 'Myanmar' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Myanmar',
    },
    {
        en: 'South Korea',
        cs: 'Jižní Korea',
        search: { country: 'South Korea' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=South+Korea',
    },
    {
        en: 'Colombia',
        cs: 'Kolumbie',
        search: { country: 'Colombia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Colombia',
    },
    {
        en: 'Kenya',
        cs: 'Keňa',
        search: { country: 'Kenya' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Kenya',
    },
    {
        en: 'Spain',
        cs: 'Španělsko',
        search: { country: 'Spain' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Spain',
    },
    {
        en: 'Argentina',
        cs: 'Argentina',
        search: { country: 'Argentina' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Argentina',
    },
    {
        en: 'Algeria',
        cs: 'Alžírsko',
        search: { country: 'Algeria' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Algeria',
    },
    {
        en: 'Sudan',
        cs: 'Sudan.',
        search: { country: 'Sudan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Sudan',
    },
    {
        en: 'Uganda',
        cs: 'Uganda.',
        search: { country: 'Uganda' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Uganda',
    },
    {
        en: 'Iraq',
        cs: 'Irák',
        search: { country: 'Iraq' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Iraq',
    },
    {
        en: 'Ukraine',
        cs: 'Ukrajina',
        search: { country: 'Ukraine' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Ukraine',
    },
    {
        en: 'Canada',
        cs: 'Kanada',
        search: { country: 'Canada' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Canada',
    },
    {
        en: 'Poland',
        cs: 'Polsko',
        search: { country: 'Poland' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Poland',
    },
    {
        en: 'Morocco',
        cs: 'Maroko',
        search: { country: 'Morocco' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Morocco',
    },
    {
        en: 'Uzbekistan',
        cs: 'Uzbekistán',
        search: { country: 'Uzbekistan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Uzbekistan',
    },
    {
        en: 'Saudi Arabia',
        cs: 'Saudská arábie',
        search: { country: 'Saudi Arabia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Saudi+Arabia',
    },
    {
        en: 'Peru',
        cs: 'Peru',
        search: { country: 'Peru' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Peru',
    },
    {
        en: 'Afghanistan',
        cs: 'Afghánistán',
        search: { country: 'Afghanistan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Afghanistan',
    },
    {
        en: 'Malaysia',
        cs: 'Malajsie',
        search: { country: 'Malaysia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Malaysia',
    },
    {
        en: 'Angola',
        cs: 'Angola',
        search: { country: 'Angola' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Angola',
    },
    {
        en: 'Mozambique',
        cs: 'Mozambik',
        search: { country: 'Mozambique' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Mozambique',
    },
    {
        en: 'Ghana',
        cs: 'Ghana',
        search: { country: 'Ghana' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Ghana',
    },
    {
        en: 'Yemen',
        cs: 'Jemen',
        search: { country: 'Yemen' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Yemen',
    },
    {
        en: 'Nepal',
        cs: 'Nepál',
        search: { country: 'Nepal' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Nepal',
    },
    {
        en: 'Venezuela',
        cs: 'Venezuela',
        search: { country: 'Venezuela' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Venezuela',
    },
    {
        en: 'Ivory Coast',
        cs: 'Pobřeží slonoviny',
        search: { country: 'Ivory Coast' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Ivory+Coast',
    },
    {
        en: 'Madagascar',
        cs: 'Madagaskar',
        search: { country: 'Madagascar' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Madagascar',
    },
    {
        en: 'Australia',
        cs: 'Austrálie',
        search: { country: 'Australia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Australia',
    },
    {
        en: 'North Korea',
        cs: 'Severní Korea',
        search: { country: 'North Korea' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=North+Korea',
    },
    {
        en: 'Cameroon',
        cs: 'Kamerun',
        search: { country: 'Cameroon' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Cameroon',
    },
    {
        en: 'Niger',
        cs: 'Niger',
        search: { country: 'Niger' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Niger',
    },
    {
        en: 'Taiwan',
        cs: 'Tchaj-wan.',
        search: { country: 'Taiwan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Taiwan',
    },
    {
        en: 'Sri Lanka',
        cs: 'Srí Lanka',
        search: { country: 'Sri Lanka' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Sri+Lanka',
    },
    {
        en: 'Burkina Faso',
        cs: 'Burkina Faso.',
        search: { country: 'Burkina Faso' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Burkina+Faso',
    },
    {
        en: 'Mali',
        cs: 'Mali.',
        search: { country: 'Mali' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Mali',
    },
    {
        en: 'Chile',
        cs: 'Chile',
        search: { country: 'Chile' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Chile',
    },
    {
        en: 'Romania',
        cs: 'Rumunsko',
        search: { country: 'Romania' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Romania',
    },
    {
        en: 'Kazakhstan',
        cs: 'Kazachstán',
        search: { country: 'Kazakhstan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Kazakhstan',
    },
    {
        en: 'Malawi',
        cs: 'Malawi.',
        search: { country: 'Malawi' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Malawi',
    },
    {
        en: 'Zambia',
        cs: 'Zambie',
        search: { country: 'Zambia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Zambia',
    },
    {
        en: 'Syria',
        cs: 'Sýrie',
        search: { country: 'Syria' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Syria',
    },
    {
        en: 'Ecuador',
        cs: 'Ekvádor',
        search: { country: 'Ecuador' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Ecuador',
    },
    {
        en: 'Netherlands',
        cs: 'Holandsko',
        search: { country: 'Netherlands' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Netherlands',
    },
    {
        en: 'Senegal',
        cs: 'Senegal.',
        search: { country: 'Senegal' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Senegal',
    },
    {
        en: 'Guatemala',
        cs: 'Guatemala',
        search: { country: 'Guatemala' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Guatemala',
    },
    {
        en: 'Chad',
        cs: 'Chad.',
        search: { country: 'Chad' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Chad',
    },
    {
        en: 'Somalia',
        cs: 'Somálsko',
        search: { country: 'Somalia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Somalia',
    },
    {
        en: 'Zimbabwe',
        cs: 'Zimbabwe',
        search: { country: 'Zimbabwe' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Zimbabwe',
    },
    {
        en: 'Cambodia',
        cs: 'Kambodža',
        search: { country: 'Cambodia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Cambodia',
    },
    {
        en: 'South Sudan',
        cs: 'jižní Súdán',
        search: { country: 'South Sudan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=South+Sudan',
    },
    {
        en: 'Rwanda',
        cs: 'Rwanda.',
        search: { country: 'Rwanda' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Rwanda',
    },
    {
        en: 'Guinea',
        cs: 'Guinea',
        search: { country: 'Guinea' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Guinea',
    },
    {
        en: 'Burundi',
        cs: 'Burundi.',
        search: { country: 'Burundi' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Burundi',
    },
    {
        en: 'Benin',
        cs: 'Benin',
        search: { country: 'Benin' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Benin',
    },
    {
        en: 'Bolivia',
        cs: 'Bolívie',
        search: { country: 'Bolivia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Bolivia',
    },
    {
        en: 'Tunisia',
        cs: 'Tunisko',
        search: { country: 'Tunisia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Tunisia',
    },
    {
        en: 'Haiti',
        cs: 'Haiti',
        search: { country: 'Haiti' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Haiti',
    },
    {
        en: 'Belgium',
        cs: 'Belgie',
        search: { country: 'Belgium' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Belgium',
    },
    {
        en: 'Cuba',
        cs: 'Kostka',
        search: { country: 'Cuba' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Cuba',
    },
    {
        en: 'Jordan',
        cs: 'Jordán',
        search: { country: 'Jordan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Jordan',
    },
    {
        en: 'Greece',
        cs: 'Řecko',
        search: { country: 'Greece' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Greece',
    },
    {
        en: 'Dominican Republic',
        cs: 'Dominikánská republika',
        search: { country: 'Dominican Republic' },
        searchUrl:
            'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Dominican+Republic',
    },
    {
        en: 'Czech Republic',
        cs: 'Česká republika',
        search: { country: 'Czech Republic' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Czech+Republic',
    },
    {
        en: 'Sweden',
        cs: 'Švédsko',
        search: { country: 'Sweden' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Sweden',
    },
    {
        en: 'Portugal',
        cs: 'Portugalsko',
        search: { country: 'Portugal' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Portugal',
    },
    {
        en: 'Azerbaijan',
        cs: 'Ázerbajdžán',
        search: { country: 'Azerbaijan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Azerbaijan',
    },
    {
        en: 'Hungary',
        cs: 'Maďarsko',
        search: { country: 'Hungary' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Hungary',
    },
    {
        en: 'Tajikistan',
        cs: 'Tádžikistán',
        search: { country: 'Tajikistan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Tajikistan',
    },
    {
        en: 'United Arab Emirates',
        cs: 'Spojené arabské emiráty',
        search: { country: 'United Arab Emirates' },
        searchUrl:
            'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=United+Arab+Emirates',
    },
    {
        en: 'Israel',
        cs: 'Izrael',
        search: { country: 'Israel' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Israel',
    },
    {
        en: 'Honduras',
        cs: 'Honduras',
        search: { country: 'Honduras' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Honduras',
    },
    {
        en: 'Belarus',
        cs: 'Bělorusko',
        search: { country: 'Belarus' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Belarus',
    },
    {
        en: 'Papua New Guinea',
        cs: 'Papua-Nová Guinea',
        search: { country: 'Papua New Guinea' },
        searchUrl:
            'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Papua+New+Guinea',
    },
    {
        en: 'Austria',
        cs: 'Rakousko',
        search: { country: 'Austria' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Austria',
    },
    {
        en: 'Switzerland',
        cs: 'Švýcarsko',
        search: { country: 'Switzerland' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Switzerland',
    },
    {
        en: 'Sierra Leone',
        cs: 'Sierra Leone',
        search: { country: 'Sierra Leone' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Sierra+Leone',
    },
    {
        en: 'Togo',
        cs: 'Jít',
        search: { country: 'Togo' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Togo',
    },
    {
        en: 'Hong Kong (China)',
        cs: 'Hong Kong (Čína)',
        search: { country: 'Hong Kong (China)' },
        searchUrl:
            'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Hong+Kong+%28China%29',
    },
    {
        en: 'Paraguay',
        cs: 'Paraguay',
        search: { country: 'Paraguay' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Paraguay',
    },
    {
        en: 'Laos',
        cs: 'Laos',
        search: { country: 'Laos' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Laos',
    },
    {
        en: 'Libya',
        cs: 'Libye',
        search: { country: 'Libya' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Libya',
    },
    {
        en: 'Serbia',
        cs: 'Srbsko',
        search: { country: 'Serbia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Serbia',
    },
    {
        en: 'El Salvador',
        cs: 'El Salvador',
        search: { country: 'El Salvador' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=El+Salvador',
    },
    {
        en: 'Lebanon',
        cs: 'Libanon',
        search: { country: 'Lebanon' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Lebanon',
    },
    {
        en: 'Kyrgyzstan',
        cs: 'Kyrgyzstán',
        search: { country: 'Kyrgyzstan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Kyrgyzstan',
    },
    {
        en: 'Nicaragua',
        cs: 'Nikaragua',
        search: { country: 'Nicaragua' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Nicaragua',
    },
    {
        en: 'Bulgaria',
        cs: 'Bulharsko',
        search: { country: 'Bulgaria' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Bulgaria',
    },
    {
        en: 'Turkmenistan',
        cs: 'Turkmenistan.',
        search: { country: 'Turkmenistan' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Turkmenistan',
    },
    {
        en: 'Denmark',
        cs: 'Dánsko',
        search: { country: 'Denmark' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Denmark',
    },
    {
        en: 'Congo',
        cs: 'Kongo',
        search: { country: 'Congo' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Congo',
    },
    {
        en: 'Central African Republic',
        cs: 'Středoafrická republika',
        search: { country: 'Central African Republic' },
        searchUrl:
            'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Central+African+Republic',
    },
    {
        en: 'Finland',
        cs: 'Finsko',
        search: { country: 'Finland' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Finland',
    },
    {
        en: 'Singapore',
        cs: 'Singapur.',
        search: { country: 'Singapore' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Singapore',
    },
    {
        en: 'Slovakia',
        cs: 'Slovensko',
        search: { country: 'Slovakia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Slovakia',
    },
    {
        en: 'Norway',
        cs: 'Norsko',
        search: { country: 'Norway' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Norway',
    },
    {
        en: 'Palestine',
        cs: 'Palestina',
        search: { country: 'Palestine' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Palestine',
    },
    {
        en: 'Costa Rica',
        cs: 'Kostarika',
        search: { country: 'Costa Rica' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Costa+Rica',
    },
    {
        en: 'New Zealand',
        cs: 'Nový Zéland',
        search: { country: 'New Zealand' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=New+Zealand',
    },
    {
        en: 'Ireland',
        cs: 'Irsko',
        search: { country: 'Ireland' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Ireland',
    },
    {
        en: 'Kuwait',
        cs: 'Kuvajt',
        search: { country: 'Kuwait' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Kuwait',
    },
    {
        en: 'Liberia',
        cs: 'Libérie',
        search: { country: 'Liberia' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Liberia',
    },
    {
        en: 'Oman',
        cs: 'Omán',
        search: { country: 'Oman' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Oman',
    },
    {
        en: 'Panama',
        cs: 'Panama',
        search: { country: 'Panama' },
        searchUrl: 'https://nominatim.openstreetmap.org/search?format=geojson&polygon_geojson=1&country=Panama',
    },
];
