/**
 * 🏭 GENERATED WITH features-generator
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution
 */

export const FEATURES: Array<{ en: string; cs: string; search: any }> = [
    { en: 'China', cs: 'China', search: { country: 'China' } },
    { en: 'India', cs: 'India', search: { country: 'India' } },
    { en: 'United States', cs: 'United States', search: { country: 'United States' } },
    { en: 'Indonesia', cs: 'Indonesia', search: { country: 'Indonesia' } },
    { en: 'Pakistan', cs: 'Pakistan', search: { country: 'Pakistan' } },
    { en: 'Brazil', cs: 'Brazil', search: { country: 'Brazil' } },
    { en: 'Nigeria', cs: 'Nigeria', search: { country: 'Nigeria' } },
    { en: 'Bangladesh', cs: 'Bangladesh', search: { country: 'Bangladesh' } },
    { en: 'Russia', cs: 'Russia', search: { country: 'Russia' } },
    { en: 'Mexico', cs: 'Mexico', search: { country: 'Mexico' } },
    { en: 'Japan', cs: 'Japan', search: { country: 'Japan' } },
    { en: 'Ethiopia', cs: 'Ethiopia', search: { country: 'Ethiopia' } },
    { en: 'Philippines', cs: 'Philippines', search: { country: 'Philippines' } },
    { en: 'Egypt', cs: 'Egypt', search: { country: 'Egypt' } },
    { en: 'Vietnam', cs: 'Vietnam', search: { country: 'Vietnam' } },
    { en: 'DR Congo', cs: 'DR Congo', search: { country: 'DR Congo' } },
    { en: 'Iran', cs: 'Iran', search: { country: 'Iran' } },
    { en: 'Turkey', cs: 'Turkey', search: { country: 'Turkey' } },
    { en: 'Germany', cs: 'Germany', search: { country: 'Germany' } },
    { en: 'France', cs: 'France', search: { country: 'France' } },
    { en: 'United Kingdom', cs: 'United Kingdom', search: { country: 'United Kingdom' } },
    { en: 'Thailand', cs: 'Thailand', search: { country: 'Thailand' } },
    { en: 'South Africa', cs: 'South Africa', search: { country: 'South Africa' } },
    { en: 'Tanzania', cs: 'Tanzania', search: { country: 'Tanzania' } },
    { en: 'Italy', cs: 'Italy', search: { country: 'Italy' } },
    { en: 'Myanmar', cs: 'Myanmar', search: { country: 'Myanmar' } },
    { en: 'South Korea', cs: 'South Korea', search: { country: 'South Korea' } },
    { en: 'Colombia', cs: 'Colombia', search: { country: 'Colombia' } },
    { en: 'Kenya', cs: 'Kenya', search: { country: 'Kenya' } },
    { en: 'Spain', cs: 'Spain', search: { country: 'Spain' } },
    { en: 'Argentina', cs: 'Argentina', search: { country: 'Argentina' } },
    { en: 'Algeria', cs: 'Algeria', search: { country: 'Algeria' } },
    { en: 'Sudan', cs: 'Sudan', search: { country: 'Sudan' } },
    { en: 'Uganda', cs: 'Uganda', search: { country: 'Uganda' } },
    { en: 'Iraq', cs: 'Iraq', search: { country: 'Iraq' } },
    { en: 'Ukraine', cs: 'Ukraine', search: { country: 'Ukraine' } },
    { en: 'Canada', cs: 'Canada', search: { country: 'Canada' } },
    { en: 'Poland', cs: 'Poland', search: { country: 'Poland' } },
    { en: 'Morocco', cs: 'Morocco', search: { country: 'Morocco' } },
    { en: 'Uzbekistan', cs: 'Uzbekistan', search: { country: 'Uzbekistan' } },
    { en: 'Saudi Arabia', cs: 'Saudi Arabia', search: { country: 'Saudi Arabia' } },
    { en: 'Peru', cs: 'Peru', search: { country: 'Peru' } },
    { en: 'Afghanistan', cs: 'Afghanistan', search: { country: 'Afghanistan' } },
    { en: 'Malaysia', cs: 'Malaysia', search: { country: 'Malaysia' } },
    { en: 'Angola', cs: 'Angola', search: { country: 'Angola' } },
    { en: 'Mozambique', cs: 'Mozambique', search: { country: 'Mozambique' } },
    { en: 'Ghana', cs: 'Ghana', search: { country: 'Ghana' } },
    { en: 'Yemen', cs: 'Yemen', search: { country: 'Yemen' } },
    { en: 'Nepal', cs: 'Nepal', search: { country: 'Nepal' } },
    { en: 'Venezuela', cs: 'Venezuela', search: { country: 'Venezuela' } },
    { en: 'Ivory Coast', cs: 'Ivory Coast', search: { country: 'Ivory Coast' } },
    { en: 'Madagascar', cs: 'Madagascar', search: { country: 'Madagascar' } },
    { en: 'Australia', cs: 'Australia', search: { country: 'Australia' } },
    { en: 'North Korea', cs: 'North Korea', search: { country: 'North Korea' } },
    { en: 'Cameroon', cs: 'Cameroon', search: { country: 'Cameroon' } },
    { en: 'Niger', cs: 'Niger', search: { country: 'Niger' } },
    { en: 'Taiwan', cs: 'Taiwan', search: { country: 'Taiwan' } },
    { en: 'Sri Lanka', cs: 'Sri Lanka', search: { country: 'Sri Lanka' } },
    { en: 'Burkina Faso', cs: 'Burkina Faso', search: { country: 'Burkina Faso' } },
    { en: 'Mali', cs: 'Mali', search: { country: 'Mali' } },
    { en: 'Chile', cs: 'Chile', search: { country: 'Chile' } },
    { en: 'Romania', cs: 'Romania', search: { country: 'Romania' } },
    { en: 'Kazakhstan', cs: 'Kazakhstan', search: { country: 'Kazakhstan' } },
    { en: 'Malawi', cs: 'Malawi', search: { country: 'Malawi' } },
    { en: 'Zambia', cs: 'Zambia', search: { country: 'Zambia' } },
    { en: 'Syria', cs: 'Syria', search: { country: 'Syria' } },
    { en: 'Ecuador', cs: 'Ecuador', search: { country: 'Ecuador' } },
    { en: 'Netherlands', cs: 'Netherlands', search: { country: 'Netherlands' } },
    { en: 'Senegal', cs: 'Senegal', search: { country: 'Senegal' } },
    { en: 'Guatemala', cs: 'Guatemala', search: { country: 'Guatemala' } },
    { en: 'Chad', cs: 'Chad', search: { country: 'Chad' } },
    { en: 'Somalia', cs: 'Somalia', search: { country: 'Somalia' } },
    { en: 'Zimbabwe', cs: 'Zimbabwe', search: { country: 'Zimbabwe' } },
    { en: 'Cambodia', cs: 'Cambodia', search: { country: 'Cambodia' } },
    { en: 'South Sudan', cs: 'South Sudan', search: { country: 'South Sudan' } },
    { en: 'Rwanda', cs: 'Rwanda', search: { country: 'Rwanda' } },
    { en: 'Guinea', cs: 'Guinea', search: { country: 'Guinea' } },
    { en: 'Burundi', cs: 'Burundi', search: { country: 'Burundi' } },
    { en: 'Benin', cs: 'Benin', search: { country: 'Benin' } },
    { en: 'Bolivia', cs: 'Bolivia', search: { country: 'Bolivia' } },
    { en: 'Tunisia', cs: 'Tunisia', search: { country: 'Tunisia' } },
    { en: 'Haiti', cs: 'Haiti', search: { country: 'Haiti' } },
    { en: 'Belgium', cs: 'Belgium', search: { country: 'Belgium' } },
    { en: 'Cuba', cs: 'Cuba', search: { country: 'Cuba' } },
    { en: 'Jordan', cs: 'Jordan', search: { country: 'Jordan' } },
    { en: 'Greece', cs: 'Greece', search: { country: 'Greece' } },
    { en: 'Dominican Republic', cs: 'Dominican Republic', search: { country: 'Dominican Republic' } },
    { en: 'Czech Republic', cs: 'Czech Republic', search: { country: 'Czech Republic' } },
    { en: 'Sweden', cs: 'Sweden', search: { country: 'Sweden' } },
    { en: 'Portugal', cs: 'Portugal', search: { country: 'Portugal' } },
    { en: 'Azerbaijan', cs: 'Azerbaijan', search: { country: 'Azerbaijan' } },
    { en: 'Hungary', cs: 'Hungary', search: { country: 'Hungary' } },
    { en: 'Tajikistan', cs: 'Tajikistan', search: { country: 'Tajikistan' } },
    { en: 'United Arab Emirates', cs: 'United Arab Emirates', search: { country: 'United Arab Emirates' } },
    { en: 'Israel', cs: 'Israel', search: { country: 'Israel' } },
    { en: 'Honduras', cs: 'Honduras', search: { country: 'Honduras' } },
    { en: 'Belarus', cs: 'Belarus', search: { country: 'Belarus' } },
    { en: 'Papua New Guinea', cs: 'Papua New Guinea', search: { country: 'Papua New Guinea' } },
    { en: 'Austria', cs: 'Austria', search: { country: 'Austria' } },
    { en: 'Switzerland', cs: 'Switzerland', search: { country: 'Switzerland' } },
    { en: 'Sierra Leone', cs: 'Sierra Leone', search: { country: 'Sierra Leone' } },
    { en: 'Togo', cs: 'Togo', search: { country: 'Togo' } },
    { en: 'Hong Kong (China)', cs: 'Hong Kong (China)', search: { country: 'Hong Kong (China)' } },
    { en: 'Paraguay', cs: 'Paraguay', search: { country: 'Paraguay' } },
    { en: 'Laos', cs: 'Laos', search: { country: 'Laos' } },
    { en: 'Libya', cs: 'Libya', search: { country: 'Libya' } },
    { en: 'Serbia', cs: 'Serbia', search: { country: 'Serbia' } },
    { en: 'El Salvador', cs: 'El Salvador', search: { country: 'El Salvador' } },
    { en: 'Lebanon', cs: 'Lebanon', search: { country: 'Lebanon' } },
    { en: 'Kyrgyzstan', cs: 'Kyrgyzstan', search: { country: 'Kyrgyzstan' } },
    { en: 'Nicaragua', cs: 'Nicaragua', search: { country: 'Nicaragua' } },
    { en: 'Bulgaria', cs: 'Bulgaria', search: { country: 'Bulgaria' } },
    { en: 'Turkmenistan', cs: 'Turkmenistan', search: { country: 'Turkmenistan' } },
    { en: 'Denmark', cs: 'Denmark', search: { country: 'Denmark' } },
    { en: 'Congo', cs: 'Congo', search: { country: 'Congo' } },
    { en: 'Central African Republic', cs: 'Central African Republic', search: { country: 'Central African Republic' } },
    { en: 'Finland', cs: 'Finland', search: { country: 'Finland' } },
    { en: 'Singapore', cs: 'Singapore', search: { country: 'Singapore' } },
    { en: 'Slovakia', cs: 'Slovakia', search: { country: 'Slovakia' } },
    { en: 'Norway', cs: 'Norway', search: { country: 'Norway' } },
    { en: 'Palestine', cs: 'Palestine', search: { country: 'Palestine' } },
    { en: 'Costa Rica', cs: 'Costa Rica', search: { country: 'Costa Rica' } },
    { en: 'New Zealand', cs: 'New Zealand', search: { country: 'New Zealand' } },
    { en: 'Ireland', cs: 'Ireland', search: { country: 'Ireland' } },
    { en: 'Kuwait', cs: 'Kuwait', search: { country: 'Kuwait' } },
    { en: 'Liberia', cs: 'Liberia', search: { country: 'Liberia' } },
    { en: 'Oman', cs: 'Oman', search: { country: 'Oman' } },
    { en: 'Panama', cs: 'Panama', search: { country: 'Panama' } },
    { en: 'Mauritania', cs: 'Mauritania', search: { country: 'Mauritania' } },
    { en: 'Croatia', cs: 'Croatia', search: { country: 'Croatia' } },
    { en: 'Georgia', cs: 'Georgia', search: { country: 'Georgia' } },
    { en: 'Eritrea', cs: 'Eritrea', search: { country: 'Eritrea' } },
    { en: 'Uruguay', cs: 'Uruguay', search: { country: 'Uruguay' } },
    { en: 'Mongolia', cs: 'Mongolia', search: { country: 'Mongolia' } },
    { en: 'Bosnia and Herzegovina', cs: 'Bosnia and Herzegovina', search: { country: 'Bosnia and Herzegovina' } },
    {
        en: 'Puerto Rico (United States)',
        cs: 'Puerto Rico (United States)',
        search: { country: 'Puerto Rico (United States)' },
    },
    { en: 'Armenia', cs: 'Armenia', search: { country: 'Armenia' } },
    { en: 'Albania', cs: 'Albania', search: { country: 'Albania' } },
    { en: 'Qatar', cs: 'Qatar', search: { country: 'Qatar' } },
    { en: 'Lithuania', cs: 'Lithuania', search: { country: 'Lithuania' } },
    { en: 'Jamaica', cs: 'Jamaica', search: { country: 'Jamaica' } },
    { en: 'Moldova', cs: 'Moldova', search: { country: 'Moldova' } },
    { en: 'Namibia', cs: 'Namibia', search: { country: 'Namibia' } },
    { en: 'Gambia', cs: 'Gambia', search: { country: 'Gambia' } },
    { en: 'Botswana', cs: 'Botswana', search: { country: 'Botswana' } },
    { en: 'Gabon', cs: 'Gabon', search: { country: 'Gabon' } },
    { en: 'Lesotho', cs: 'Lesotho', search: { country: 'Lesotho' } },
    { en: 'Slovenia', cs: 'Slovenia', search: { country: 'Slovenia' } },
    { en: 'Latvia', cs: 'Latvia', search: { country: 'Latvia' } },
    { en: 'North Macedonia', cs: 'North Macedonia', search: { country: 'North Macedonia' } },
    { en: 'Kosovo', cs: 'Kosovo', search: { country: 'Kosovo' } },
    { en: 'Guinea-Bissau', cs: 'Guinea-Bissau', search: { country: 'Guinea-Bissau' } },
    { en: 'Equatorial Guinea', cs: 'Equatorial Guinea', search: { country: 'Equatorial Guinea' } },
    { en: 'Bahrain', cs: 'Bahrain', search: { country: 'Bahrain' } },
    { en: 'Trinidad and Tobago', cs: 'Trinidad and Tobago', search: { country: 'Trinidad and Tobago' } },
    { en: 'Estonia', cs: 'Estonia', search: { country: 'Estonia' } },
    { en: 'East Timor', cs: 'East Timor', search: { country: 'East Timor' } },
    { en: 'Mauritius', cs: 'Mauritius', search: { country: 'Mauritius' } },
    { en: 'Eswatini', cs: 'Eswatini', search: { country: 'Eswatini' } },
    { en: 'Djibouti', cs: 'Djibouti', search: { country: 'Djibouti' } },
    { en: 'Fiji', cs: 'Fiji', search: { country: 'Fiji' } },
    { en: 'Cyprus', cs: 'Cyprus', search: { country: 'Cyprus' } },
    { en: 'Comoros', cs: 'Comoros', search: { country: 'Comoros' } },
    { en: 'Bhutan', cs: 'Bhutan', search: { country: 'Bhutan' } },
    { en: 'Guyana', cs: 'Guyana', search: { country: 'Guyana' } },
    { en: 'Solomon Islands', cs: 'Solomon Islands', search: { country: 'Solomon Islands' } },
    { en: 'Macau (China)', cs: 'Macau (China)', search: { country: 'Macau (China)' } },
    { en: 'Luxembourg', cs: 'Luxembourg', search: { country: 'Luxembourg' } },
    { en: 'Montenegro', cs: 'Montenegro', search: { country: 'Montenegro' } },
    { en: 'Western Sahara', cs: 'Western Sahara', search: { country: 'Western Sahara' } },
    { en: 'Suriname', cs: 'Suriname', search: { country: 'Suriname' } },
    { en: 'Cape Verde', cs: 'Cape Verde', search: { country: 'Cape Verde' } },
    { en: 'Malta', cs: 'Malta', search: { country: 'Malta' } },
    { en: 'Belize', cs: 'Belize', search: { country: 'Belize' } },
    { en: 'Brunei', cs: 'Brunei', search: { country: 'Brunei' } },
    { en: 'Bahamas', cs: 'Bahamas', search: { country: 'Bahamas' } },
    { en: 'Maldives', cs: 'Maldives', search: { country: 'Maldives' } },
    { en: 'Northern Cyprus', cs: 'Northern Cyprus', search: { country: 'Northern Cyprus' } },
    { en: 'Iceland', cs: 'Iceland', search: { country: 'Iceland' } },
    { en: 'Transnistria', cs: 'Transnistria', search: { country: 'Transnistria' } },
    { en: 'Vanuatu', cs: 'Vanuatu', search: { country: 'Vanuatu' } },
    { en: 'Barbados', cs: 'Barbados', search: { country: 'Barbados' } },
    {
        en: 'French Polynesia (France)',
        cs: 'French Polynesia (France)',
        search: { country: 'French Polynesia (France)' },
    },
    { en: 'New Caledonia (France)', cs: 'New Caledonia (France)', search: { country: 'New Caledonia (France)' } },
    { en: 'Abkhazia', cs: 'Abkhazia', search: { country: 'Abkhazia' } },
    { en: 'São Tomé and Príncipe', cs: 'São Tomé and Príncipe', search: { country: 'São Tomé and Príncipe' } },
    { en: 'Samoa', cs: 'Samoa', search: { country: 'Samoa' } },
    { en: 'Saint Lucia', cs: 'Saint Lucia', search: { country: 'Saint Lucia' } },
    { en: 'Guam (United States)', cs: 'Guam (United States)', search: { country: 'Guam (United States)' } },
    { en: 'Curaçao (Netherlands)', cs: 'Curaçao (Netherlands)', search: { country: 'Curaçao (Netherlands)' } },
    { en: 'Republic of Artsakh', cs: 'Republic of Artsakh', search: { country: 'Republic of Artsakh' } },
    { en: 'Kiribati', cs: 'Kiribati', search: { country: 'Kiribati' } },
    { en: 'Grenada', cs: 'Grenada', search: { country: 'Grenada' } },
    { en: 'Aruba (Netherlands)', cs: 'Aruba (Netherlands)', search: { country: 'Aruba (Netherlands)' } },
    {
        en: 'Saint Vincent and the Grenadines',
        cs: 'Saint Vincent and the Grenadines',
        search: { country: 'Saint Vincent and the Grenadines' },
    },
    {
        en: 'Jersey (British Crown Dependency)',
        cs: 'Jersey (British Crown Dependency)',
        search: { country: 'Jersey (British Crown Dependency)' },
    },
    { en: 'Micronesia', cs: 'Micronesia', search: { country: 'Micronesia' } },
    { en: 'Tonga', cs: 'Tonga', search: { country: 'Tonga' } },
    { en: 'Antigua and Barbuda', cs: 'Antigua and Barbuda', search: { country: 'Antigua and Barbuda' } },
    { en: 'Seychelles', cs: 'Seychelles', search: { country: 'Seychelles' } },
    {
        en: 'U.S. Virgin Islands (United States)',
        cs: 'U.S. Virgin Islands (United States)',
        search: { country: 'U.S. Virgin Islands (United States)' },
    },
    {
        en: 'Isle of Man (British Crown Dependency)',
        cs: 'Isle of Man (British Crown Dependency)',
        search: { country: 'Isle of Man (British Crown Dependency)' },
    },
    { en: 'Andorra', cs: 'Andorra', search: { country: 'Andorra' } },
    { en: 'Dominica', cs: 'Dominica', search: { country: 'Dominica' } },
    {
        en: 'Cayman Islands (United Kingdom)',
        cs: 'Cayman Islands (United Kingdom)',
        search: { country: 'Cayman Islands (United Kingdom)' },
    },
    { en: 'Bermuda (United Kingdom)', cs: 'Bermuda (United Kingdom)', search: { country: 'Bermuda (United Kingdom)' } },
    {
        en: 'Guernsey (British Crown Dependency)',
        cs: 'Guernsey (British Crown Dependency)',
        search: { country: 'Guernsey (British Crown Dependency)' },
    },
    { en: 'Greenland (Denmark)', cs: 'Greenland (Denmark)', search: { country: 'Greenland (Denmark)' } },
    { en: 'Marshall Islands', cs: 'Marshall Islands', search: { country: 'Marshall Islands' } },
    { en: 'Saint Kitts and Nevis', cs: 'Saint Kitts and Nevis', search: { country: 'Saint Kitts and Nevis' } },
    { en: 'Faroe Islands (Denmark)', cs: 'Faroe Islands (Denmark)', search: { country: 'Faroe Islands (Denmark)' } },
    { en: 'South Ossetia', cs: 'South Ossetia', search: { country: 'South Ossetia' } },
    {
        en: 'American Samoa (United States)',
        cs: 'American Samoa (United States)',
        search: { country: 'American Samoa (United States)' },
    },
    {
        en: 'Northern Mariana Islands (United States)',
        cs: 'Northern Mariana Islands (United States)',
        search: { country: 'Northern Mariana Islands (United States)' },
    },
    {
        en: 'Turks and Caicos Islands (United Kingdom)',
        cs: 'Turks and Caicos Islands (United Kingdom)',
        search: { country: 'Turks and Caicos Islands (United Kingdom)' },
    },
    {
        en: 'Sint Maarten (Netherlands)',
        cs: 'Sint Maarten (Netherlands)',
        search: { country: 'Sint Maarten (Netherlands)' },
    },
    { en: 'Liechtenstein', cs: 'Liechtenstein', search: { country: 'Liechtenstein' } },
    { en: 'Monaco', cs: 'Monaco', search: { country: 'Monaco' } },
    {
        en: 'Gibraltar (United Kingdom)',
        cs: 'Gibraltar (United Kingdom)',
        search: { country: 'Gibraltar (United Kingdom)' },
    },
    { en: 'San Marino', cs: 'San Marino', search: { country: 'San Marino' } },
    { en: 'Saint Martin (France)', cs: 'Saint Martin (France)', search: { country: 'Saint Martin (France)' } },
    { en: 'Åland (Finland)', cs: 'Åland (Finland)', search: { country: 'Åland (Finland)' } },
    {
        en: 'British Virgin Islands (United Kingdom)',
        cs: 'British Virgin Islands (United Kingdom)',
        search: { country: 'British Virgin Islands (United Kingdom)' },
    },
    { en: 'Palau', cs: 'Palau', search: { country: 'Palau' } },
    {
        en: 'Cook Islands (New Zealand)',
        cs: 'Cook Islands (New Zealand)',
        search: { country: 'Cook Islands (New Zealand)' },
    },
    {
        en: 'Anguilla (United Kingdom)',
        cs: 'Anguilla (United Kingdom)',
        search: { country: 'Anguilla (United Kingdom)' },
    },
    { en: 'Nauru', cs: 'Nauru', search: { country: 'Nauru' } },
    {
        en: 'Wallis and Futuna (France)',
        cs: 'Wallis and Futuna (France)',
        search: { country: 'Wallis and Futuna (France)' },
    },
    { en: 'Tuvalu', cs: 'Tuvalu', search: { country: 'Tuvalu' } },
    {
        en: 'Saint Barthélemy (France)',
        cs: 'Saint Barthélemy (France)',
        search: { country: 'Saint Barthélemy (France)' },
    },
    {
        en: 'Saint Helena, Ascension and Tristan da Cunha (United Kingdom)',
        cs: 'Saint Helena, Ascension and Tristan da Cunha (United Kingdom)',
        search: { country: 'Saint Helena, Ascension and Tristan da Cunha (United Kingdom)' },
    },
    {
        en: 'Saint Pierre and Miquelon (France)',
        cs: 'Saint Pierre and Miquelon (France)',
        search: { country: 'Saint Pierre and Miquelon (France)' },
    },
    {
        en: 'Montserrat (United Kingdom)',
        cs: 'Montserrat (United Kingdom)',
        search: { country: 'Montserrat (United Kingdom)' },
    },
    {
        en: 'Falkland Islands (United Kingdom)',
        cs: 'Falkland Islands (United Kingdom)',
        search: { country: 'Falkland Islands (United Kingdom)' },
    },
    {
        en: 'Christmas Island (Australia)',
        cs: 'Christmas Island (Australia)',
        search: { country: 'Christmas Island (Australia)' },
    },
    {
        en: 'Norfolk Island (Australia)',
        cs: 'Norfolk Island (Australia)',
        search: { country: 'Norfolk Island (Australia)' },
    },
    { en: 'Niue (New Zealand)', cs: 'Niue (New Zealand)', search: { country: 'Niue (New Zealand)' } },
    { en: 'Tokelau (New Zealand)', cs: 'Tokelau (New Zealand)', search: { country: 'Tokelau (New Zealand)' } },
    { en: 'Vatican City', cs: 'Vatican City', search: { country: 'Vatican City' } },
    {
        en: 'Cocos (Keeling) Islands (Australia)',
        cs: 'Cocos (Keeling) Islands (Australia)',
        search: { country: 'Cocos (Keeling) Islands (Australia)' },
    },
    {
        en: 'Pitcairn Islands (United Kingdom)',
        cs: 'Pitcairn Islands (United Kingdom)',
        search: { country: 'Pitcairn Islands (United Kingdom)' },
    },
    { en: 'Praha', cs: 'Praha', search: { country: 'czechia', q: 'Praha' } },
    { en: 'Brno', cs: 'Brno', search: { country: 'czechia', q: 'Brno' } },
    { en: 'Ostrava', cs: 'Ostrava', search: { country: 'czechia', q: 'Ostrava' } },
    { en: 'Plzeň', cs: 'Plzeň', search: { country: 'czechia', q: 'Plzeň' } },
    { en: 'Liberec', cs: 'Liberec', search: { country: 'czechia', q: 'Liberec' } },
    { en: 'Olomouc', cs: 'Olomouc', search: { country: 'czechia', q: 'Olomouc' } },
    { en: 'České Budějovice', cs: 'České Budějovice', search: { country: 'czechia', q: 'České Budějovice' } },
    { en: 'Hradec Králové', cs: 'Hradec Králové', search: { country: 'czechia', q: 'Hradec Králové' } },
    { en: 'Ústí nad Labem', cs: 'Ústí nad Labem', search: { country: 'czechia', q: 'Ústí nad Labem' } },
    { en: 'Pardubice', cs: 'Pardubice', search: { country: 'czechia', q: 'Pardubice' } },
    { en: 'Zlín', cs: 'Zlín', search: { country: 'czechia', q: 'Zlín' } },
    { en: 'Havířov', cs: 'Havířov', search: { country: 'czechia', q: 'Havířov' } },
    { en: 'Kladno', cs: 'Kladno', search: { country: 'czechia', q: 'Kladno' } },
    { en: 'Most', cs: 'Most', search: { country: 'czechia', q: 'Most' } },
    { en: 'Opava', cs: 'Opava', search: { country: 'czechia', q: 'Opava' } },
    { en: 'Frýdek-Místek', cs: 'Frýdek-Místek', search: { country: 'czechia', q: 'Frýdek-Místek' } },
    { en: 'Jihlava', cs: 'Jihlava', search: { country: 'czechia', q: 'Jihlava' } },
    { en: 'Karviná', cs: 'Karviná', search: { country: 'czechia', q: 'Karviná' } },
    { en: 'Teplice', cs: 'Teplice', search: { country: 'czechia', q: 'Teplice' } },
    { en: 'Chomutov', cs: 'Chomutov', search: { country: 'czechia', q: 'Chomutov' } },
    { en: 'Karlovy Vary', cs: 'Karlovy Vary', search: { country: 'czechia', q: 'Karlovy Vary' } },
    { en: 'Děčín', cs: 'Děčín', search: { country: 'czechia', q: 'Děčín' } },
    { en: 'Jablonec nad Nisou', cs: 'Jablonec nad Nisou', search: { country: 'czechia', q: 'Jablonec nad Nisou' } },
    { en: 'Mladá Boleslav', cs: 'Mladá Boleslav', search: { country: 'czechia', q: 'Mladá Boleslav' } },
    { en: 'Prostějov', cs: 'Prostějov', search: { country: 'czechia', q: 'Prostějov' } },
    { en: 'Přerov', cs: 'Přerov', search: { country: 'czechia', q: 'Přerov' } },
    { en: 'Česká Lípa', cs: 'Česká Lípa', search: { country: 'czechia', q: 'Česká Lípa' } },
    { en: 'Třebíč', cs: 'Třebíč', search: { country: 'czechia', q: 'Třebíč' } },
    { en: 'Třinec', cs: 'Třinec', search: { country: 'czechia', q: 'Třinec' } },
    { en: 'Tábor', cs: 'Tábor', search: { country: 'czechia', q: 'Tábor' } },
    { en: 'Znojmo', cs: 'Znojmo', search: { country: 'czechia', q: 'Znojmo' } },
    { en: 'Kolín', cs: 'Kolín', search: { country: 'czechia', q: 'Kolín' } },
    { en: 'Příbram', cs: 'Příbram', search: { country: 'czechia', q: 'Příbram' } },
    { en: 'Cheb', cs: 'Cheb', search: { country: 'czechia', q: 'Cheb' } },
    { en: 'Písek', cs: 'Písek', search: { country: 'czechia', q: 'Písek' } },
    { en: 'Trutnov', cs: 'Trutnov', search: { country: 'czechia', q: 'Trutnov' } },
    { en: 'Kroměříž', cs: 'Kroměříž', search: { country: 'czechia', q: 'Kroměříž' } },
    { en: 'Orlová', cs: 'Orlová', search: { country: 'czechia', q: 'Orlová' } },
    { en: 'Vsetín', cs: 'Vsetín', search: { country: 'czechia', q: 'Vsetín' } },
    { en: 'Šumperk', cs: 'Šumperk', search: { country: 'czechia', q: 'Šumperk' } },
    { en: 'Uherské Hradiště', cs: 'Uherské Hradiště', search: { country: 'czechia', q: 'Uherské Hradiště' } },
    { en: 'Břeclav', cs: 'Břeclav', search: { country: 'czechia', q: 'Břeclav' } },
    { en: 'Hodonín', cs: 'Hodonín', search: { country: 'czechia', q: 'Hodonín' } },
    { en: 'Český Těšín', cs: 'Český Těšín', search: { country: 'czechia', q: 'Český Těšín' } },
    { en: 'Litoměřice', cs: 'Litoměřice', search: { country: 'czechia', q: 'Litoměřice' } },
    { en: 'Litvínov', cs: 'Litvínov', search: { country: 'czechia', q: 'Litvínov' } },
    { en: 'Havlíčkův Brod', cs: 'Havlíčkův Brod', search: { country: 'czechia', q: 'Havlíčkův Brod' } },
    { en: 'Nový Jičín', cs: 'Nový Jičín', search: { country: 'czechia', q: 'Nový Jičín' } },
    { en: 'Chrudim', cs: 'Chrudim', search: { country: 'czechia', q: 'Chrudim' } },
    { en: 'Krnov', cs: 'Krnov', search: { country: 'czechia', q: 'Krnov' } },
    { en: 'Sokolov', cs: 'Sokolov', search: { country: 'czechia', q: 'Sokolov' } },
    { en: 'Strakonice', cs: 'Strakonice', search: { country: 'czechia', q: 'Strakonice' } },
    { en: 'Valašské Meziříčí', cs: 'Valašské Meziříčí', search: { country: 'czechia', q: 'Valašské Meziříčí' } },
    { en: 'Klatovy', cs: 'Klatovy', search: { country: 'czechia', q: 'Klatovy' } },
    { en: 'Kopřivnice', cs: 'Kopřivnice', search: { country: 'czechia', q: 'Kopřivnice' } },
    { en: 'Jindřichův Hradec', cs: 'Jindřichův Hradec', search: { country: 'czechia', q: 'Jindřichův Hradec' } },
    { en: 'Kutná Hora', cs: 'Kutná Hora', search: { country: 'czechia', q: 'Kutná Hora' } },
    { en: 'Vyškov', cs: 'Vyškov', search: { country: 'czechia', q: 'Vyškov' } },
    { en: 'Žďár nad Sázavou', cs: 'Žďár nad Sázavou', search: { country: 'czechia', q: 'Žďár nad Sázavou' } },
    { en: 'Bohumín', cs: 'Bohumín', search: { country: 'czechia', q: 'Bohumín' } },
    { en: 'Blansko', cs: 'Blansko', search: { country: 'czechia', q: 'Blansko' } },
    { en: 'Beroun', cs: 'Beroun', search: { country: 'czechia', q: 'Beroun' } },
    { en: 'Náchod', cs: 'Náchod', search: { country: 'czechia', q: 'Náchod' } },
    { en: 'Mělník', cs: 'Mělník', search: { country: 'czechia', q: 'Mělník' } },
    {
        en: 'Brandýs nad Labem-Stará Boleslav',
        cs: 'Brandýs nad Labem-Stará Boleslav',
        search: { country: 'czechia', q: 'Brandýs nad Labem-Stará Boleslav' },
    },
    { en: 'Jirkov', cs: 'Jirkov', search: { country: 'czechia', q: 'Jirkov' } },
    { en: 'Žatec', cs: 'Žatec', search: { country: 'czechia', q: 'Žatec' } },
    { en: 'Kralupy nad Vltavou', cs: 'Kralupy nad Vltavou', search: { country: 'czechia', q: 'Kralupy nad Vltavou' } },
    { en: 'Louny', cs: 'Louny', search: { country: 'czechia', q: 'Louny' } },
    { en: 'Kadaň', cs: 'Kadaň', search: { country: 'czechia', q: 'Kadaň' } },
    { en: 'Hranice', cs: 'Hranice', search: { country: 'czechia', q: 'Hranice' } },
    { en: 'Otrokovice', cs: 'Otrokovice', search: { country: 'czechia', q: 'Otrokovice' } },
    { en: 'Bílina', cs: 'Bílina', search: { country: 'czechia', q: 'Bílina' } },
    { en: 'Benešov', cs: 'Benešov', search: { country: 'czechia', q: 'Benešov' } },
    { en: 'Svitavy', cs: 'Svitavy', search: { country: 'czechia', q: 'Svitavy' } },
    { en: 'Jičín', cs: 'Jičín', search: { country: 'czechia', q: 'Jičín' } },
    { en: 'Ostrov', cs: 'Ostrov', search: { country: 'czechia', q: 'Ostrov' } },
    { en: 'Uherský Brod', cs: 'Uherský Brod', search: { country: 'czechia', q: 'Uherský Brod' } },
    {
        en: 'Rožnov pod Radhoštěm',
        cs: 'Rožnov pod Radhoštěm',
        search: { country: 'czechia', q: 'Rožnov pod Radhoštěm' },
    },
    { en: 'Říčany', cs: 'Říčany', search: { country: 'czechia', q: 'Říčany' } },
    { en: 'Neratovice', cs: 'Neratovice', search: { country: 'czechia', q: 'Neratovice' } },
    { en: 'Pelhřimov', cs: 'Pelhřimov', search: { country: 'czechia', q: 'Pelhřimov' } },
    { en: 'Slaný', cs: 'Slaný', search: { country: 'czechia', q: 'Slaný' } },
    { en: 'Bruntál', cs: 'Bruntál', search: { country: 'czechia', q: 'Bruntál' } },
    { en: 'Rakovník', cs: 'Rakovník', search: { country: 'czechia', q: 'Rakovník' } },
    {
        en: 'Dvůr Králové nad Labem',
        cs: 'Dvůr Králové nad Labem',
        search: { country: 'czechia', q: 'Dvůr Králové nad Labem' },
    },
    { en: 'Česká Třebová', cs: 'Česká Třebová', search: { country: 'czechia', q: 'Česká Třebová' } },
    { en: 'Varnsdorf', cs: 'Varnsdorf', search: { country: 'czechia', q: 'Varnsdorf' } },
    { en: 'Nymburk', cs: 'Nymburk', search: { country: 'czechia', q: 'Nymburk' } },
    { en: 'Poděbrady', cs: 'Poděbrady', search: { country: 'czechia', q: 'Poděbrady' } },
    { en: 'Turnov', cs: 'Turnov', search: { country: 'czechia', q: 'Turnov' } },
    { en: 'Klášterec nad Ohří', cs: 'Klášterec nad Ohří', search: { country: 'czechia', q: 'Klášterec nad Ohří' } },
    { en: 'Rokycany', cs: 'Rokycany', search: { country: 'czechia', q: 'Rokycany' } },
    { en: 'Ústí nad Orlicí', cs: 'Ústí nad Orlicí', search: { country: 'czechia', q: 'Ústí nad Orlicí' } },
    { en: 'Hlučín', cs: 'Hlučín', search: { country: 'czechia', q: 'Hlučín' } },
    { en: 'Zábřeh', cs: 'Zábřeh', search: { country: 'czechia', q: 'Zábřeh' } },
    { en: 'Šternberk', cs: 'Šternberk', search: { country: 'czechia', q: 'Šternberk' } },
    { en: 'Aš', cs: 'Aš', search: { country: 'czechia', q: 'Aš' } },
    { en: 'Chodov', cs: 'Chodov', search: { country: 'czechia', q: 'Chodov' } },
    { en: 'Tachov', cs: 'Tachov', search: { country: 'czechia', q: 'Tachov' } },
    { en: 'Český Krumlov', cs: 'Český Krumlov', search: { country: 'czechia', q: 'Český Krumlov' } },
    { en: 'Roudnice nad Labem', cs: 'Roudnice nad Labem', search: { country: 'czechia', q: 'Roudnice nad Labem' } },
    { en: 'Mariánské Lázně', cs: 'Mariánské Lázně', search: { country: 'czechia', q: 'Mariánské Lázně' } },
    { en: 'Krupka', cs: 'Krupka', search: { country: 'czechia', q: 'Krupka' } },
    { en: 'Jaroměř', cs: 'Jaroměř', search: { country: 'czechia', q: 'Jaroměř' } },
    { en: 'Čelákovice', cs: 'Čelákovice', search: { country: 'czechia', q: 'Čelákovice' } },
    { en: 'Vrchlabí', cs: 'Vrchlabí', search: { country: 'czechia', q: 'Vrchlabí' } },
    { en: 'Vysoké Mýto', cs: 'Vysoké Mýto', search: { country: 'czechia', q: 'Vysoké Mýto' } },
    { en: 'Milovice', cs: 'Milovice', search: { country: 'czechia', q: 'Milovice' } },
    { en: 'Boskovice', cs: 'Boskovice', search: { country: 'czechia', q: 'Boskovice' } },
    { en: 'Nový Bor', cs: 'Nový Bor', search: { country: 'czechia', q: 'Nový Bor' } },
    { en: 'Holešov', cs: 'Holešov', search: { country: 'czechia', q: 'Holešov' } },
    { en: 'Vlašim', cs: 'Vlašim', search: { country: 'czechia', q: 'Vlašim' } },
    { en: 'Velké Meziříčí', cs: 'Velké Meziříčí', search: { country: 'czechia', q: 'Velké Meziříčí' } },
    { en: 'Uničov', cs: 'Uničov', search: { country: 'czechia', q: 'Uničov' } },
    { en: 'Kyjov', cs: 'Kyjov', search: { country: 'czechia', q: 'Kyjov' } },
    { en: 'Domažlice', cs: 'Domažlice', search: { country: 'czechia', q: 'Domažlice' } },
    { en: 'Kuřim', cs: 'Kuřim', search: { country: 'czechia', q: 'Kuřim' } },
    { en: 'Jeseník', cs: 'Jeseník', search: { country: 'czechia', q: 'Jeseník' } },
    { en: 'Humpolec', cs: 'Humpolec', search: { country: 'czechia', q: 'Humpolec' } },
    { en: 'Sušice', cs: 'Sušice', search: { country: 'czechia', q: 'Sušice' } },
    { en: 'Rumburk', cs: 'Rumburk', search: { country: 'czechia', q: 'Rumburk' } },
    { en: 'Rychnov nad Kněžnou', cs: 'Rychnov nad Kněžnou', search: { country: 'czechia', q: 'Rychnov nad Kněžnou' } },
    { en: 'Veselí nad Moravou', cs: 'Veselí nad Moravou', search: { country: 'czechia', q: 'Veselí nad Moravou' } },
    {
        en: 'Frenštát pod Radhoštěm',
        cs: 'Frenštát pod Radhoštěm',
        search: { country: 'czechia', q: 'Frenštát pod Radhoštěm' },
    },
    { en: 'Prachatice', cs: 'Prachatice', search: { country: 'czechia', q: 'Prachatice' } },
    { en: 'Čáslav', cs: 'Čáslav', search: { country: 'czechia', q: 'Čáslav' } },
    { en: 'Litomyšl', cs: 'Litomyšl', search: { country: 'czechia', q: 'Litomyšl' } },
    {
        en: 'Nové Město na Moravě',
        cs: 'Nové Město na Moravě',
        search: { country: 'czechia', q: 'Nové Město na Moravě' },
    },
    { en: 'Jesenice', cs: 'Jesenice', search: { country: 'czechia', q: 'Jesenice' } },
    { en: 'Králův Dvůr', cs: 'Králův Dvůr', search: { country: 'czechia', q: 'Králův Dvůr' } },
    {
        en: 'Frýdlant nad Ostravicí',
        cs: 'Frýdlant nad Ostravicí',
        search: { country: 'czechia', q: 'Frýdlant nad Ostravicí' },
    },
    { en: 'Přelouč', cs: 'Přelouč', search: { country: 'czechia', q: 'Přelouč' } },
    { en: 'Ivančice', cs: 'Ivančice', search: { country: 'czechia', q: 'Ivančice' } },
    { en: 'Lysá nad Labem', cs: 'Lysá nad Labem', search: { country: 'czechia', q: 'Lysá nad Labem' } },
    { en: 'Lanškroun', cs: 'Lanškroun', search: { country: 'czechia', q: 'Lanškroun' } },
    { en: 'Moravská Třebová', cs: 'Moravská Třebová', search: { country: 'czechia', q: 'Moravská Třebová' } },
    { en: 'Litovel', cs: 'Litovel', search: { country: 'czechia', q: 'Litovel' } },
    { en: 'Hlinsko', cs: 'Hlinsko', search: { country: 'czechia', q: 'Hlinsko' } },
    { en: 'Studénka', cs: 'Studénka', search: { country: 'czechia', q: 'Studénka' } },
    {
        en: 'Nové Město nad Metují',
        cs: 'Nové Město nad Metují',
        search: { country: 'czechia', q: 'Nové Město nad Metují' },
    },
    { en: 'Tišnov', cs: 'Tišnov', search: { country: 'czechia', q: 'Tišnov' } },
    { en: 'Mohelnice', cs: 'Mohelnice', search: { country: 'czechia', q: 'Mohelnice' } },
    { en: 'Chotěboř', cs: 'Chotěboř', search: { country: 'czechia', q: 'Chotěboř' } },
    { en: 'Nová Paka', cs: 'Nová Paka', search: { country: 'czechia', q: 'Nová Paka' } },
    { en: 'Hostivice', cs: 'Hostivice', search: { country: 'czechia', q: 'Hostivice' } },
    { en: 'Mnichovo Hradiště', cs: 'Mnichovo Hradiště', search: { country: 'czechia', q: 'Mnichovo Hradiště' } },
    { en: 'Dobříš', cs: 'Dobříš', search: { country: 'czechia', q: 'Dobříš' } },
    { en: 'Polička', cs: 'Polička', search: { country: 'czechia', q: 'Polička' } },
    { en: 'Roztoky', cs: 'Roztoky', search: { country: 'czechia', q: 'Roztoky' } },
    { en: 'Lovosice', cs: 'Lovosice', search: { country: 'czechia', q: 'Lovosice' } },
    { en: 'Štětí', cs: 'Štětí', search: { country: 'czechia', q: 'Štětí' } },
    { en: 'Choceň', cs: 'Choceň', search: { country: 'czechia', q: 'Choceň' } },
    { en: 'Duchcov', cs: 'Duchcov', search: { country: 'czechia', q: 'Duchcov' } },
    { en: 'Hořice', cs: 'Hořice', search: { country: 'czechia', q: 'Hořice' } },
    { en: 'Příbor', cs: 'Příbor', search: { country: 'czechia', q: 'Příbor' } },
    { en: 'Červený Kostelec', cs: 'Červený Kostelec', search: { country: 'czechia', q: 'Červený Kostelec' } },
    { en: 'Semily', cs: 'Semily', search: { country: 'czechia', q: 'Semily' } },
    { en: 'Milevsko', cs: 'Milevsko', search: { country: 'czechia', q: 'Milevsko' } },
    { en: 'Třeboň', cs: 'Třeboň', search: { country: 'czechia', q: 'Třeboň' } },
    {
        en: 'Bystřice pod Hostýnem',
        cs: 'Bystřice pod Hostýnem',
        search: { country: 'czechia', q: 'Bystřice pod Hostýnem' },
    },
    { en: 'Rýmařov', cs: 'Rýmařov', search: { country: 'czechia', q: 'Rýmařov' } },
    {
        en: 'Bystřice nad Pernštejnem',
        cs: 'Bystřice nad Pernštejnem',
        search: { country: 'czechia', q: 'Bystřice nad Pernštejnem' },
    },
    { en: 'Lipník nad Bečvou', cs: 'Lipník nad Bečvou', search: { country: 'czechia', q: 'Lipník nad Bečvou' } },
    { en: 'Týn nad Vltavou', cs: 'Týn nad Vltavou', search: { country: 'czechia', q: 'Týn nad Vltavou' } },
    { en: 'Dubí', cs: 'Dubí', search: { country: 'czechia', q: 'Dubí' } },
    { en: 'Nejdek', cs: 'Nejdek', search: { country: 'czechia', q: 'Nejdek' } },
    { en: 'Hrádek nad Nisou', cs: 'Hrádek nad Nisou', search: { country: 'czechia', q: 'Hrádek nad Nisou' } },
    { en: 'Šlapanice', cs: 'Šlapanice', search: { country: 'czechia', q: 'Šlapanice' } },
    { en: 'Stříbro', cs: 'Stříbro', search: { country: 'czechia', q: 'Stříbro' } },
    { en: 'Benátky nad Jizerou', cs: 'Benátky nad Jizerou', search: { country: 'czechia', q: 'Benátky nad Jizerou' } },
    { en: 'Rychvald', cs: 'Rychvald', search: { country: 'czechia', q: 'Rychvald' } },
    { en: 'Mikulov', cs: 'Mikulov', search: { country: 'czechia', q: 'Mikulov' } },
    { en: 'Frýdlant', cs: 'Frýdlant', search: { country: 'czechia', q: 'Frýdlant' } },
    { en: 'Vimperk', cs: 'Vimperk', search: { country: 'czechia', q: 'Vimperk' } },
    { en: 'Bílovec', cs: 'Bílovec', search: { country: 'czechia', q: 'Bílovec' } },
    { en: 'Černošice', cs: 'Černošice', search: { country: 'czechia', q: 'Černošice' } },
    { en: 'Vratimov', cs: 'Vratimov', search: { country: 'czechia', q: 'Vratimov' } },
    { en: 'Petřvald', cs: 'Petřvald', search: { country: 'czechia', q: 'Petřvald' } },
    { en: 'Odry', cs: 'Odry', search: { country: 'czechia', q: 'Odry' } },
    { en: 'Broumov', cs: 'Broumov', search: { country: 'czechia', q: 'Broumov' } },
    { en: 'Moravské Budějovice', cs: 'Moravské Budějovice', search: { country: 'czechia', q: 'Moravské Budějovice' } },
    { en: 'Kaplice', cs: 'Kaplice', search: { country: 'czechia', q: 'Kaplice' } },
    { en: 'Dačice', cs: 'Dačice', search: { country: 'czechia', q: 'Dačice' } },
    { en: 'Sezimovo Ústí', cs: 'Sezimovo Ústí', search: { country: 'czechia', q: 'Sezimovo Ústí' } },
    { en: 'Napajedla', cs: 'Napajedla', search: { country: 'czechia', q: 'Napajedla' } },
    { en: 'Český Brod', cs: 'Český Brod', search: { country: 'czechia', q: 'Český Brod' } },
    { en: 'Přeštice', cs: 'Přeštice', search: { country: 'czechia', q: 'Přeštice' } },
    { en: 'Slavkov u Brna', cs: 'Slavkov u Brna', search: { country: 'czechia', q: 'Slavkov u Brna' } },
    { en: 'Úvaly', cs: 'Úvaly', search: { country: 'czechia', q: 'Úvaly' } },
    { en: 'Vodňany', cs: 'Vodňany', search: { country: 'czechia', q: 'Vodňany' } },
    { en: 'Nýřany', cs: 'Nýřany', search: { country: 'czechia', q: 'Nýřany' } },
    { en: 'Hořovice', cs: 'Hořovice', search: { country: 'czechia', q: 'Hořovice' } },
    { en: 'Soběslav', cs: 'Soběslav', search: { country: 'czechia', q: 'Soběslav' } },
    { en: 'Nový Bydžov', cs: 'Nový Bydžov', search: { country: 'czechia', q: 'Nový Bydžov' } },
    { en: 'Sedlčany', cs: 'Sedlčany', search: { country: 'czechia', q: 'Sedlčany' } },
    { en: 'Letovice', cs: 'Letovice', search: { country: 'czechia', q: 'Letovice' } },
    { en: 'Kraslice', cs: 'Kraslice', search: { country: 'czechia', q: 'Kraslice' } },
    { en: 'Hulín', cs: 'Hulín', search: { country: 'czechia', q: 'Hulín' } },
    { en: 'Kravaře', cs: 'Kravaře', search: { country: 'czechia', q: 'Kravaře' } },
    { en: 'Dobruška', cs: 'Dobruška', search: { country: 'czechia', q: 'Dobruška' } },
    { en: 'Holice', cs: 'Holice', search: { country: 'czechia', q: 'Holice' } },
    { en: 'Staré Město', cs: 'Staré Město', search: { country: 'czechia', q: 'Staré Město' } },
    { en: 'Blatná', cs: 'Blatná', search: { country: 'czechia', q: 'Blatná' } },
    { en: 'Bučovice', cs: 'Bučovice', search: { country: 'czechia', q: 'Bučovice' } },
    { en: 'Letohrad', cs: 'Letohrad', search: { country: 'czechia', q: 'Letohrad' } },
    { en: 'Světlá nad Sázavou', cs: 'Světlá nad Sázavou', search: { country: 'czechia', q: 'Světlá nad Sázavou' } },
    { en: 'Šenov', cs: 'Šenov', search: { country: 'czechia', q: 'Šenov' } },
    { en: 'Podbořany', cs: 'Podbořany', search: { country: 'czechia', q: 'Podbořany' } },
    { en: 'Mimoň', cs: 'Mimoň', search: { country: 'czechia', q: 'Mimoň' } },
    { en: 'Rosice', cs: 'Rosice', search: { country: 'czechia', q: 'Rosice' } },
    { en: 'Veselí nad Lužnicí', cs: 'Veselí nad Lužnicí', search: { country: 'czechia', q: 'Veselí nad Lužnicí' } },
    { en: 'Dubňany', cs: 'Dubňany', search: { country: 'czechia', q: 'Dubňany' } },
    { en: 'Slavičín', cs: 'Slavičín', search: { country: 'czechia', q: 'Slavičín' } },
    { en: 'Chrastava', cs: 'Chrastava', search: { country: 'czechia', q: 'Chrastava' } },
    { en: 'Odolena Voda', cs: 'Odolena Voda', search: { country: 'czechia', q: 'Odolena Voda' } },
    { en: 'Kostelec nad Orlicí', cs: 'Kostelec nad Orlicí', search: { country: 'czechia', q: 'Kostelec nad Orlicí' } },
    { en: 'Dobřany', cs: 'Dobřany', search: { country: 'czechia', q: 'Dobřany' } },
    { en: 'Tanvald', cs: 'Tanvald', search: { country: 'czechia', q: 'Tanvald' } },
    { en: 'Mníšek pod Brdy', cs: 'Mníšek pod Brdy', search: { country: 'czechia', q: 'Mníšek pod Brdy' } },
    { en: 'Hronov', cs: 'Hronov', search: { country: 'czechia', q: 'Hronov' } },
    { en: 'Týniště nad Orlicí', cs: 'Týniště nad Orlicí', search: { country: 'czechia', q: 'Týniště nad Orlicí' } },
    { en: 'Žamberk', cs: 'Žamberk', search: { country: 'czechia', q: 'Žamberk' } },
    { en: 'Železný Brod', cs: 'Železný Brod', search: { country: 'czechia', q: 'Železný Brod' } },
    { en: 'Hustopeče', cs: 'Hustopeče', search: { country: 'czechia', q: 'Hustopeče' } },
    { en: 'Kojetín', cs: 'Kojetín', search: { country: 'czechia', q: 'Kojetín' } },
    { en: 'Rousínov', cs: 'Rousínov', search: { country: 'czechia', q: 'Rousínov' } },
    { en: 'Šluknov', cs: 'Šluknov', search: { country: 'czechia', q: 'Šluknov' } },
    {
        en: 'Třebechovice pod Orebem',
        cs: 'Třebechovice pod Orebem',
        search: { country: 'czechia', q: 'Třebechovice pod Orebem' },
    },
    { en: 'Týnec nad Sázavou', cs: 'Týnec nad Sázavou', search: { country: 'czechia', q: 'Týnec nad Sázavou' } },
    { en: 'Moravský Krumlov', cs: 'Moravský Krumlov', search: { country: 'czechia', q: 'Moravský Krumlov' } },
    { en: 'Třešť', cs: 'Třešť', search: { country: 'czechia', q: 'Třešť' } },
    { en: 'Úpice', cs: 'Úpice', search: { country: 'czechia', q: 'Úpice' } },
    { en: 'Vítkov', cs: 'Vítkov', search: { country: 'czechia', q: 'Vítkov' } },
    { en: 'Nové Strašecí', cs: 'Nové Strašecí', search: { country: 'czechia', q: 'Nové Strašecí' } },
    {
        en: 'Chlumec nad Cidlinou',
        cs: 'Chlumec nad Cidlinou',
        search: { country: 'czechia', q: 'Chlumec nad Cidlinou' },
    },
    { en: 'Fulnek', cs: 'Fulnek', search: { country: 'czechia', q: 'Fulnek' } },
    { en: 'Brumov-Bylnice', cs: 'Brumov-Bylnice', search: { country: 'czechia', q: 'Brumov-Bylnice' } },
    { en: 'Zubří', cs: 'Zubří', search: { country: 'czechia', q: 'Zubří' } },
    {
        en: 'Lomnice nad Popelkou',
        cs: 'Lomnice nad Popelkou',
        search: { country: 'czechia', q: 'Lomnice nad Popelkou' },
    },
    { en: 'Kunovice', cs: 'Kunovice', search: { country: 'czechia', q: 'Kunovice' } },
    { en: 'Hradec nad Moravicí', cs: 'Hradec nad Moravicí', search: { country: 'czechia', q: 'Hradec nad Moravicí' } },
    { en: 'Strážnice', cs: 'Strážnice', search: { country: 'czechia', q: 'Strážnice' } },
    { en: 'Hluboká nad Vltavou', cs: 'Hluboká nad Vltavou', search: { country: 'czechia', q: 'Hluboká nad Vltavou' } },
    { en: 'Jablunkov', cs: 'Jablunkov', search: { country: 'czechia', q: 'Jablunkov' } },
    { en: 'Jilemnice', cs: 'Jilemnice', search: { country: 'czechia', q: 'Jilemnice' } },
    { en: 'Františkovy Lázně', cs: 'Františkovy Lázně', search: { country: 'czechia', q: 'Františkovy Lázně' } },
    { en: 'Modřice', cs: 'Modřice', search: { country: 'czechia', q: 'Modřice' } },
    { en: 'Stochov', cs: 'Stochov', search: { country: 'czechia', q: 'Stochov' } },
    { en: 'Planá', cs: 'Planá', search: { country: 'czechia', q: 'Planá' } },
    { en: 'Horní Slavkov', cs: 'Horní Slavkov', search: { country: 'czechia', q: 'Horní Slavkov' } },
    { en: 'Trhové Sviny', cs: 'Trhové Sviny', search: { country: 'czechia', q: 'Trhové Sviny' } },
    { en: 'Telč', cs: 'Telč', search: { country: 'czechia', q: 'Telč' } },
    { en: 'Pohořelice', cs: 'Pohořelice', search: { country: 'czechia', q: 'Pohořelice' } },
    { en: 'Velká Bíteš', cs: 'Velká Bíteš', search: { country: 'czechia', q: 'Velká Bíteš' } },
    { en: 'Horažďovice', cs: 'Horažďovice', search: { country: 'czechia', q: 'Horažďovice' } },
    { en: 'Polná', cs: 'Polná', search: { country: 'czechia', q: 'Polná' } },
    { en: 'Česká Kamenice', cs: 'Česká Kamenice', search: { country: 'czechia', q: 'Česká Kamenice' } },
    { en: 'Doksy', cs: 'Doksy', search: { country: 'czechia', q: 'Doksy' } },
    { en: 'Kosmonosy', cs: 'Kosmonosy', search: { country: 'czechia', q: 'Kosmonosy' } },
    { en: 'Starý Plzenec', cs: 'Starý Plzenec', search: { country: 'czechia', q: 'Starý Plzenec' } },
    { en: 'Rudná', cs: 'Rudná', search: { country: 'czechia', q: 'Rudná' } },
    { en: 'Holýšov', cs: 'Holýšov', search: { country: 'czechia', q: 'Holýšov' } },
    { en: 'Kdyně', cs: 'Kdyně', search: { country: 'czechia', q: 'Kdyně' } },
    { en: 'Bakov nad Jizerou', cs: 'Bakov nad Jizerou', search: { country: 'czechia', q: 'Bakov nad Jizerou' } },
    { en: 'Třemošná', cs: 'Třemošná', search: { country: 'czechia', q: 'Třemošná' } },
    { en: 'Jílové', cs: 'Jílové', search: { country: 'czechia', q: 'Jílové' } },
    { en: 'Luhačovice', cs: 'Luhačovice', search: { country: 'czechia', q: 'Luhačovice' } },
    { en: 'Skuteč', cs: 'Skuteč', search: { country: 'czechia', q: 'Skuteč' } },
    { en: 'Česká Skalice', cs: 'Česká Skalice', search: { country: 'czechia', q: 'Česká Skalice' } },
    { en: 'Horšovský Týn', cs: 'Horšovský Týn', search: { country: 'czechia', q: 'Horšovský Týn' } },
    { en: 'Bechyně', cs: 'Bechyně', search: { country: 'czechia', q: 'Bechyně' } },
    { en: 'Ledeč nad Sázavou', cs: 'Ledeč nad Sázavou', search: { country: 'czechia', q: 'Ledeč nad Sázavou' } },
    { en: 'Vrbno pod Pradědem', cs: 'Vrbno pod Pradědem', search: { country: 'czechia', q: 'Vrbno pod Pradědem' } },
    { en: 'Nýrsko', cs: 'Nýrsko', search: { country: 'czechia', q: 'Nýrsko' } },
    { en: 'Valašské Klobouky', cs: 'Valašské Klobouky', search: { country: 'czechia', q: 'Valašské Klobouky' } },
    { en: 'Jílové u Prahy', cs: 'Jílové u Prahy', search: { country: 'czechia', q: 'Jílové u Prahy' } },
    { en: 'Meziboří', cs: 'Meziboří', search: { country: 'czechia', q: 'Meziboří' } },
    { en: 'Chropyně', cs: 'Chropyně', search: { country: 'czechia', q: 'Chropyně' } },
    { en: 'Vizovice', cs: 'Vizovice', search: { country: 'czechia', q: 'Vizovice' } },
    { en: 'Habartov', cs: 'Habartov', search: { country: 'czechia', q: 'Habartov' } },
    { en: 'Zruč nad Sázavou', cs: 'Zruč nad Sázavou', search: { country: 'czechia', q: 'Zruč nad Sázavou' } },
    { en: 'Náměšť nad Oslavou', cs: 'Náměšť nad Oslavou', search: { country: 'czechia', q: 'Náměšť nad Oslavou' } },
    { en: 'Unhošť', cs: 'Unhošť', search: { country: 'czechia', q: 'Unhošť' } },
    { en: 'Pečky', cs: 'Pečky', search: { country: 'czechia', q: 'Pečky' } },
    { en: 'Heřmanův Městec', cs: 'Heřmanův Městec', search: { country: 'czechia', q: 'Heřmanův Městec' } },
    { en: 'Protivín', cs: 'Protivín', search: { country: 'czechia', q: 'Protivín' } },
    { en: 'Bělá pod Bezdězem', cs: 'Bělá pod Bezdězem', search: { country: 'czechia', q: 'Bělá pod Bezdězem' } },
    { en: 'Kynšperk nad Ohří', cs: 'Kynšperk nad Ohří', search: { country: 'czechia', q: 'Kynšperk nad Ohří' } },
    { en: 'Oslavany', cs: 'Oslavany', search: { country: 'czechia', q: 'Oslavany' } },
    { en: 'Postoloprty', cs: 'Postoloprty', search: { country: 'czechia', q: 'Postoloprty' } },
    { en: 'Osek', cs: 'Osek', search: { country: 'czechia', q: 'Osek' } },
    { en: 'Pacov', cs: 'Pacov', search: { country: 'czechia', q: 'Pacov' } },
    { en: 'Vamberk', cs: 'Vamberk', search: { country: 'czechia', q: 'Vamberk' } },
    { en: 'Vracov', cs: 'Vracov', search: { country: 'czechia', q: 'Vracov' } },
    { en: 'Votice', cs: 'Votice', search: { country: 'czechia', q: 'Votice' } },
    { en: 'Adamov', cs: 'Adamov', search: { country: 'czechia', q: 'Adamov' } },
    { en: 'Lišov', cs: 'Lišov', search: { country: 'czechia', q: 'Lišov' } },
    { en: 'Cvikov', cs: 'Cvikov', search: { country: 'czechia', q: 'Cvikov' } },
    { en: 'Klimkovice', cs: 'Klimkovice', search: { country: 'czechia', q: 'Klimkovice' } },
    { en: 'Bor', cs: 'Bor', search: { country: 'czechia', q: 'Bor' } },
    { en: 'Bystřice', cs: 'Bystřice', search: { country: 'czechia', q: 'Bystřice' } },
    { en: 'Bzenec', cs: 'Bzenec', search: { country: 'czechia', q: 'Bzenec' } },
    { en: 'Bojkovice', cs: 'Bojkovice', search: { country: 'czechia', q: 'Bojkovice' } },
    { en: 'Hostinné', cs: 'Hostinné', search: { country: 'czechia', q: 'Hostinné' } },
    { en: 'Hluk', cs: 'Hluk', search: { country: 'czechia', q: 'Hluk' } },
    { en: 'Chlumec', cs: 'Chlumec', search: { country: 'czechia', q: 'Chlumec' } },
    {
        en: 'Rožmitál pod Třemšínem',
        cs: 'Rožmitál pod Třemšínem',
        search: { country: 'czechia', q: 'Rožmitál pod Třemšínem' },
    },
    { en: 'Planá nad Lužnicí', cs: 'Planá nad Lužnicí', search: { country: 'czechia', q: 'Planá nad Lužnicí' } },
    { en: 'Kostelec nad Labem', cs: 'Kostelec nad Labem', search: { country: 'czechia', q: 'Kostelec nad Labem' } },
    { en: 'Uherský Ostroh', cs: 'Uherský Ostroh', search: { country: 'czechia', q: 'Uherský Ostroh' } },
    { en: 'Slatiňany', cs: 'Slatiňany', search: { country: 'czechia', q: 'Slatiňany' } },
    { en: 'Zdice', cs: 'Zdice', search: { country: 'czechia', q: 'Zdice' } },
    { en: 'Borovany', cs: 'Borovany', search: { country: 'czechia', q: 'Borovany' } },
    { en: 'Králíky', cs: 'Králíky', search: { country: 'czechia', q: 'Králíky' } },
    { en: 'Nová Role', cs: 'Nová Role', search: { country: 'czechia', q: 'Nová Role' } },
    {
        en: 'Jaroměřice nad Rokytnou',
        cs: 'Jaroměřice nad Rokytnou',
        search: { country: 'czechia', q: 'Jaroměřice nad Rokytnou' },
    },
    { en: 'Horní Bříza', cs: 'Horní Bříza', search: { country: 'czechia', q: 'Horní Bříza' } },
    { en: 'Brušperk', cs: 'Brušperk', search: { country: 'czechia', q: 'Brušperk' } },
    { en: 'Blovice', cs: 'Blovice', search: { country: 'czechia', q: 'Blovice' } },
    { en: 'Dolní Benešov', cs: 'Dolní Benešov', search: { country: 'czechia', q: 'Dolní Benešov' } },
    { en: 'Sezemice', cs: 'Sezemice', search: { country: 'czechia', q: 'Sezemice' } },
    { en: 'Police nad Metují', cs: 'Police nad Metují', search: { country: 'czechia', q: 'Police nad Metují' } },
    { en: 'Jemnice', cs: 'Jemnice', search: { country: 'czechia', q: 'Jemnice' } },
    { en: 'Přibyslav', cs: 'Přibyslav', search: { country: 'czechia', q: 'Přibyslav' } },
    { en: 'Rajhrad', cs: 'Rajhrad', search: { country: 'czechia', q: 'Rajhrad' } },
    { en: 'Mnichovice', cs: 'Mnichovice', search: { country: 'czechia', q: 'Mnichovice' } },
    { en: 'Kamenický Šenov', cs: 'Kamenický Šenov', search: { country: 'czechia', q: 'Kamenický Šenov' } },
    { en: 'Paskov', cs: 'Paskov', search: { country: 'czechia', q: 'Paskov' } },
    { en: 'Velké Bílovice', cs: 'Velké Bílovice', search: { country: 'czechia', q: 'Velké Bílovice' } },
    { en: 'Stráž pod Ralskem', cs: 'Stráž pod Ralskem', search: { country: 'czechia', q: 'Stráž pod Ralskem' } },
    { en: 'Velešín', cs: 'Velešín', search: { country: 'czechia', q: 'Velešín' } },
    { en: 'Větřní', cs: 'Větřní', search: { country: 'czechia', q: 'Větřní' } },
    { en: 'Židlochovice', cs: 'Židlochovice', search: { country: 'czechia', q: 'Židlochovice' } },
    {
        en: 'Kostelec nad Černými lesy',
        cs: 'Kostelec nad Černými lesy',
        search: { country: 'czechia', q: 'Kostelec nad Černými lesy' },
    },
    { en: 'Brtnice', cs: 'Brtnice', search: { country: 'czechia', q: 'Brtnice' } },
    { en: 'Smržovka', cs: 'Smržovka', search: { country: 'czechia', q: 'Smržovka' } },
    { en: 'Sázava', cs: 'Sázava', search: { country: 'czechia', q: 'Sázava' } },
    { en: 'Rájec-Jestřebí', cs: 'Rájec-Jestřebí', search: { country: 'czechia', q: 'Rájec-Jestřebí' } },
    { en: 'Kamenice nad Lipou', cs: 'Kamenice nad Lipou', search: { country: 'czechia', q: 'Kamenice nad Lipou' } },
    { en: 'Zbýšov', cs: 'Zbýšov', search: { country: 'czechia', q: 'Zbýšov' } },
    { en: 'Dobřichovice', cs: 'Dobřichovice', search: { country: 'czechia', q: 'Dobřichovice' } },
    { en: 'Volary', cs: 'Volary', search: { country: 'czechia', q: 'Volary' } },
    { en: 'Nepomuk', cs: 'Nepomuk', search: { country: 'czechia', q: 'Nepomuk' } },
    { en: 'Fryšták', cs: 'Fryšták', search: { country: 'czechia', q: 'Fryšták' } },
    { en: 'Zlaté Hory', cs: 'Zlaté Hory', search: { country: 'czechia', q: 'Zlaté Hory' } },
    { en: 'Lanžhot', cs: 'Lanžhot', search: { country: 'czechia', q: 'Lanžhot' } },
    {
        en: 'Nové Město pod Smrkem',
        cs: 'Nové Město pod Smrkem',
        search: { country: 'czechia', q: 'Nové Město pod Smrkem' },
    },
    { en: 'Lom', cs: 'Lom', search: { country: 'czechia', q: 'Lom' } },
    { en: 'Lázně Bělohrad', cs: 'Lázně Bělohrad', search: { country: 'czechia', q: 'Lázně Bělohrad' } },
    { en: 'Klecany', cs: 'Klecany', search: { country: 'czechia', q: 'Klecany' } },
    {
        en: 'Benešov nad Ploučnicí',
        cs: 'Benešov nad Ploučnicí',
        search: { country: 'czechia', q: 'Benešov nad Ploučnicí' },
    },
    {
        en: 'Jablonné v Podještědí',
        cs: 'Jablonné v Podještědí',
        search: { country: 'czechia', q: 'Jablonné v Podještědí' },
    },
    { en: 'Toužim', cs: 'Toužim', search: { country: 'czechia', q: 'Toužim' } },
    { en: 'Buštěhrad', cs: 'Buštěhrad', search: { country: 'czechia', q: 'Buštěhrad' } },
    { en: 'Velké Opatovice', cs: 'Velké Opatovice', search: { country: 'czechia', q: 'Velké Opatovice' } },
    { en: 'Řevnice', cs: 'Řevnice', search: { country: 'czechia', q: 'Řevnice' } },
    { en: 'Jiříkov', cs: 'Jiříkov', search: { country: 'czechia', q: 'Jiříkov' } },
    { en: 'Valtice', cs: 'Valtice', search: { country: 'czechia', q: 'Valtice' } },
    { en: 'Stod', cs: 'Stod', search: { country: 'czechia', q: 'Stod' } },
    { en: 'Suchdol nad Lužnicí', cs: 'Suchdol nad Lužnicí', search: { country: 'czechia', q: 'Suchdol nad Lužnicí' } },
    { en: 'Lázně Bohdaneč', cs: 'Lázně Bohdaneč', search: { country: 'czechia', q: 'Lázně Bohdaneč' } },
    { en: 'Zliv', cs: 'Zliv', search: { country: 'czechia', q: 'Zliv' } },
    { en: 'Štěpánov', cs: 'Štěpánov', search: { country: 'czechia', q: 'Štěpánov' } },
    { en: 'Březnice', cs: 'Březnice', search: { country: 'czechia', q: 'Březnice' } },
    { en: 'České Velenice', cs: 'České Velenice', search: { country: 'czechia', q: 'České Velenice' } },
    { en: 'Velká Bystřice', cs: 'Velká Bystřice', search: { country: 'czechia', q: 'Velká Bystřice' } },
    { en: 'Libochovice', cs: 'Libochovice', search: { country: 'czechia', q: 'Libochovice' } },
    { en: 'Město Albrechtice', cs: 'Město Albrechtice', search: { country: 'czechia', q: 'Město Albrechtice' } },
    { en: 'Libčice nad Vltavou', cs: 'Libčice nad Vltavou', search: { country: 'czechia', q: 'Libčice nad Vltavou' } },
    { en: 'Štramberk', cs: 'Štramberk', search: { country: 'czechia', q: 'Štramberk' } },
    { en: 'Kralovice', cs: 'Kralovice', search: { country: 'czechia', q: 'Kralovice' } },
    { en: 'Dobrovice', cs: 'Dobrovice', search: { country: 'czechia', q: 'Dobrovice' } },
    { en: 'Veverská Bítýška', cs: 'Veverská Bítýška', search: { country: 'czechia', q: 'Veverská Bítýška' } },
    { en: 'Krásná Lípa', cs: 'Krásná Lípa', search: { country: 'czechia', q: 'Krásná Lípa' } },
    { en: 'Újezd u Brna', cs: 'Újezd u Brna', search: { country: 'czechia', q: 'Újezd u Brna' } },
    { en: 'Libušín', cs: 'Libušín', search: { country: 'czechia', q: 'Libušín' } },
    { en: 'Trmice', cs: 'Trmice', search: { country: 'czechia', q: 'Trmice' } },
    { en: 'Staňkov', cs: 'Staňkov', search: { country: 'czechia', q: 'Staňkov' } },
    {
        en: 'Hrušovany nad Jevišovkou',
        cs: 'Hrušovany nad Jevišovkou',
        search: { country: 'czechia', q: 'Hrušovany nad Jevišovkou' },
    },
    { en: 'Nová Bystřice', cs: 'Nová Bystřice', search: { country: 'czechia', q: 'Nová Bystřice' } },
    { en: 'Sadská', cs: 'Sadská', search: { country: 'czechia', q: 'Sadská' } },
    { en: 'Košťany', cs: 'Košťany', search: { country: 'czechia', q: 'Košťany' } },
    { en: 'Chrast', cs: 'Chrast', search: { country: 'czechia', q: 'Chrast' } },
    { en: 'Jablonné nad Orlicí', cs: 'Jablonné nad Orlicí', search: { country: 'czechia', q: 'Jablonné nad Orlicí' } },
    {
        en: 'Ždírec nad Doubravou',
        cs: 'Ždírec nad Doubravou',
        search: { country: 'czechia', q: 'Ždírec nad Doubravou' },
    },
    { en: 'Žacléř', cs: 'Žacléř', search: { country: 'czechia', q: 'Žacléř' } },
    { en: 'Uhlířské Janovice', cs: 'Uhlířské Janovice', search: { country: 'czechia', q: 'Uhlířské Janovice' } },
    { en: 'Velké Pavlovice', cs: 'Velké Pavlovice', search: { country: 'czechia', q: 'Velké Pavlovice' } },
    { en: 'Desná', cs: 'Desná', search: { country: 'czechia', q: 'Desná' } },
    { en: 'Opočno', cs: 'Opočno', search: { country: 'czechia', q: 'Opočno' } },
    { en: 'Loket', cs: 'Loket', search: { country: 'czechia', q: 'Loket' } },
    { en: 'Velvary', cs: 'Velvary', search: { country: 'czechia', q: 'Velvary' } },
    { en: 'Kaznějov', cs: 'Kaznějov', search: { country: 'czechia', q: 'Kaznějov' } },
    { en: 'Břidličná', cs: 'Břidličná', search: { country: 'czechia', q: 'Břidličná' } },
    { en: 'Třemošnice', cs: 'Třemošnice', search: { country: 'czechia', q: 'Třemošnice' } },
    { en: 'Hanušovice', cs: 'Hanušovice', search: { country: 'czechia', q: 'Hanušovice' } },
    { en: 'Podivín', cs: 'Podivín', search: { country: 'czechia', q: 'Podivín' } },
    { en: 'Miroslav', cs: 'Miroslav', search: { country: 'czechia', q: 'Miroslav' } },
    { en: 'Volyně', cs: 'Volyně', search: { country: 'czechia', q: 'Volyně' } },
    {
        en: 'Hodkovice nad Mohelkou',
        cs: 'Hodkovice nad Mohelkou',
        search: { country: 'czechia', q: 'Hodkovice nad Mohelkou' },
    },
    { en: 'Rtyně v Podkrkonoší', cs: 'Rtyně v Podkrkonoší', search: { country: 'czechia', q: 'Rtyně v Podkrkonoší' } },
    { en: 'Teplá', cs: 'Teplá', search: { country: 'czechia', q: 'Teplá' } },
    { en: 'Morkovice-Slížany', cs: 'Morkovice-Slížany', search: { country: 'czechia', q: 'Morkovice-Slížany' } },
    { en: 'Loštice', cs: 'Loštice', search: { country: 'czechia', q: 'Loštice' } },
    { en: 'Slušovice', cs: 'Slušovice', search: { country: 'czechia', q: 'Slušovice' } },
    { en: 'Úštěk', cs: 'Úštěk', search: { country: 'czechia', q: 'Úštěk' } },
    { en: 'Chvaletice', cs: 'Chvaletice', search: { country: 'czechia', q: 'Chvaletice' } },
    { en: 'Ivanovice na Hané', cs: 'Ivanovice na Hané', search: { country: 'czechia', q: 'Ivanovice na Hané' } },
    { en: 'Smiřice', cs: 'Smiřice', search: { country: 'czechia', q: 'Smiřice' } },
    { en: 'Žirovnice', cs: 'Žirovnice', search: { country: 'czechia', q: 'Žirovnice' } },
    { en: 'Moravský Beroun', cs: 'Moravský Beroun', search: { country: 'czechia', q: 'Moravský Beroun' } },
    {
        en: 'Budišov nad Budišovkou',
        cs: 'Budišov nad Budišovkou',
        search: { country: 'czechia', q: 'Budišov nad Budišovkou' },
    },
    { en: 'Rotava', cs: 'Rotava', search: { country: 'czechia', q: 'Rotava' } },
    { en: 'Kostelec na Hané', cs: 'Kostelec na Hané', search: { country: 'czechia', q: 'Kostelec na Hané' } },
    { en: 'Spálené Poříčí', cs: 'Spálené Poříčí', search: { country: 'czechia', q: 'Spálené Poříčí' } },
    { en: 'Vejprty', cs: 'Vejprty', search: { country: 'czechia', q: 'Vejprty' } },
    { en: 'Sedlec-Prčice', cs: 'Sedlec-Prčice', search: { country: 'czechia', q: 'Sedlec-Prčice' } },
    { en: 'Terezín', cs: 'Terezín', search: { country: 'czechia', q: 'Terezín' } },
    { en: 'Zákupy', cs: 'Zákupy', search: { country: 'czechia', q: 'Zákupy' } },
    { en: 'Raspenava', cs: 'Raspenava', search: { country: 'czechia', q: 'Raspenava' } },
    { en: 'Hrádek', cs: 'Hrádek', search: { country: 'czechia', q: 'Hrádek' } },
    { en: 'Dolní Bousov', cs: 'Dolní Bousov', search: { country: 'czechia', q: 'Dolní Bousov' } },
    { en: 'Český Dub', cs: 'Český Dub', search: { country: 'czechia', q: 'Český Dub' } },
    { en: 'Kunštát', cs: 'Kunštát', search: { country: 'czechia', q: 'Kunštát' } },
    { en: 'Jevíčko', cs: 'Jevíčko', search: { country: 'czechia', q: 'Jevíčko' } },
    { en: 'Městec Králové', cs: 'Městec Králové', search: { country: 'czechia', q: 'Městec Králové' } },
    {
        en: 'Rychnov u Jablonce nad Nisou',
        cs: 'Rychnov u Jablonce nad Nisou',
        search: { country: 'czechia', q: 'Rychnov u Jablonce nad Nisou' },
    },
    { en: 'Plasy', cs: 'Plasy', search: { country: 'czechia', q: 'Plasy' } },
    { en: 'Konice', cs: 'Konice', search: { country: 'czechia', q: 'Konice' } },
    { en: 'Hejnice', cs: 'Hejnice', search: { country: 'czechia', q: 'Hejnice' } },
    { en: 'Javorník', cs: 'Javorník', search: { country: 'czechia', q: 'Javorník' } },
    { en: 'Mladá Vožice', cs: 'Mladá Vožice', search: { country: 'czechia', q: 'Mladá Vožice' } },
    { en: 'Koryčany', cs: 'Koryčany', search: { country: 'czechia', q: 'Koryčany' } },
    { en: 'Golčův Jeníkov', cs: 'Golčův Jeníkov', search: { country: 'czechia', q: 'Golčův Jeníkov' } },
    { en: 'Kelč', cs: 'Kelč', search: { country: 'czechia', q: 'Kelč' } },
    { en: 'Velké Hamry', cs: 'Velké Hamry', search: { country: 'czechia', q: 'Velké Hamry' } },
    { en: 'Neveklov', cs: 'Neveklov', search: { country: 'czechia', q: 'Neveklov' } },
    { en: 'Březová', cs: 'Březová', search: { country: 'czechia', q: 'Březová' } },
    { en: 'Vyšší Brod', cs: 'Vyšší Brod', search: { country: 'czechia', q: 'Vyšší Brod' } },
    { en: 'Luže', cs: 'Luže', search: { country: 'czechia', q: 'Luže' } },
    { en: 'Nové Sedlo', cs: 'Nové Sedlo', search: { country: 'czechia', q: 'Nové Sedlo' } },
    {
        en: 'Rokytnice nad Jizerou',
        cs: 'Rokytnice nad Jizerou',
        search: { country: 'czechia', q: 'Rokytnice nad Jizerou' },
    },
    { en: 'Rudolfov', cs: 'Rudolfov', search: { country: 'czechia', q: 'Rudolfov' } },
    { en: 'Netolice', cs: 'Netolice', search: { country: 'czechia', q: 'Netolice' } },
    { en: 'Počátky', cs: 'Počátky', search: { country: 'czechia', q: 'Počátky' } },
    { en: 'Chabařovice', cs: 'Chabařovice', search: { country: 'czechia', q: 'Chabařovice' } },
    { en: 'Nové Hrady', cs: 'Nové Hrady', search: { country: 'czechia', q: 'Nové Hrady' } },
    { en: 'Zbiroh', cs: 'Zbiroh', search: { country: 'czechia', q: 'Zbiroh' } },
    { en: 'Ždánice', cs: 'Ždánice', search: { country: 'czechia', q: 'Ždánice' } },
    { en: 'Klobouky u Brna', cs: 'Klobouky u Brna', search: { country: 'czechia', q: 'Klobouky u Brna' } },
    { en: 'Bohušovice nad Ohří', cs: 'Bohušovice nad Ohří', search: { country: 'czechia', q: 'Bohušovice nad Ohří' } },
    { en: 'Chýnov', cs: 'Chýnov', search: { country: 'czechia', q: 'Chýnov' } },
    { en: 'Dolní Kounice', cs: 'Dolní Kounice', search: { country: 'czechia', q: 'Dolní Kounice' } },
    { en: 'Tovačov', cs: 'Tovačov', search: { country: 'czechia', q: 'Tovačov' } },
    { en: 'Karolinka', cs: 'Karolinka', search: { country: 'czechia', q: 'Karolinka' } },
    { en: 'Jáchymov', cs: 'Jáchymov', search: { country: 'czechia', q: 'Jáchymov' } },
    { en: 'Sobotka', cs: 'Sobotka', search: { country: 'czechia', q: 'Sobotka' } },
    { en: 'Dašice', cs: 'Dašice', search: { country: 'czechia', q: 'Dašice' } },
    { en: 'Meziměstí', cs: 'Meziměstí', search: { country: 'czechia', q: 'Meziměstí' } },
    { en: 'Kryry', cs: 'Kryry', search: { country: 'czechia', q: 'Kryry' } },
    { en: 'Nechanice', cs: 'Nechanice', search: { country: 'czechia', q: 'Nechanice' } },
    { en: 'Slavonice', cs: 'Slavonice', search: { country: 'czechia', q: 'Slavonice' } },
    {
        en: 'Janovice nad Úhlavou',
        cs: 'Janovice nad Úhlavou',
        search: { country: 'czechia', q: 'Janovice nad Úhlavou' },
    },
    { en: 'Plumlov', cs: 'Plumlov', search: { country: 'czechia', q: 'Plumlov' } },
    { en: 'Mirošov', cs: 'Mirošov', search: { country: 'czechia', q: 'Mirošov' } },
    { en: 'Nová Včelnice', cs: 'Nová Včelnice', search: { country: 'czechia', q: 'Nová Včelnice' } },
    { en: 'Veltrusy', cs: 'Veltrusy', search: { country: 'czechia', q: 'Veltrusy' } },
    { en: 'Žlutice', cs: 'Žlutice', search: { country: 'czechia', q: 'Žlutice' } },
    { en: 'Solnice', cs: 'Solnice', search: { country: 'czechia', q: 'Solnice' } },
    { en: 'Horní Jiřetín', cs: 'Horní Jiřetín', search: { country: 'czechia', q: 'Horní Jiřetín' } },
    { en: 'Horní Benešov', cs: 'Horní Benešov', search: { country: 'czechia', q: 'Horní Benešov' } },
    { en: 'Kardašova Řečice', cs: 'Kardašova Řečice', search: { country: 'czechia', q: 'Kardašova Řečice' } },
    { en: 'Žebrák', cs: 'Žebrák', search: { country: 'czechia', q: 'Žebrák' } },
    { en: 'Město Touškov', cs: 'Město Touškov', search: { country: 'czechia', q: 'Město Touškov' } },
    { en: 'Hranice', cs: 'Hranice', search: { country: 'czechia', q: 'Hranice' } },
    { en: 'Budyně nad Ohří', cs: 'Budyně nad Ohří', search: { country: 'czechia', q: 'Budyně nad Ohří' } },
    { en: 'Luby', cs: 'Luby', search: { country: 'czechia', q: 'Luby' } },
    { en: 'Ralsko', cs: 'Ralsko', search: { country: 'czechia', q: 'Ralsko' } },
    { en: 'Kopidlno', cs: 'Kopidlno', search: { country: 'czechia', q: 'Kopidlno' } },
    { en: 'Mikulášovice', cs: 'Mikulášovice', search: { country: 'czechia', q: 'Mikulášovice' } },
    { en: 'Borohrádek', cs: 'Borohrádek', search: { country: 'czechia', q: 'Borohrádek' } },
    { en: 'Týnec nad Labem', cs: 'Týnec nad Labem', search: { country: 'czechia', q: 'Týnec nad Labem' } },
    { en: 'Nový Knín', cs: 'Nový Knín', search: { country: 'czechia', q: 'Nový Knín' } },
    { en: 'Proseč', cs: 'Proseč', search: { country: 'czechia', q: 'Proseč' } },
    { en: 'Pyšely', cs: 'Pyšely', search: { country: 'czechia', q: 'Pyšely' } },
    { en: 'Horní Jelení', cs: 'Horní Jelení', search: { country: 'czechia', q: 'Horní Jelení' } },
    { en: 'Hrochův Týnec', cs: 'Hrochův Týnec', search: { country: 'czechia', q: 'Hrochův Týnec' } },
    { en: 'Horní Planá', cs: 'Horní Planá', search: { country: 'czechia', q: 'Horní Planá' } },
    { en: 'Hroznětín', cs: 'Hroznětín', search: { country: 'czechia', q: 'Hroznětín' } },
    { en: 'Svoboda nad Úpou', cs: 'Svoboda nad Úpou', search: { country: 'czechia', q: 'Svoboda nad Úpou' } },
    { en: 'Jistebnice', cs: 'Jistebnice', search: { country: 'czechia', q: 'Jistebnice' } },
    { en: 'Hrob', cs: 'Hrob', search: { country: 'czechia', q: 'Hrob' } },
    { en: 'Zásmuky', cs: 'Zásmuky', search: { country: 'czechia', q: 'Zásmuky' } },
    { en: 'Skalná', cs: 'Skalná', search: { country: 'czechia', q: 'Skalná' } },
    {
        en: 'Rokytnice v Orlických horách',
        cs: 'Rokytnice v Orlických horách',
        search: { country: 'czechia', q: 'Rokytnice v Orlických horách' },
    },
    { en: 'Štíty', cs: 'Štíty', search: { country: 'czechia', q: 'Štíty' } },
    { en: 'Velký Šenov', cs: 'Velký Šenov', search: { country: 'czechia', q: 'Velký Šenov' } },
    { en: 'Němčice nad Hanou', cs: 'Němčice nad Hanou', search: { country: 'czechia', q: 'Němčice nad Hanou' } },
    { en: 'Plesná', cs: 'Plesná', search: { country: 'czechia', q: 'Plesná' } },
    { en: 'Třebenice', cs: 'Třebenice', search: { country: 'czechia', q: 'Třebenice' } },
    { en: 'Libáň', cs: 'Libáň', search: { country: 'czechia', q: 'Libáň' } },
    { en: 'Smečno', cs: 'Smečno', search: { country: 'czechia', q: 'Smečno' } },
    { en: 'Bochov', cs: 'Bochov', search: { country: 'czechia', q: 'Bochov' } },
    { en: 'Kouřim', cs: 'Kouřim', search: { country: 'czechia', q: 'Kouřim' } },
    { en: 'Lučany nad Nisou', cs: 'Lučany nad Nisou', search: { country: 'czechia', q: 'Lučany nad Nisou' } },
    { en: 'Žandov', cs: 'Žandov', search: { country: 'czechia', q: 'Žandov' } },
    { en: 'Horní Cerekev', cs: 'Horní Cerekev', search: { country: 'czechia', q: 'Horní Cerekev' } },
    { en: 'Vroutek', cs: 'Vroutek', search: { country: 'czechia', q: 'Vroutek' } },
    { en: 'Hostomice', cs: 'Hostomice', search: { country: 'czechia', q: 'Hostomice' } },
    { en: 'Radnice', cs: 'Radnice', search: { country: 'czechia', q: 'Radnice' } },
    { en: 'Lomnice nad Lužnicí', cs: 'Lomnice nad Lužnicí', search: { country: 'czechia', q: 'Lomnice nad Lužnicí' } },
    { en: 'Hrotovice', cs: 'Hrotovice', search: { country: 'czechia', q: 'Hrotovice' } },
    { en: 'Černovice', cs: 'Černovice', search: { country: 'czechia', q: 'Černovice' } },
    { en: 'Bělá nad Radbuzou', cs: 'Bělá nad Radbuzou', search: { country: 'czechia', q: 'Bělá nad Radbuzou' } },
    { en: 'Seč', cs: 'Seč', search: { country: 'czechia', q: 'Seč' } },
    { en: 'Hoštka', cs: 'Hoštka', search: { country: 'czechia', q: 'Hoštka' } },
    { en: 'Dolní Poustevna', cs: 'Dolní Poustevna', search: { country: 'czechia', q: 'Dolní Poustevna' } },
    { en: 'Vlachovo Březí', cs: 'Vlachovo Březí', search: { country: 'czechia', q: 'Vlachovo Březí' } },
    { en: 'Dubá', cs: 'Dubá', search: { country: 'czechia', q: 'Dubá' } },
    { en: 'Ronov nad Doubravou', cs: 'Ronov nad Doubravou', search: { country: 'czechia', q: 'Ronov nad Doubravou' } },
    { en: 'Jesenice', cs: 'Jesenice', search: { country: 'czechia', q: 'Jesenice' } },
    { en: 'Staré Město', cs: 'Staré Město', search: { country: 'czechia', q: 'Staré Město' } },
    { en: 'Nasavrky', cs: 'Nasavrky', search: { country: 'czechia', q: 'Nasavrky' } },
    { en: 'Olešnice', cs: 'Olešnice', search: { country: 'czechia', q: 'Olešnice' } },
    { en: 'Švihov', cs: 'Švihov', search: { country: 'czechia', q: 'Švihov' } },
    { en: 'Plánice', cs: 'Plánice', search: { country: 'czechia', q: 'Plánice' } },
    { en: 'Oloví', cs: 'Oloví', search: { country: 'czechia', q: 'Oloví' } },
    { en: 'Rožďalovice', cs: 'Rožďalovice', search: { country: 'czechia', q: 'Rožďalovice' } },
    { en: 'Bavorov', cs: 'Bavorov', search: { country: 'czechia', q: 'Bavorov' } },
    { en: 'Kladruby', cs: 'Kladruby', search: { country: 'czechia', q: 'Kladruby' } },
    { en: 'Železná Ruda', cs: 'Železná Ruda', search: { country: 'czechia', q: 'Železná Ruda' } },
    {
        en: 'Březová nad Svitavou',
        cs: 'Březová nad Svitavou',
        search: { country: 'czechia', q: 'Březová nad Svitavou' },
    },
    { en: 'Všeruby', cs: 'Všeruby', search: { country: 'czechia', q: 'Všeruby' } },
    { en: 'Mirovice', cs: 'Mirovice', search: { country: 'czechia', q: 'Mirovice' } },
    { en: 'Teplice nad Metují', cs: 'Teplice nad Metují', search: { country: 'czechia', q: 'Teplice nad Metují' } },
    {
        en: 'Jablonec nad Jizerou',
        cs: 'Jablonec nad Jizerou',
        search: { country: 'czechia', q: 'Jablonec nad Jizerou' },
    },
    { en: 'Přimda', cs: 'Přimda', search: { country: 'czechia', q: 'Přimda' } },
    { en: 'Poběžovice', cs: 'Poběžovice', search: { country: 'czechia', q: 'Poběžovice' } },
    { en: 'Mýto', cs: 'Mýto', search: { country: 'czechia', q: 'Mýto' } },
    { en: 'Bystré', cs: 'Bystré', search: { country: 'czechia', q: 'Bystré' } },
    { en: 'Kožlany', cs: 'Kožlany', search: { country: 'czechia', q: 'Kožlany' } },
    { en: 'Strmilov', cs: 'Strmilov', search: { country: 'czechia', q: 'Strmilov' } },
    { en: 'Mšeno', cs: 'Mšeno', search: { country: 'czechia', q: 'Mšeno' } },
    { en: 'Husinec', cs: 'Husinec', search: { country: 'czechia', q: 'Husinec' } },
    { en: 'Lázně Kynžvart', cs: 'Lázně Kynžvart', search: { country: 'czechia', q: 'Lázně Kynžvart' } },
    { en: 'Strážov', cs: 'Strážov', search: { country: 'czechia', q: 'Strážov' } },
    { en: 'Trhový Štěpánov', cs: 'Trhový Štěpánov', search: { country: 'czechia', q: 'Trhový Štěpánov' } },
    { en: 'Kašperské Hory', cs: 'Kašperské Hory', search: { country: 'czechia', q: 'Kašperské Hory' } },
    { en: 'Svratka', cs: 'Svratka', search: { country: 'czechia', q: 'Svratka' } },
    { en: 'Chřibská', cs: 'Chřibská', search: { country: 'czechia', q: 'Chřibská' } },
    { en: 'Harrachov', cs: 'Harrachov', search: { country: 'czechia', q: 'Harrachov' } },
    { en: 'Habry', cs: 'Habry', search: { country: 'czechia', q: 'Habry' } },
    { en: 'Železnice', cs: 'Železnice', search: { country: 'czechia', q: 'Železnice' } },
    { en: 'Kasejovice', cs: 'Kasejovice', search: { country: 'czechia', q: 'Kasejovice' } },
    { en: 'Brandýs nad Orlicí', cs: 'Brandýs nad Orlicí', search: { country: 'czechia', q: 'Brandýs nad Orlicí' } },
    {
        en: 'Rovensko pod Troskami',
        cs: 'Rovensko pod Troskami',
        search: { country: 'czechia', q: 'Rovensko pod Troskami' },
    },
    { en: 'Vysoké nad Jizerou', cs: 'Vysoké nad Jizerou', search: { country: 'czechia', q: 'Vysoké nad Jizerou' } },
    { en: 'Vidnava', cs: 'Vidnava', search: { country: 'czechia', q: 'Vidnava' } },
    { en: 'Sedlice', cs: 'Sedlice', search: { country: 'czechia', q: 'Sedlice' } },
    { en: 'Mirotice', cs: 'Mirotice', search: { country: 'czechia', q: 'Mirotice' } },
    { en: 'Pilníkov', cs: 'Pilníkov', search: { country: 'czechia', q: 'Pilníkov' } },
    { en: 'Hostouň', cs: 'Hostouň', search: { country: 'czechia', q: 'Hostouň' } },
    { en: 'Žulová', cs: 'Žulová', search: { country: 'czechia', q: 'Žulová' } },
    { en: 'Černošín', cs: 'Černošín', search: { country: 'czechia', q: 'Černošín' } },
    { en: 'Potštát', cs: 'Potštát', search: { country: 'czechia', q: 'Potštát' } },
    { en: 'Osečná', cs: 'Osečná', search: { country: 'czechia', q: 'Osečná' } },
    { en: 'Verneřice', cs: 'Verneřice', search: { country: 'czechia', q: 'Verneřice' } },
    { en: 'Nalžovské Hory', cs: 'Nalžovské Hory', search: { country: 'czechia', q: 'Nalžovské Hory' } },
    { en: 'Úsov', cs: 'Úsov', search: { country: 'czechia', q: 'Úsov' } },
    { en: 'Jevišovice', cs: 'Jevišovice', search: { country: 'czechia', q: 'Jevišovice' } },
    { en: 'Manětín', cs: 'Manětín', search: { country: 'czechia', q: 'Manětín' } },
    { en: 'Měčín', cs: 'Měčín', search: { country: 'czechia', q: 'Měčín' } },
    {
        en: 'Krásná Hora nad Vltavou',
        cs: 'Krásná Hora nad Vltavou',
        search: { country: 'czechia', q: 'Krásná Hora nad Vltavou' },
    },
    { en: 'Špindlerův Mlýn', cs: 'Špindlerův Mlýn', search: { country: 'czechia', q: 'Špindlerův Mlýn' } },
    { en: 'Liběchov', cs: 'Liběchov', search: { country: 'czechia', q: 'Liběchov' } },
    { en: 'Červená Řečice', cs: 'Červená Řečice', search: { country: 'czechia', q: 'Červená Řečice' } },
    { en: 'Blšany', cs: 'Blšany', search: { country: 'czechia', q: 'Blšany' } },
    { en: 'Bělčice', cs: 'Bělčice', search: { country: 'czechia', q: 'Bělčice' } },
    { en: 'Bečov nad Teplou', cs: 'Bečov nad Teplou', search: { country: 'czechia', q: 'Bečov nad Teplou' } },
    { en: 'Hartmanice', cs: 'Hartmanice', search: { country: 'czechia', q: 'Hartmanice' } },
    { en: 'Bezdružice', cs: 'Bezdružice', search: { country: 'czechia', q: 'Bezdružice' } },
    { en: 'Miletín', cs: 'Miletín', search: { country: 'czechia', q: 'Miletín' } },
    { en: 'Abertamy', cs: 'Abertamy', search: { country: 'czechia', q: 'Abertamy' } },
    { en: 'Stráž nad Nežárkou', cs: 'Stráž nad Nežárkou', search: { country: 'czechia', q: 'Stráž nad Nežárkou' } },
    { en: 'Vysoké Veselí', cs: 'Vysoké Veselí', search: { country: 'czechia', q: 'Vysoké Veselí' } },
    { en: 'Deštná', cs: 'Deštná', search: { country: 'czechia', q: 'Deštná' } },
    { en: 'Krásno', cs: 'Krásno', search: { country: 'czechia', q: 'Krásno' } },
    { en: 'Janské Lázně', cs: 'Janské Lázně', search: { country: 'czechia', q: 'Janské Lázně' } },
    { en: 'Stárkov', cs: 'Stárkov', search: { country: 'czechia', q: 'Stárkov' } },
    { en: 'Lipnice nad Sázavou', cs: 'Lipnice nad Sázavou', search: { country: 'czechia', q: 'Lipnice nad Sázavou' } },
    { en: 'Pec pod Sněžkou', cs: 'Pec pod Sněžkou', search: { country: 'czechia', q: 'Pec pod Sněžkou' } },
    { en: 'Chyše', cs: 'Chyše', search: { country: 'czechia', q: 'Chyše' } },
    { en: 'Mašťov', cs: 'Mašťov', search: { country: 'czechia', q: 'Mašťov' } },
    { en: 'Ledvice', cs: 'Ledvice', search: { country: 'czechia', q: 'Ledvice' } },
    { en: 'Rabí', cs: 'Rabí', search: { country: 'czechia', q: 'Rabí' } },
    { en: 'Úterý', cs: 'Úterý', search: { country: 'czechia', q: 'Úterý' } },
    { en: 'Hora Svaté Kateřiny', cs: 'Hora Svaté Kateřiny', search: { country: 'czechia', q: 'Hora Svaté Kateřiny' } },
    { en: 'Výsluní', cs: 'Výsluní', search: { country: 'czechia', q: 'Výsluní' } },
    { en: 'Horní Blatná', cs: 'Horní Blatná', search: { country: 'czechia', q: 'Horní Blatná' } },
    { en: 'Krásné Údolí', cs: 'Krásné Údolí', search: { country: 'czechia', q: 'Krásné Údolí' } },
    {
        en: 'Rožmberk nad Vltavou',
        cs: 'Rožmberk nad Vltavou',
        search: { country: 'czechia', q: 'Rožmberk nad Vltavou' },
    },
    { en: 'Andělská Hora', cs: 'Andělská Hora', search: { country: 'czechia', q: 'Andělská Hora' } },
    { en: 'Janov', cs: 'Janov', search: { country: 'czechia', q: 'Janov' } },
    { en: 'Rejštejn', cs: 'Rejštejn', search: { country: 'czechia', q: 'Rejštejn' } },
    { en: 'Boží Dar', cs: 'Boží Dar', search: { country: 'czechia', q: 'Boží Dar' } },
    {
        en: 'Loučná pod Klínovcem',
        cs: 'Loučná pod Klínovcem',
        search: { country: 'czechia', q: 'Loučná pod Klínovcem' },
    },
    { en: 'Přebuz', cs: 'Přebuz', search: { country: 'czechia', q: 'Přebuz' } },
    { en: 'Hlavní město Praha', cs: 'Hlavní město Praha', search: { country: 'czechia', q: 'Hlavní město Praha' } },
    { en: 'Středočeský kraj', cs: 'Středočeský kraj', search: { country: 'czechia', q: 'Středočeský kraj' } },
    { en: 'Jihočeský kraj', cs: 'Jihočeský kraj', search: { country: 'czechia', q: 'Jihočeský kraj' } },
    { en: 'Plzeňský kraj', cs: 'Plzeňský kraj', search: { country: 'czechia', q: 'Plzeňský kraj' } },
    { en: 'Karlovarský kraj', cs: 'Karlovarský kraj', search: { country: 'czechia', q: 'Karlovarský kraj' } },
    { en: 'Ústecký kraj', cs: 'Ústecký kraj', search: { country: 'czechia', q: 'Ústecký kraj' } },
    { en: 'Liberecký kraj', cs: 'Liberecký kraj', search: { country: 'czechia', q: 'Liberecký kraj' } },
    {
        en: 'Královéhradecký kraj',
        cs: 'Královéhradecký kraj',
        search: { country: 'czechia', q: 'Královéhradecký kraj' },
    },
    { en: 'Pardubický kraj', cs: 'Pardubický kraj', search: { country: 'czechia', q: 'Pardubický kraj' } },
    { en: 'Kraj Vysočina', cs: 'Kraj Vysočina', search: { country: 'czechia', q: 'Kraj Vysočina' } },
    { en: 'Jihomoravský kraj', cs: 'Jihomoravský kraj', search: { country: 'czechia', q: 'Jihomoravský kraj' } },
    { en: 'Olomoucký kraj', cs: 'Olomoucký kraj', search: { country: 'czechia', q: 'Olomoucký kraj' } },
    {
        en: 'Moravskoslezský kraj',
        cs: 'Moravskoslezský kraj',
        search: { country: 'czechia', q: 'Moravskoslezský kraj' },
    },
    { en: 'Zlínský kraj', cs: 'Zlínský kraj', search: { country: 'czechia', q: 'Zlínský kraj' } },
    { en: '', cs: '', search: { country: 'czechia', q: '' } },
    { en: 'Okres Benešov', cs: 'Okres Benešov', search: { country: 'czechia', q: 'Okres Benešov' } },
    { en: 'Okres Beroun', cs: 'Okres Beroun', search: { country: 'czechia', q: 'Okres Beroun' } },
    { en: 'Okres Blansko', cs: 'Okres Blansko', search: { country: 'czechia', q: 'Okres Blansko' } },
    { en: 'Okres Brno-město', cs: 'Okres Brno-město', search: { country: 'czechia', q: 'Okres Brno-město' } },
    { en: 'Okres Brno-venkov', cs: 'Okres Brno-venkov', search: { country: 'czechia', q: 'Okres Brno-venkov' } },
    { en: 'Okres Bruntál', cs: 'Okres Bruntál', search: { country: 'czechia', q: 'Okres Bruntál' } },
    { en: 'Okres Břeclav', cs: 'Okres Břeclav', search: { country: 'czechia', q: 'Okres Břeclav' } },
    { en: 'Okres Česká Lípa', cs: 'Okres Česká Lípa', search: { country: 'czechia', q: 'Okres Česká Lípa' } },
    {
        en: 'Okres České Budějovice',
        cs: 'Okres České Budějovice',
        search: { country: 'czechia', q: 'Okres České Budějovice' },
    },
    { en: 'Okres Český Krumlov', cs: 'Okres Český Krumlov', search: { country: 'czechia', q: 'Okres Český Krumlov' } },
    { en: 'Okres Děčín', cs: 'Okres Děčín', search: { country: 'czechia', q: 'Okres Děčín' } },
    { en: 'Okres Domažlice', cs: 'Okres Domažlice', search: { country: 'czechia', q: 'Okres Domažlice' } },
    { en: 'Okres Frýdek-Místek', cs: 'Okres Frýdek-Místek', search: { country: 'czechia', q: 'Okres Frýdek-Místek' } },
    {
        en: 'Okres Havlíčkův Brod',
        cs: 'Okres Havlíčkův Brod',
        search: { country: 'czechia', q: 'Okres Havlíčkův Brod' },
    },
    { en: 'Okres Hodonín', cs: 'Okres Hodonín', search: { country: 'czechia', q: 'Okres Hodonín' } },
    {
        en: 'Okres Hradec Králové',
        cs: 'Okres Hradec Králové',
        search: { country: 'czechia', q: 'Okres Hradec Králové' },
    },
    { en: 'Okres Cheb', cs: 'Okres Cheb', search: { country: 'czechia', q: 'Okres Cheb' } },
    { en: 'Okres Chomutov', cs: 'Okres Chomutov', search: { country: 'czechia', q: 'Okres Chomutov' } },
    { en: 'Okres Chrudim', cs: 'Okres Chrudim', search: { country: 'czechia', q: 'Okres Chrudim' } },
    {
        en: 'Okres Jablonec nad Nisou',
        cs: 'Okres Jablonec nad Nisou',
        search: { country: 'czechia', q: 'Okres Jablonec nad Nisou' },
    },
    { en: 'Okres Jeseník', cs: 'Okres Jeseník', search: { country: 'czechia', q: 'Okres Jeseník' } },
    { en: 'Okres Jičín', cs: 'Okres Jičín', search: { country: 'czechia', q: 'Okres Jičín' } },
    { en: 'Okres Jihlava', cs: 'Okres Jihlava', search: { country: 'czechia', q: 'Okres Jihlava' } },
    {
        en: 'Okres Jindřichův Hradec',
        cs: 'Okres Jindřichův Hradec',
        search: { country: 'czechia', q: 'Okres Jindřichův Hradec' },
    },
    { en: 'Okres Karlovy Vary', cs: 'Okres Karlovy Vary', search: { country: 'czechia', q: 'Okres Karlovy Vary' } },
    { en: 'Okres Karviná', cs: 'Okres Karviná', search: { country: 'czechia', q: 'Okres Karviná' } },
    { en: 'Okres Kladno', cs: 'Okres Kladno', search: { country: 'czechia', q: 'Okres Kladno' } },
    { en: 'Okres Klatovy', cs: 'Okres Klatovy', search: { country: 'czechia', q: 'Okres Klatovy' } },
    { en: 'Okres Kolín', cs: 'Okres Kolín', search: { country: 'czechia', q: 'Okres Kolín' } },
    { en: 'Okres Kroměříž', cs: 'Okres Kroměříž', search: { country: 'czechia', q: 'Okres Kroměříž' } },
    { en: 'Okres Kutná Hora', cs: 'Okres Kutná Hora', search: { country: 'czechia', q: 'Okres Kutná Hora' } },
    { en: 'Okres Liberec', cs: 'Okres Liberec', search: { country: 'czechia', q: 'Okres Liberec' } },
    { en: 'Okres Litoměřice', cs: 'Okres Litoměřice', search: { country: 'czechia', q: 'Okres Litoměřice' } },
    { en: 'Okres Louny', cs: 'Okres Louny', search: { country: 'czechia', q: 'Okres Louny' } },
    { en: 'Okres Mělník', cs: 'Okres Mělník', search: { country: 'czechia', q: 'Okres Mělník' } },
    {
        en: 'Okres Mladá Boleslav',
        cs: 'Okres Mladá Boleslav',
        search: { country: 'czechia', q: 'Okres Mladá Boleslav' },
    },
    { en: 'Okres Most', cs: 'Okres Most', search: { country: 'czechia', q: 'Okres Most' } },
    { en: 'Okres Náchod', cs: 'Okres Náchod', search: { country: 'czechia', q: 'Okres Náchod' } },
    { en: 'Okres Nový Jičín', cs: 'Okres Nový Jičín', search: { country: 'czechia', q: 'Okres Nový Jičín' } },
    { en: 'Okres Nymburk', cs: 'Okres Nymburk', search: { country: 'czechia', q: 'Okres Nymburk' } },
    { en: 'Okres Olomouc', cs: 'Okres Olomouc', search: { country: 'czechia', q: 'Okres Olomouc' } },
    { en: 'Okres Opava', cs: 'Okres Opava', search: { country: 'czechia', q: 'Okres Opava' } },
    { en: 'Okres Ostrava-město', cs: 'Okres Ostrava-město', search: { country: 'czechia', q: 'Okres Ostrava-město' } },
    { en: 'Okres Pardubice', cs: 'Okres Pardubice', search: { country: 'czechia', q: 'Okres Pardubice' } },
    { en: 'Okres Pelhřimov', cs: 'Okres Pelhřimov', search: { country: 'czechia', q: 'Okres Pelhřimov' } },
    { en: 'Okres Písek', cs: 'Okres Písek', search: { country: 'czechia', q: 'Okres Písek' } },
    { en: 'Okres Plzeň-jih', cs: 'Okres Plzeň-jih', search: { country: 'czechia', q: 'Okres Plzeň-jih' } },
    { en: 'Okres Plzeň-město', cs: 'Okres Plzeň-město', search: { country: 'czechia', q: 'Okres Plzeň-město' } },
    { en: 'Okres Plzeň-sever', cs: 'Okres Plzeň-sever', search: { country: 'czechia', q: 'Okres Plzeň-sever' } },
    { en: 'Hlavní město Praha', cs: 'Hlavní město Praha', search: { country: 'czechia', q: 'Hlavní město Praha' } },
    { en: 'Okres Praha-východ', cs: 'Okres Praha-východ', search: { country: 'czechia', q: 'Okres Praha-východ' } },
    { en: 'Okres Praha-západ', cs: 'Okres Praha-západ', search: { country: 'czechia', q: 'Okres Praha-západ' } },
    { en: 'Okres Prachatice', cs: 'Okres Prachatice', search: { country: 'czechia', q: 'Okres Prachatice' } },
    { en: 'Okres Prostějov', cs: 'Okres Prostějov', search: { country: 'czechia', q: 'Okres Prostějov' } },
    { en: 'Okres Přerov', cs: 'Okres Přerov', search: { country: 'czechia', q: 'Okres Přerov' } },
    { en: 'Okres Příbram', cs: 'Okres Příbram', search: { country: 'czechia', q: 'Okres Příbram' } },
    { en: 'Okres Rakovník', cs: 'Okres Rakovník', search: { country: 'czechia', q: 'Okres Rakovník' } },
    { en: 'Okres Rokycany', cs: 'Okres Rokycany', search: { country: 'czechia', q: 'Okres Rokycany' } },
    {
        en: 'Okres Rychnov nad Kněžnou',
        cs: 'Okres Rychnov nad Kněžnou',
        search: { country: 'czechia', q: 'Okres Rychnov nad Kněžnou' },
    },
    { en: 'Okres Semily', cs: 'Okres Semily', search: { country: 'czechia', q: 'Okres Semily' } },
    { en: 'Okres Sokolov', cs: 'Okres Sokolov', search: { country: 'czechia', q: 'Okres Sokolov' } },
    { en: 'Okres Strakonice', cs: 'Okres Strakonice', search: { country: 'czechia', q: 'Okres Strakonice' } },
    { en: 'Okres Svitavy', cs: 'Okres Svitavy', search: { country: 'czechia', q: 'Okres Svitavy' } },
    { en: 'Okres Šumperk', cs: 'Okres Šumperk', search: { country: 'czechia', q: 'Okres Šumperk' } },
    { en: 'Okres Tábor', cs: 'Okres Tábor', search: { country: 'czechia', q: 'Okres Tábor' } },
    { en: 'Okres Tachov', cs: 'Okres Tachov', search: { country: 'czechia', q: 'Okres Tachov' } },
    { en: 'Okres Teplice', cs: 'Okres Teplice', search: { country: 'czechia', q: 'Okres Teplice' } },
    { en: 'Okres Trutnov', cs: 'Okres Trutnov', search: { country: 'czechia', q: 'Okres Trutnov' } },
    { en: 'Okres Třebíč', cs: 'Okres Třebíč', search: { country: 'czechia', q: 'Okres Třebíč' } },
    {
        en: 'Okres Uherské Hradiště',
        cs: 'Okres Uherské Hradiště',
        search: { country: 'czechia', q: 'Okres Uherské Hradiště' },
    },
    {
        en: 'Okres Ústí nad Labem',
        cs: 'Okres Ústí nad Labem',
        search: { country: 'czechia', q: 'Okres Ústí nad Labem' },
    },
    {
        en: 'Okres Ústí nad Orlicí',
        cs: 'Okres Ústí nad Orlicí',
        search: { country: 'czechia', q: 'Okres Ústí nad Orlicí' },
    },
    { en: 'Okres Vsetín', cs: 'Okres Vsetín', search: { country: 'czechia', q: 'Okres Vsetín' } },
    { en: 'Okres Vyškov', cs: 'Okres Vyškov', search: { country: 'czechia', q: 'Okres Vyškov' } },
    { en: 'Okres Zlín', cs: 'Okres Zlín', search: { country: 'czechia', q: 'Okres Zlín' } },
    { en: 'Okres Znojmo', cs: 'Okres Znojmo', search: { country: 'czechia', q: 'Okres Znojmo' } },
    {
        en: 'Okres Žďár nad Sázavou',
        cs: 'Okres Žďár nad Sázavou',
        search: { country: 'czechia', q: 'Okres Žďár nad Sázavou' },
    },
];
