/**
 * 🏭 GENERATED WITH features-generator
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution
 */

export const FEATURES: any = [
    { cs: 'Afghánistán', search: { q: 'Afghánistán' } },
    { cs: 'Albánie', search: { q: 'Albánie' } },
    { cs: 'Alžírsko', search: { q: 'Alžírsko' } },
    { cs: 'Andorra', search: { q: 'Andorra' } },
    { cs: 'Angola', search: { q: 'Angola' } },
    { cs: 'Antigua a Barbuda', search: { q: 'Antigua a Barbuda' } },
    { cs: 'Argentina', search: { q: 'Argentina' } },
    { cs: 'Arménie', search: { q: 'Arménie' } },
    { cs: 'Austrálie', search: { q: 'Austrálie' } },
    { cs: 'Ázerbájdžán', search: { q: 'Ázerbájdžán' } },
    { cs: 'Bahamy', search: { q: 'Bahamy' } },
    { cs: 'Bahrajn', search: { q: 'Bahrajn' } },
    { cs: 'Bangladéš', search: { q: 'Bangladéš' } },
    { cs: 'Barbados', search: { q: 'Barbados' } },
    { cs: 'Belgie', search: { q: 'Belgie' } },
    { cs: 'Belize', search: { q: 'Belize' } },
    { cs: 'Bělorusko', search: { q: 'Bělorusko' } },
    { cs: 'Benin[pozn. 4]', search: { q: 'Benin[pozn. 4]' } },
    { cs: 'Bhútán', search: { q: 'Bhútán' } },
    { cs: 'Bolívie', search: { q: 'Bolívie' } },
    { cs: 'Bosna a Hercegovina', search: { q: 'Bosna a Hercegovina' } },
    { cs: 'Botswana', search: { q: 'Botswana' } },
    { cs: 'Brazílie', search: { q: 'Brazílie' } },
    { cs: 'Brunej', search: { q: 'Brunej' } },
    { cs: 'Bulharsko', search: { q: 'Bulharsko' } },
    { cs: 'Burkina Faso[pozn. 5]', search: { q: 'Burkina Faso[pozn. 5]' } },
    { cs: 'Burundi', search: { q: 'Burundi' } },
    { cs: 'Čad', search: { q: 'Čad' } },
    { cs: 'Černá Hora', search: { q: 'Černá Hora' } },
    { cs: 'Česko[2]', search: { q: 'Česko[2]' } },
    { cs: 'Čína[pozn. 7]', search: { q: 'Čína[pozn. 7]' } },
    { cs: 'Dánsko', search: { q: 'Dánsko' } },
    { cs: 'Dominika', search: { q: 'Dominika' } },
    { cs: 'Dominikánská republika', search: { q: 'Dominikánská republika' } },
    { cs: 'Džibutsko', search: { q: 'Džibutsko' } },
    { cs: 'Egypt', search: { q: 'Egypt' } },
    { cs: 'Ekvádor', search: { q: 'Ekvádor' } },
    { cs: 'Eritrea', search: { q: 'Eritrea' } },
    { cs: 'Estonsko', search: { q: 'Estonsko' } },
    { cs: 'Etiopie', search: { q: 'Etiopie' } },
    { cs: 'Fidži', search: { q: 'Fidži' } },
    { cs: 'Filipíny', search: { q: 'Filipíny' } },
    { cs: 'Finsko', search: { q: 'Finsko' } },
    { cs: 'Francie', search: { q: 'Francie' } },
    { cs: 'Gabon', search: { q: 'Gabon' } },
    { cs: 'Gambie', search: { q: 'Gambie' } },
    { cs: 'Ghana', search: { q: 'Ghana' } },
    { cs: 'Grenada', search: { q: 'Grenada' } },
    { cs: 'Gruzie', search: { q: 'Gruzie' } },
    { cs: 'Guatemala', search: { q: 'Guatemala' } },
    { cs: 'Guinea', search: { q: 'Guinea' } },
    { cs: 'Guinea-Bissau', search: { q: 'Guinea-Bissau' } },
    { cs: 'Guyana', search: { q: 'Guyana' } },
    { cs: 'Haiti', search: { q: 'Haiti' } },
    { cs: 'Honduras', search: { q: 'Honduras' } },
    { cs: 'Chile', search: { q: 'Chile' } },
    { cs: 'Chorvatsko', search: { q: 'Chorvatsko' } },
    { cs: 'Indie', search: { q: 'Indie' } },
    { cs: 'Indonésie', search: { q: 'Indonésie' } },
    { cs: 'Irák', search: { q: 'Irák' } },
    { cs: 'Írán', search: { q: 'Írán' } },
    { cs: 'Irsko', search: { q: 'Irsko' } },
    { cs: 'Island', search: { q: 'Island' } },
    { cs: 'Itálie', search: { q: 'Itálie' } },
    { cs: 'Izrael', search: { q: 'Izrael' } },
    { cs: 'Jamajka', search: { q: 'Jamajka' } },
    { cs: 'Japonsko', search: { q: 'Japonsko' } },
    { cs: 'Jemen', search: { q: 'Jemen' } },
    { cs: 'Jihoafrická republika', search: { q: 'Jihoafrická republika' } },
    { cs: 'Jižní Korea', search: { q: 'Jižní Korea' } },
    { cs: 'Jižní Súdán', search: { q: 'Jižní Súdán' } },
    { cs: 'Jordánsko', search: { q: 'Jordánsko' } },
    { cs: 'Kambodža', search: { q: 'Kambodža' } },
    { cs: 'Kamerun', search: { q: 'Kamerun' } },
    { cs: 'Kanada', search: { q: 'Kanada' } },
    { cs: 'Kapverdy', search: { q: 'Kapverdy' } },
    { cs: 'Katar', search: { q: 'Katar' } },
    { cs: 'Kazachstán', search: { q: 'Kazachstán' } },
    { cs: 'Keňa', search: { q: 'Keňa' } },
    { cs: 'Kiribati', search: { q: 'Kiribati' } },
    { cs: 'Kolumbie', search: { q: 'Kolumbie' } },
    { cs: 'Komory', search: { q: 'Komory' } },
    { cs: 'Konžská republika[pozn. 10]', search: { q: 'Konžská republika[pozn. 10]' } },
    { cs: 'Konžská demokratická republika[pozn. 11]', search: { q: 'Konžská demokratická republika[pozn. 11]' } },
    { cs: 'Kostarika', search: { q: 'Kostarika' } },
    { cs: 'Kuba', search: { q: 'Kuba' } },
    { cs: 'Kuvajt', search: { q: 'Kuvajt' } },
    { cs: 'Kypr', search: { q: 'Kypr' } },
    { cs: 'Kyrgyzstán', search: { q: 'Kyrgyzstán' } },
    { cs: 'Laos', search: { q: 'Laos' } },
    { cs: 'Lesotho', search: { q: 'Lesotho' } },
    { cs: 'Libanon', search: { q: 'Libanon' } },
    { cs: 'Libérie', search: { q: 'Libérie' } },
    { cs: 'Libye', search: { q: 'Libye' } },
    { cs: 'Lichtenštejnsko', search: { q: 'Lichtenštejnsko' } },
    { cs: 'Litva', search: { q: 'Litva' } },
    { cs: 'Lotyšsko', search: { q: 'Lotyšsko' } },
    { cs: 'Lucembursko', search: { q: 'Lucembursko' } },
    { cs: 'Madagaskar', search: { q: 'Madagaskar' } },
    { cs: 'Maďarsko', search: { q: 'Maďarsko' } },
    { cs: 'Malajsie', search: { q: 'Malajsie' } },
    { cs: 'Malawi', search: { q: 'Malawi' } },
    { cs: 'Maledivy', search: { q: 'Maledivy' } },
    { cs: 'Mali', search: { q: 'Mali' } },
    { cs: 'Malta', search: { q: 'Malta' } },
    { cs: 'Maroko', search: { q: 'Maroko' } },
    { cs: 'Marshallovy ostrovy', search: { q: 'Marshallovy ostrovy' } },
    { cs: 'Mauricius', search: { q: 'Mauricius' } },
    { cs: 'Mauritánie', search: { q: 'Mauritánie' } },
    { cs: 'Mexiko', search: { q: 'Mexiko' } },
    { cs: 'Mikronésie', search: { q: 'Mikronésie' } },
    { cs: 'Moldavsko', search: { q: 'Moldavsko' } },
    { cs: 'Monako', search: { q: 'Monako' } },
    { cs: 'Mongolsko', search: { q: 'Mongolsko' } },
    { cs: 'Mosambik', search: { q: 'Mosambik' } },
    { cs: 'Myanmar (Barma)', search: { q: 'Myanmar (Barma)' } },
    { cs: 'Namibie', search: { q: 'Namibie' } },
    { cs: 'Nauru', search: { q: 'Nauru' } },
    { cs: 'Německo', search: { q: 'Německo' } },
    { cs: 'Nepál', search: { q: 'Nepál' } },
    { cs: 'Niger', search: { q: 'Niger' } },
    { cs: 'Nigérie', search: { q: 'Nigérie' } },
    { cs: 'Nikaragua', search: { q: 'Nikaragua' } },
    { cs: 'Nizozemsko', search: { q: 'Nizozemsko' } },
    { cs: 'Norsko', search: { q: 'Norsko' } },
    { cs: 'Nový Zéland', search: { q: 'Nový Zéland' } },
    { cs: 'Omán', search: { q: 'Omán' } },
    { cs: 'Pákistán', search: { q: 'Pákistán' } },
    { cs: 'Palau', search: { q: 'Palau' } },
    { cs: 'Palestina', search: { q: 'Palestina' } },
    { cs: 'Panama', search: { q: 'Panama' } },
    { cs: 'Papua Nová Guinea', search: { q: 'Papua Nová Guinea' } },
    { cs: 'Paraguay', search: { q: 'Paraguay' } },
    { cs: 'Peru', search: { q: 'Peru' } },
    { cs: 'Pobřeží slonoviny', search: { q: 'Pobřeží slonoviny' } },
    { cs: 'Polsko', search: { q: 'Polsko' } },
    { cs: 'Portugalsko', search: { q: 'Portugalsko' } },
    { cs: 'Rakousko', search: { q: 'Rakousko' } },
    { cs: 'Rovníková Guinea', search: { q: 'Rovníková Guinea' } },
    { cs: 'Rumunsko', search: { q: 'Rumunsko' } },
    { cs: 'Rusko', search: { q: 'Rusko' } },
    { cs: 'Rwanda', search: { q: 'Rwanda' } },
    { cs: 'Řecko', search: { q: 'Řecko' } },
    { cs: 'Salvador', search: { q: 'Salvador' } },
    { cs: 'Samoa', search: { q: 'Samoa' } },
    { cs: 'San Marino', search: { q: 'San Marino' } },
    { cs: 'Saúdská Arábie', search: { q: 'Saúdská Arábie' } },
    { cs: 'Senegal', search: { q: 'Senegal' } },
    { cs: 'Severní Korea', search: { q: 'Severní Korea' } },
    { cs: 'Severní Makedonie', search: { q: 'Severní Makedonie' } },
    { cs: 'Seychely', search: { q: 'Seychely' } },
    { cs: 'Sierra Leone', search: { q: 'Sierra Leone' } },
    { cs: 'Singapur', search: { q: 'Singapur' } },
    { cs: 'Slovensko', search: { q: 'Slovensko' } },
    { cs: 'Slovinsko', search: { q: 'Slovinsko' } },
    { cs: 'Somálsko', search: { q: 'Somálsko' } },
    { cs: 'Spojené arabské emiráty[pozn. 14]', search: { q: 'Spojené arabské emiráty[pozn. 14]' } },
    { cs: 'Spojené království[pozn. 15]', search: { q: 'Spojené království[pozn. 15]' } },
    { cs: 'Spojené státy americké[pozn. 16]', search: { q: 'Spojené státy americké[pozn. 16]' } },
    { cs: 'Srbsko', search: { q: 'Srbsko' } },
    { cs: 'Srí Lanka', search: { q: 'Srí Lanka' } },
    { cs: 'Středoafrická republika', search: { q: 'Středoafrická republika' } },
    { cs: 'Súdán', search: { q: 'Súdán' } },
    { cs: 'Surinam', search: { q: 'Surinam' } },
    { cs: 'Svatá Lucie', search: { q: 'Svatá Lucie' } },
    { cs: 'Svatý Kryštof a Nevis', search: { q: 'Svatý Kryštof a Nevis' } },
    { cs: 'Svatý Tomáš a Princův ostrov', search: { q: 'Svatý Tomáš a Princův ostrov' } },
    { cs: 'Svatý Vincenc a Grenadiny', search: { q: 'Svatý Vincenc a Grenadiny' } },
    { cs: 'Svazijsko', search: { q: 'Svazijsko' } },
    { cs: 'Sýrie', search: { q: 'Sýrie' } },
    { cs: 'Šalomounovy ostrovy', search: { q: 'Šalomounovy ostrovy' } },
    { cs: 'Španělsko', search: { q: 'Španělsko' } },
    { cs: 'Švédsko', search: { q: 'Švédsko' } },
    { cs: 'Švýcarsko', search: { q: 'Švýcarsko' } },
    { cs: 'Tádžikistán', search: { q: 'Tádžikistán' } },
    { cs: 'Tanzanie', search: { q: 'Tanzanie' } },
    { cs: 'Thajsko', search: { q: 'Thajsko' } },
    { cs: 'Togo', search: { q: 'Togo' } },
    { cs: 'Tonga', search: { q: 'Tonga' } },
    { cs: 'Trinidad a Tobago', search: { q: 'Trinidad a Tobago' } },
    { cs: 'Tunisko', search: { q: 'Tunisko' } },
    { cs: 'Turecko', search: { q: 'Turecko' } },
    { cs: 'Turkmenistán', search: { q: 'Turkmenistán' } },
    { cs: 'Tuvalu', search: { q: 'Tuvalu' } },
    { cs: 'Uganda', search: { q: 'Uganda' } },
    { cs: 'Ukrajina', search: { q: 'Ukrajina' } },
    { cs: 'Uruguay', search: { q: 'Uruguay' } },
    { cs: 'Uzbekistán', search: { q: 'Uzbekistán' } },
    { cs: 'Vanuatu', search: { q: 'Vanuatu' } },
    { cs: 'Vatikán', search: { q: 'Vatikán' } },
    { cs: 'Venezuela', search: { q: 'Venezuela' } },
    { cs: 'Vietnam', search: { q: 'Vietnam' } },
    { cs: 'Východní Timor', search: { q: 'Východní Timor' } },
    { cs: 'Zambie', search: { q: 'Zambie' } },
    { cs: 'Zimbabwe', search: { q: 'Zimbabwe' } },
    { cs: 'Praha', search: { q: 'Praha' } },
    { cs: 'Brno', search: { q: 'Brno' } },
    { cs: 'Ostrava', search: { q: 'Ostrava' } },
    { cs: 'Plzeň', search: { q: 'Plzeň' } },
    { cs: 'Liberec', search: { q: 'Liberec' } },
    { cs: 'Olomouc', search: { q: 'Olomouc' } },
    { cs: 'České Budějovice', search: { q: 'České Budějovice' } },
    { cs: 'Hradec Králové', search: { q: 'Hradec Králové' } },
    { cs: 'Ústí nad Labem', search: { q: 'Ústí nad Labem' } },
    { cs: 'Pardubice', search: { q: 'Pardubice' } },
    { cs: 'Zlín', search: { q: 'Zlín' } },
    { cs: 'Havířov', search: { q: 'Havířov' } },
    { cs: 'Kladno', search: { q: 'Kladno' } },
    { cs: 'Most', search: { q: 'Most' } },
    { cs: 'Opava', search: { q: 'Opava' } },
    { cs: 'Frýdek-Místek', search: { q: 'Frýdek-Místek' } },
    { cs: 'Jihlava', search: { q: 'Jihlava' } },
    { cs: 'Karviná', search: { q: 'Karviná' } },
    { cs: 'Teplice', search: { q: 'Teplice' } },
    { cs: 'Chomutov', search: { q: 'Chomutov' } },
    { cs: 'Karlovy Vary', search: { q: 'Karlovy Vary' } },
    { cs: 'Děčín', search: { q: 'Děčín' } },
    { cs: 'Jablonec nad Nisou', search: { q: 'Jablonec nad Nisou' } },
    { cs: 'Mladá Boleslav', search: { q: 'Mladá Boleslav' } },
    { cs: 'Prostějov', search: { q: 'Prostějov' } },
    { cs: 'Přerov', search: { q: 'Přerov' } },
    { cs: 'Česká Lípa', search: { q: 'Česká Lípa' } },
    { cs: 'Třebíč', search: { q: 'Třebíč' } },
    { cs: 'Třinec', search: { q: 'Třinec' } },
    { cs: 'Tábor', search: { q: 'Tábor' } },
    { cs: 'Znojmo', search: { q: 'Znojmo' } },
    { cs: 'Kolín', search: { q: 'Kolín' } },
    { cs: 'Příbram', search: { q: 'Příbram' } },
    { cs: 'Cheb', search: { q: 'Cheb' } },
    { cs: 'Písek', search: { q: 'Písek' } },
    { cs: 'Trutnov', search: { q: 'Trutnov' } },
    { cs: 'Kroměříž', search: { q: 'Kroměříž' } },
    { cs: 'Orlová', search: { q: 'Orlová' } },
    { cs: 'Vsetín', search: { q: 'Vsetín' } },
    { cs: 'Šumperk', search: { q: 'Šumperk' } },
    { cs: 'Uherské Hradiště', search: { q: 'Uherské Hradiště' } },
    { cs: 'Břeclav', search: { q: 'Břeclav' } },
    { cs: 'Hodonín', search: { q: 'Hodonín' } },
    { cs: 'Český Těšín', search: { q: 'Český Těšín' } },
    { cs: 'Litoměřice', search: { q: 'Litoměřice' } },
    { cs: 'Litvínov', search: { q: 'Litvínov' } },
    { cs: 'Havlíčkův Brod', search: { q: 'Havlíčkův Brod' } },
    { cs: 'Nový Jičín', search: { q: 'Nový Jičín' } },
    { cs: 'Chrudim', search: { q: 'Chrudim' } },
    { cs: 'Krnov', search: { q: 'Krnov' } },
    { cs: 'Sokolov', search: { q: 'Sokolov' } },
    { cs: 'Strakonice', search: { q: 'Strakonice' } },
    { cs: 'Valašské Meziříčí', search: { q: 'Valašské Meziříčí' } },
    { cs: 'Klatovy', search: { q: 'Klatovy' } },
    { cs: 'Kopřivnice', search: { q: 'Kopřivnice' } },
    { cs: 'Jindřichův Hradec', search: { q: 'Jindřichův Hradec' } },
    { cs: 'Kutná Hora', search: { q: 'Kutná Hora' } },
    { cs: 'Vyškov', search: { q: 'Vyškov' } },
    { cs: 'Žďár nad Sázavou', search: { q: 'Žďár nad Sázavou' } },
    { cs: 'Bohumín', search: { q: 'Bohumín' } },
    { cs: 'Blansko', search: { q: 'Blansko' } },
    { cs: 'Beroun', search: { q: 'Beroun' } },
    { cs: 'Náchod', search: { q: 'Náchod' } },
    { cs: 'Mělník', search: { q: 'Mělník' } },
    { cs: 'Brandýs nad Labem-Stará Boleslav', search: { q: 'Brandýs nad Labem-Stará Boleslav' } },
    { cs: 'Jirkov', search: { q: 'Jirkov' } },
    { cs: 'Žatec', search: { q: 'Žatec' } },
    { cs: 'Kralupy nad Vltavou', search: { q: 'Kralupy nad Vltavou' } },
    { cs: 'Louny', search: { q: 'Louny' } },
    { cs: 'Kadaň', search: { q: 'Kadaň' } },
    { cs: 'Hranice', search: { q: 'Hranice' } },
    { cs: 'Otrokovice', search: { q: 'Otrokovice' } },
    { cs: 'Bílina', search: { q: 'Bílina' } },
    { cs: 'Benešov', search: { q: 'Benešov' } },
    { cs: 'Svitavy', search: { q: 'Svitavy' } },
    { cs: 'Jičín', search: { q: 'Jičín' } },
    { cs: 'Ostrov', search: { q: 'Ostrov' } },
    { cs: 'Uherský Brod', search: { q: 'Uherský Brod' } },
    { cs: 'Rožnov pod Radhoštěm', search: { q: 'Rožnov pod Radhoštěm' } },
    { cs: 'Říčany', search: { q: 'Říčany' } },
    { cs: 'Neratovice', search: { q: 'Neratovice' } },
    { cs: 'Pelhřimov', search: { q: 'Pelhřimov' } },
    { cs: 'Slaný', search: { q: 'Slaný' } },
    { cs: 'Bruntál', search: { q: 'Bruntál' } },
    { cs: 'Rakovník', search: { q: 'Rakovník' } },
    { cs: 'Dvůr Králové nad Labem', search: { q: 'Dvůr Králové nad Labem' } },
    { cs: 'Česká Třebová', search: { q: 'Česká Třebová' } },
    { cs: 'Varnsdorf', search: { q: 'Varnsdorf' } },
    { cs: 'Nymburk', search: { q: 'Nymburk' } },
    { cs: 'Poděbrady', search: { q: 'Poděbrady' } },
    { cs: 'Turnov', search: { q: 'Turnov' } },
    { cs: 'Klášterec nad Ohří', search: { q: 'Klášterec nad Ohří' } },
    { cs: 'Rokycany', search: { q: 'Rokycany' } },
    { cs: 'Ústí nad Orlicí', search: { q: 'Ústí nad Orlicí' } },
    { cs: 'Hlučín', search: { q: 'Hlučín' } },
    { cs: 'Zábřeh', search: { q: 'Zábřeh' } },
    { cs: 'Šternberk', search: { q: 'Šternberk' } },
    { cs: 'Aš', search: { q: 'Aš' } },
    { cs: 'Chodov', search: { q: 'Chodov' } },
    { cs: 'Tachov', search: { q: 'Tachov' } },
    { cs: 'Český Krumlov', search: { q: 'Český Krumlov' } },
    { cs: 'Roudnice nad Labem', search: { q: 'Roudnice nad Labem' } },
    { cs: 'Mariánské Lázně', search: { q: 'Mariánské Lázně' } },
    { cs: 'Krupka', search: { q: 'Krupka' } },
    { cs: 'Jaroměř', search: { q: 'Jaroměř' } },
    { cs: 'Čelákovice', search: { q: 'Čelákovice' } },
    { cs: 'Vrchlabí', search: { q: 'Vrchlabí' } },
    { cs: 'Vysoké Mýto', search: { q: 'Vysoké Mýto' } },
    { cs: 'Milovice', search: { q: 'Milovice' } },
    { cs: 'Boskovice', search: { q: 'Boskovice' } },
    { cs: 'Nový Bor', search: { q: 'Nový Bor' } },
    { cs: 'Holešov', search: { q: 'Holešov' } },
    { cs: 'Vlašim', search: { q: 'Vlašim' } },
    { cs: 'Velké Meziříčí', search: { q: 'Velké Meziříčí' } },
    { cs: 'Uničov', search: { q: 'Uničov' } },
    { cs: 'Kyjov', search: { q: 'Kyjov' } },
    { cs: 'Domažlice', search: { q: 'Domažlice' } },
    { cs: 'Kuřim', search: { q: 'Kuřim' } },
    { cs: 'Jeseník', search: { q: 'Jeseník' } },
    { cs: 'Humpolec', search: { q: 'Humpolec' } },
    { cs: 'Sušice', search: { q: 'Sušice' } },
    { cs: 'Rumburk', search: { q: 'Rumburk' } },
    { cs: 'Rychnov nad Kněžnou', search: { q: 'Rychnov nad Kněžnou' } },
    { cs: 'Veselí nad Moravou', search: { q: 'Veselí nad Moravou' } },
    { cs: 'Frenštát pod Radhoštěm', search: { q: 'Frenštát pod Radhoštěm' } },
    { cs: 'Prachatice', search: { q: 'Prachatice' } },
    { cs: 'Čáslav', search: { q: 'Čáslav' } },
    { cs: 'Litomyšl', search: { q: 'Litomyšl' } },
    { cs: 'Nové Město na Moravě', search: { q: 'Nové Město na Moravě' } },
    { cs: 'Jesenice', search: { q: 'Jesenice' } },
    { cs: 'Králův Dvůr', search: { q: 'Králův Dvůr' } },
    { cs: 'Frýdlant nad Ostravicí', search: { q: 'Frýdlant nad Ostravicí' } },
    { cs: 'Přelouč', search: { q: 'Přelouč' } },
    { cs: 'Ivančice', search: { q: 'Ivančice' } },
    { cs: 'Lysá nad Labem', search: { q: 'Lysá nad Labem' } },
    { cs: 'Lanškroun', search: { q: 'Lanškroun' } },
    { cs: 'Moravská Třebová', search: { q: 'Moravská Třebová' } },
    { cs: 'Litovel', search: { q: 'Litovel' } },
    { cs: 'Hlinsko', search: { q: 'Hlinsko' } },
    { cs: 'Studénka', search: { q: 'Studénka' } },
    { cs: 'Nové Město nad Metují', search: { q: 'Nové Město nad Metují' } },
    { cs: 'Tišnov', search: { q: 'Tišnov' } },
    { cs: 'Mohelnice', search: { q: 'Mohelnice' } },
    { cs: 'Chotěboř', search: { q: 'Chotěboř' } },
    { cs: 'Nová Paka', search: { q: 'Nová Paka' } },
    { cs: 'Hostivice', search: { q: 'Hostivice' } },
    { cs: 'Mnichovo Hradiště', search: { q: 'Mnichovo Hradiště' } },
    { cs: 'Dobříš', search: { q: 'Dobříš' } },
    { cs: 'Polička', search: { q: 'Polička' } },
    { cs: 'Roztoky', search: { q: 'Roztoky' } },
    { cs: 'Lovosice', search: { q: 'Lovosice' } },
    { cs: 'Štětí', search: { q: 'Štětí' } },
    { cs: 'Choceň', search: { q: 'Choceň' } },
    { cs: 'Duchcov', search: { q: 'Duchcov' } },
    { cs: 'Hořice', search: { q: 'Hořice' } },
    { cs: 'Příbor', search: { q: 'Příbor' } },
    { cs: 'Červený Kostelec', search: { q: 'Červený Kostelec' } },
    { cs: 'Semily', search: { q: 'Semily' } },
    { cs: 'Milevsko', search: { q: 'Milevsko' } },
    { cs: 'Třeboň', search: { q: 'Třeboň' } },
    { cs: 'Bystřice pod Hostýnem', search: { q: 'Bystřice pod Hostýnem' } },
    { cs: 'Rýmařov', search: { q: 'Rýmařov' } },
    { cs: 'Bystřice nad Pernštejnem', search: { q: 'Bystřice nad Pernštejnem' } },
    { cs: 'Lipník nad Bečvou', search: { q: 'Lipník nad Bečvou' } },
    { cs: 'Týn nad Vltavou', search: { q: 'Týn nad Vltavou' } },
    { cs: 'Dubí', search: { q: 'Dubí' } },
    { cs: 'Nejdek', search: { q: 'Nejdek' } },
    { cs: 'Hrádek nad Nisou', search: { q: 'Hrádek nad Nisou' } },
    { cs: 'Šlapanice', search: { q: 'Šlapanice' } },
    { cs: 'Stříbro', search: { q: 'Stříbro' } },
    { cs: 'Benátky nad Jizerou', search: { q: 'Benátky nad Jizerou' } },
    { cs: 'Rychvald', search: { q: 'Rychvald' } },
    { cs: 'Mikulov', search: { q: 'Mikulov' } },
    { cs: 'Frýdlant', search: { q: 'Frýdlant' } },
    { cs: 'Vimperk', search: { q: 'Vimperk' } },
    { cs: 'Bílovec', search: { q: 'Bílovec' } },
    { cs: 'Černošice', search: { q: 'Černošice' } },
    { cs: 'Vratimov', search: { q: 'Vratimov' } },
    { cs: 'Petřvald', search: { q: 'Petřvald' } },
    { cs: 'Odry', search: { q: 'Odry' } },
    { cs: 'Broumov', search: { q: 'Broumov' } },
    { cs: 'Moravské Budějovice', search: { q: 'Moravské Budějovice' } },
    { cs: 'Kaplice', search: { q: 'Kaplice' } },
    { cs: 'Dačice', search: { q: 'Dačice' } },
    { cs: 'Sezimovo Ústí', search: { q: 'Sezimovo Ústí' } },
    { cs: 'Napajedla', search: { q: 'Napajedla' } },
    { cs: 'Český Brod', search: { q: 'Český Brod' } },
    { cs: 'Přeštice', search: { q: 'Přeštice' } },
    { cs: 'Slavkov u Brna', search: { q: 'Slavkov u Brna' } },
    { cs: 'Úvaly', search: { q: 'Úvaly' } },
    { cs: 'Vodňany', search: { q: 'Vodňany' } },
    { cs: 'Nýřany', search: { q: 'Nýřany' } },
    { cs: 'Hořovice', search: { q: 'Hořovice' } },
    { cs: 'Soběslav', search: { q: 'Soběslav' } },
    { cs: 'Nový Bydžov', search: { q: 'Nový Bydžov' } },
    { cs: 'Sedlčany', search: { q: 'Sedlčany' } },
    { cs: 'Letovice', search: { q: 'Letovice' } },
    { cs: 'Kraslice', search: { q: 'Kraslice' } },
    { cs: 'Hulín', search: { q: 'Hulín' } },
    { cs: 'Kravaře', search: { q: 'Kravaře' } },
    { cs: 'Dobruška', search: { q: 'Dobruška' } },
    { cs: 'Holice', search: { q: 'Holice' } },
    { cs: 'Staré Město', search: { q: 'Staré Město' } },
    { cs: 'Blatná', search: { q: 'Blatná' } },
    { cs: 'Bučovice', search: { q: 'Bučovice' } },
    { cs: 'Letohrad', search: { q: 'Letohrad' } },
    { cs: 'Světlá nad Sázavou', search: { q: 'Světlá nad Sázavou' } },
    { cs: 'Šenov', search: { q: 'Šenov' } },
    { cs: 'Podbořany', search: { q: 'Podbořany' } },
    { cs: 'Mimoň', search: { q: 'Mimoň' } },
    { cs: 'Rosice', search: { q: 'Rosice' } },
    { cs: 'Veselí nad Lužnicí', search: { q: 'Veselí nad Lužnicí' } },
    { cs: 'Dubňany', search: { q: 'Dubňany' } },
    { cs: 'Slavičín', search: { q: 'Slavičín' } },
    { cs: 'Chrastava', search: { q: 'Chrastava' } },
    { cs: 'Odolena Voda', search: { q: 'Odolena Voda' } },
    { cs: 'Kostelec nad Orlicí', search: { q: 'Kostelec nad Orlicí' } },
    { cs: 'Dobřany', search: { q: 'Dobřany' } },
    { cs: 'Tanvald', search: { q: 'Tanvald' } },
    { cs: 'Mníšek pod Brdy', search: { q: 'Mníšek pod Brdy' } },
    { cs: 'Hronov', search: { q: 'Hronov' } },
    { cs: 'Týniště nad Orlicí', search: { q: 'Týniště nad Orlicí' } },
    { cs: 'Žamberk', search: { q: 'Žamberk' } },
    { cs: 'Železný Brod', search: { q: 'Železný Brod' } },
    { cs: 'Hustopeče', search: { q: 'Hustopeče' } },
    { cs: 'Kojetín', search: { q: 'Kojetín' } },
    { cs: 'Rousínov', search: { q: 'Rousínov' } },
    { cs: 'Šluknov', search: { q: 'Šluknov' } },
    { cs: 'Třebechovice pod Orebem', search: { q: 'Třebechovice pod Orebem' } },
    { cs: 'Týnec nad Sázavou', search: { q: 'Týnec nad Sázavou' } },
    { cs: 'Moravský Krumlov', search: { q: 'Moravský Krumlov' } },
    { cs: 'Třešť', search: { q: 'Třešť' } },
    { cs: 'Úpice', search: { q: 'Úpice' } },
    { cs: 'Vítkov', search: { q: 'Vítkov' } },
    { cs: 'Nové Strašecí', search: { q: 'Nové Strašecí' } },
    { cs: 'Chlumec nad Cidlinou', search: { q: 'Chlumec nad Cidlinou' } },
    { cs: 'Fulnek', search: { q: 'Fulnek' } },
    { cs: 'Brumov-Bylnice', search: { q: 'Brumov-Bylnice' } },
    { cs: 'Zubří', search: { q: 'Zubří' } },
    { cs: 'Lomnice nad Popelkou', search: { q: 'Lomnice nad Popelkou' } },
    { cs: 'Kunovice', search: { q: 'Kunovice' } },
    { cs: 'Hradec nad Moravicí', search: { q: 'Hradec nad Moravicí' } },
    { cs: 'Strážnice', search: { q: 'Strážnice' } },
    { cs: 'Hluboká nad Vltavou', search: { q: 'Hluboká nad Vltavou' } },
    { cs: 'Jablunkov', search: { q: 'Jablunkov' } },
    { cs: 'Jilemnice', search: { q: 'Jilemnice' } },
    { cs: 'Františkovy Lázně', search: { q: 'Františkovy Lázně' } },
    { cs: 'Modřice', search: { q: 'Modřice' } },
    { cs: 'Stochov', search: { q: 'Stochov' } },
    { cs: 'Planá', search: { q: 'Planá' } },
    { cs: 'Horní Slavkov', search: { q: 'Horní Slavkov' } },
    { cs: 'Trhové Sviny', search: { q: 'Trhové Sviny' } },
    { cs: 'Telč', search: { q: 'Telč' } },
    { cs: 'Pohořelice', search: { q: 'Pohořelice' } },
    { cs: 'Velká Bíteš', search: { q: 'Velká Bíteš' } },
    { cs: 'Horažďovice', search: { q: 'Horažďovice' } },
    { cs: 'Polná', search: { q: 'Polná' } },
    { cs: 'Česká Kamenice', search: { q: 'Česká Kamenice' } },
    { cs: 'Doksy', search: { q: 'Doksy' } },
    { cs: 'Kosmonosy', search: { q: 'Kosmonosy' } },
    { cs: 'Starý Plzenec', search: { q: 'Starý Plzenec' } },
    { cs: 'Rudná', search: { q: 'Rudná' } },
    { cs: 'Holýšov', search: { q: 'Holýšov' } },
    { cs: 'Kdyně', search: { q: 'Kdyně' } },
    { cs: 'Bakov nad Jizerou', search: { q: 'Bakov nad Jizerou' } },
    { cs: 'Třemošná', search: { q: 'Třemošná' } },
    { cs: 'Jílové', search: { q: 'Jílové' } },
    { cs: 'Luhačovice', search: { q: 'Luhačovice' } },
    { cs: 'Skuteč', search: { q: 'Skuteč' } },
    { cs: 'Česká Skalice', search: { q: 'Česká Skalice' } },
    { cs: 'Horšovský Týn', search: { q: 'Horšovský Týn' } },
    { cs: 'Bechyně', search: { q: 'Bechyně' } },
    { cs: 'Ledeč nad Sázavou', search: { q: 'Ledeč nad Sázavou' } },
    { cs: 'Vrbno pod Pradědem', search: { q: 'Vrbno pod Pradědem' } },
    { cs: 'Nýrsko', search: { q: 'Nýrsko' } },
    { cs: 'Valašské Klobouky', search: { q: 'Valašské Klobouky' } },
    { cs: 'Jílové u Prahy', search: { q: 'Jílové u Prahy' } },
    { cs: 'Meziboří', search: { q: 'Meziboří' } },
    { cs: 'Chropyně', search: { q: 'Chropyně' } },
    { cs: 'Vizovice', search: { q: 'Vizovice' } },
    { cs: 'Habartov', search: { q: 'Habartov' } },
    { cs: 'Zruč nad Sázavou', search: { q: 'Zruč nad Sázavou' } },
    { cs: 'Náměšť nad Oslavou', search: { q: 'Náměšť nad Oslavou' } },
    { cs: 'Unhošť', search: { q: 'Unhošť' } },
    { cs: 'Pečky', search: { q: 'Pečky' } },
    { cs: 'Heřmanův Městec', search: { q: 'Heřmanův Městec' } },
    { cs: 'Protivín', search: { q: 'Protivín' } },
    { cs: 'Bělá pod Bezdězem', search: { q: 'Bělá pod Bezdězem' } },
    { cs: 'Kynšperk nad Ohří', search: { q: 'Kynšperk nad Ohří' } },
    { cs: 'Oslavany', search: { q: 'Oslavany' } },
    { cs: 'Postoloprty', search: { q: 'Postoloprty' } },
    { cs: 'Osek', search: { q: 'Osek' } },
    { cs: 'Pacov', search: { q: 'Pacov' } },
    { cs: 'Vamberk', search: { q: 'Vamberk' } },
    { cs: 'Vracov', search: { q: 'Vracov' } },
    { cs: 'Votice', search: { q: 'Votice' } },
    { cs: 'Adamov', search: { q: 'Adamov' } },
    { cs: 'Lišov', search: { q: 'Lišov' } },
    { cs: 'Cvikov', search: { q: 'Cvikov' } },
    { cs: 'Klimkovice', search: { q: 'Klimkovice' } },
    { cs: 'Bor', search: { q: 'Bor' } },
    { cs: 'Bystřice', search: { q: 'Bystřice' } },
    { cs: 'Bzenec', search: { q: 'Bzenec' } },
    { cs: 'Bojkovice', search: { q: 'Bojkovice' } },
    { cs: 'Hostinné', search: { q: 'Hostinné' } },
    { cs: 'Hluk', search: { q: 'Hluk' } },
    { cs: 'Chlumec', search: { q: 'Chlumec' } },
    { cs: 'Rožmitál pod Třemšínem', search: { q: 'Rožmitál pod Třemšínem' } },
    { cs: 'Planá nad Lužnicí', search: { q: 'Planá nad Lužnicí' } },
    { cs: 'Kostelec nad Labem', search: { q: 'Kostelec nad Labem' } },
    { cs: 'Uherský Ostroh', search: { q: 'Uherský Ostroh' } },
    { cs: 'Slatiňany', search: { q: 'Slatiňany' } },
    { cs: 'Zdice', search: { q: 'Zdice' } },
    { cs: 'Borovany', search: { q: 'Borovany' } },
    { cs: 'Králíky', search: { q: 'Králíky' } },
    { cs: 'Nová Role', search: { q: 'Nová Role' } },
    { cs: 'Jaroměřice nad Rokytnou', search: { q: 'Jaroměřice nad Rokytnou' } },
    { cs: 'Horní Bříza', search: { q: 'Horní Bříza' } },
    { cs: 'Brušperk', search: { q: 'Brušperk' } },
    { cs: 'Blovice', search: { q: 'Blovice' } },
    { cs: 'Dolní Benešov', search: { q: 'Dolní Benešov' } },
    { cs: 'Sezemice', search: { q: 'Sezemice' } },
    { cs: 'Police nad Metují', search: { q: 'Police nad Metují' } },
    { cs: 'Jemnice', search: { q: 'Jemnice' } },
    { cs: 'Přibyslav', search: { q: 'Přibyslav' } },
    { cs: 'Rajhrad', search: { q: 'Rajhrad' } },
    { cs: 'Mnichovice', search: { q: 'Mnichovice' } },
    { cs: 'Kamenický Šenov', search: { q: 'Kamenický Šenov' } },
    { cs: 'Paskov', search: { q: 'Paskov' } },
    { cs: 'Velké Bílovice', search: { q: 'Velké Bílovice' } },
    { cs: 'Stráž pod Ralskem', search: { q: 'Stráž pod Ralskem' } },
    { cs: 'Velešín', search: { q: 'Velešín' } },
    { cs: 'Větřní', search: { q: 'Větřní' } },
    { cs: 'Židlochovice', search: { q: 'Židlochovice' } },
    { cs: 'Kostelec nad Černými lesy', search: { q: 'Kostelec nad Černými lesy' } },
    { cs: 'Brtnice', search: { q: 'Brtnice' } },
    { cs: 'Smržovka', search: { q: 'Smržovka' } },
    { cs: 'Sázava', search: { q: 'Sázava' } },
    { cs: 'Rájec-Jestřebí', search: { q: 'Rájec-Jestřebí' } },
    { cs: 'Kamenice nad Lipou', search: { q: 'Kamenice nad Lipou' } },
    { cs: 'Zbýšov', search: { q: 'Zbýšov' } },
    { cs: 'Dobřichovice', search: { q: 'Dobřichovice' } },
    { cs: 'Volary', search: { q: 'Volary' } },
    { cs: 'Nepomuk', search: { q: 'Nepomuk' } },
    { cs: 'Fryšták', search: { q: 'Fryšták' } },
    { cs: 'Zlaté Hory', search: { q: 'Zlaté Hory' } },
    { cs: 'Lanžhot', search: { q: 'Lanžhot' } },
    { cs: 'Nové Město pod Smrkem', search: { q: 'Nové Město pod Smrkem' } },
    { cs: 'Lom', search: { q: 'Lom' } },
    { cs: 'Lázně Bělohrad', search: { q: 'Lázně Bělohrad' } },
    { cs: 'Klecany', search: { q: 'Klecany' } },
    { cs: 'Benešov nad Ploučnicí', search: { q: 'Benešov nad Ploučnicí' } },
    { cs: 'Jablonné v Podještědí', search: { q: 'Jablonné v Podještědí' } },
    { cs: 'Toužim', search: { q: 'Toužim' } },
    { cs: 'Buštěhrad', search: { q: 'Buštěhrad' } },
    { cs: 'Velké Opatovice', search: { q: 'Velké Opatovice' } },
    { cs: 'Řevnice', search: { q: 'Řevnice' } },
    { cs: 'Jiříkov', search: { q: 'Jiříkov' } },
    { cs: 'Valtice', search: { q: 'Valtice' } },
    { cs: 'Stod', search: { q: 'Stod' } },
    { cs: 'Suchdol nad Lužnicí', search: { q: 'Suchdol nad Lužnicí' } },
    { cs: 'Lázně Bohdaneč', search: { q: 'Lázně Bohdaneč' } },
    { cs: 'Zliv', search: { q: 'Zliv' } },
    { cs: 'Štěpánov', search: { q: 'Štěpánov' } },
    { cs: 'Březnice', search: { q: 'Březnice' } },
    { cs: 'České Velenice', search: { q: 'České Velenice' } },
    { cs: 'Velká Bystřice', search: { q: 'Velká Bystřice' } },
    { cs: 'Libochovice', search: { q: 'Libochovice' } },
    { cs: 'Město Albrechtice', search: { q: 'Město Albrechtice' } },
    { cs: 'Libčice nad Vltavou', search: { q: 'Libčice nad Vltavou' } },
    { cs: 'Štramberk', search: { q: 'Štramberk' } },
    { cs: 'Kralovice', search: { q: 'Kralovice' } },
    { cs: 'Dobrovice', search: { q: 'Dobrovice' } },
    { cs: 'Veverská Bítýška', search: { q: 'Veverská Bítýška' } },
    { cs: 'Krásná Lípa', search: { q: 'Krásná Lípa' } },
    { cs: 'Újezd u Brna', search: { q: 'Újezd u Brna' } },
    { cs: 'Libušín', search: { q: 'Libušín' } },
    { cs: 'Trmice', search: { q: 'Trmice' } },
    { cs: 'Staňkov', search: { q: 'Staňkov' } },
    { cs: 'Hrušovany nad Jevišovkou', search: { q: 'Hrušovany nad Jevišovkou' } },
    { cs: 'Nová Bystřice', search: { q: 'Nová Bystřice' } },
    { cs: 'Sadská', search: { q: 'Sadská' } },
    { cs: 'Košťany', search: { q: 'Košťany' } },
    { cs: 'Chrast', search: { q: 'Chrast' } },
    { cs: 'Jablonné nad Orlicí', search: { q: 'Jablonné nad Orlicí' } },
    { cs: 'Ždírec nad Doubravou', search: { q: 'Ždírec nad Doubravou' } },
    { cs: 'Žacléř', search: { q: 'Žacléř' } },
    { cs: 'Uhlířské Janovice', search: { q: 'Uhlířské Janovice' } },
    { cs: 'Velké Pavlovice', search: { q: 'Velké Pavlovice' } },
    { cs: 'Desná', search: { q: 'Desná' } },
    { cs: 'Opočno', search: { q: 'Opočno' } },
    { cs: 'Loket', search: { q: 'Loket' } },
    { cs: 'Velvary', search: { q: 'Velvary' } },
    { cs: 'Kaznějov', search: { q: 'Kaznějov' } },
    { cs: 'Břidličná', search: { q: 'Břidličná' } },
    { cs: 'Třemošnice', search: { q: 'Třemošnice' } },
    { cs: 'Hanušovice', search: { q: 'Hanušovice' } },
    { cs: 'Podivín', search: { q: 'Podivín' } },
    { cs: 'Miroslav', search: { q: 'Miroslav' } },
    { cs: 'Volyně', search: { q: 'Volyně' } },
    { cs: 'Hodkovice nad Mohelkou', search: { q: 'Hodkovice nad Mohelkou' } },
    { cs: 'Rtyně v Podkrkonoší', search: { q: 'Rtyně v Podkrkonoší' } },
    { cs: 'Teplá', search: { q: 'Teplá' } },
    { cs: 'Morkovice-Slížany', search: { q: 'Morkovice-Slížany' } },
    { cs: 'Loštice', search: { q: 'Loštice' } },
    { cs: 'Slušovice', search: { q: 'Slušovice' } },
    { cs: 'Úštěk', search: { q: 'Úštěk' } },
    { cs: 'Chvaletice', search: { q: 'Chvaletice' } },
    { cs: 'Ivanovice na Hané', search: { q: 'Ivanovice na Hané' } },
    { cs: 'Smiřice', search: { q: 'Smiřice' } },
    { cs: 'Žirovnice', search: { q: 'Žirovnice' } },
    { cs: 'Moravský Beroun', search: { q: 'Moravský Beroun' } },
    { cs: 'Budišov nad Budišovkou', search: { q: 'Budišov nad Budišovkou' } },
    { cs: 'Rotava', search: { q: 'Rotava' } },
    { cs: 'Kostelec na Hané', search: { q: 'Kostelec na Hané' } },
    { cs: 'Spálené Poříčí', search: { q: 'Spálené Poříčí' } },
    { cs: 'Vejprty', search: { q: 'Vejprty' } },
    { cs: 'Sedlec-Prčice', search: { q: 'Sedlec-Prčice' } },
    { cs: 'Terezín', search: { q: 'Terezín' } },
    { cs: 'Zákupy', search: { q: 'Zákupy' } },
    { cs: 'Raspenava', search: { q: 'Raspenava' } },
    { cs: 'Hrádek', search: { q: 'Hrádek' } },
    { cs: 'Dolní Bousov', search: { q: 'Dolní Bousov' } },
    { cs: 'Český Dub', search: { q: 'Český Dub' } },
    { cs: 'Kunštát', search: { q: 'Kunštát' } },
    { cs: 'Jevíčko', search: { q: 'Jevíčko' } },
    { cs: 'Městec Králové', search: { q: 'Městec Králové' } },
    { cs: 'Rychnov u Jablonce nad Nisou', search: { q: 'Rychnov u Jablonce nad Nisou' } },
    { cs: 'Plasy', search: { q: 'Plasy' } },
    { cs: 'Konice', search: { q: 'Konice' } },
    { cs: 'Hejnice', search: { q: 'Hejnice' } },
    { cs: 'Javorník', search: { q: 'Javorník' } },
    { cs: 'Mladá Vožice', search: { q: 'Mladá Vožice' } },
    { cs: 'Koryčany', search: { q: 'Koryčany' } },
    { cs: 'Golčův Jeníkov', search: { q: 'Golčův Jeníkov' } },
    { cs: 'Kelč', search: { q: 'Kelč' } },
    { cs: 'Velké Hamry', search: { q: 'Velké Hamry' } },
    { cs: 'Neveklov', search: { q: 'Neveklov' } },
    { cs: 'Březová', search: { q: 'Březová' } },
    { cs: 'Vyšší Brod', search: { q: 'Vyšší Brod' } },
    { cs: 'Luže', search: { q: 'Luže' } },
    { cs: 'Nové Sedlo', search: { q: 'Nové Sedlo' } },
    { cs: 'Rokytnice nad Jizerou', search: { q: 'Rokytnice nad Jizerou' } },
    { cs: 'Rudolfov', search: { q: 'Rudolfov' } },
    { cs: 'Netolice', search: { q: 'Netolice' } },
    { cs: 'Počátky', search: { q: 'Počátky' } },
    { cs: 'Chabařovice', search: { q: 'Chabařovice' } },
    { cs: 'Nové Hrady', search: { q: 'Nové Hrady' } },
    { cs: 'Zbiroh', search: { q: 'Zbiroh' } },
    { cs: 'Ždánice', search: { q: 'Ždánice' } },
    { cs: 'Klobouky u Brna', search: { q: 'Klobouky u Brna' } },
    { cs: 'Bohušovice nad Ohří', search: { q: 'Bohušovice nad Ohří' } },
    { cs: 'Chýnov', search: { q: 'Chýnov' } },
    { cs: 'Dolní Kounice', search: { q: 'Dolní Kounice' } },
    { cs: 'Tovačov', search: { q: 'Tovačov' } },
    { cs: 'Karolinka', search: { q: 'Karolinka' } },
    { cs: 'Jáchymov', search: { q: 'Jáchymov' } },
    { cs: 'Sobotka', search: { q: 'Sobotka' } },
    { cs: 'Dašice', search: { q: 'Dašice' } },
    { cs: 'Meziměstí', search: { q: 'Meziměstí' } },
    { cs: 'Kryry', search: { q: 'Kryry' } },
    { cs: 'Nechanice', search: { q: 'Nechanice' } },
    { cs: 'Slavonice', search: { q: 'Slavonice' } },
    { cs: 'Janovice nad Úhlavou', search: { q: 'Janovice nad Úhlavou' } },
    { cs: 'Plumlov', search: { q: 'Plumlov' } },
    { cs: 'Mirošov', search: { q: 'Mirošov' } },
    { cs: 'Nová Včelnice', search: { q: 'Nová Včelnice' } },
    { cs: 'Veltrusy', search: { q: 'Veltrusy' } },
    { cs: 'Žlutice', search: { q: 'Žlutice' } },
    { cs: 'Solnice', search: { q: 'Solnice' } },
    { cs: 'Horní Jiřetín', search: { q: 'Horní Jiřetín' } },
    { cs: 'Horní Benešov', search: { q: 'Horní Benešov' } },
    { cs: 'Kardašova Řečice', search: { q: 'Kardašova Řečice' } },
    { cs: 'Žebrák', search: { q: 'Žebrák' } },
    { cs: 'Město Touškov', search: { q: 'Město Touškov' } },
    { cs: 'Hranice', search: { q: 'Hranice' } },
    { cs: 'Budyně nad Ohří', search: { q: 'Budyně nad Ohří' } },
    { cs: 'Luby', search: { q: 'Luby' } },
    { cs: 'Ralsko', search: { q: 'Ralsko' } },
    { cs: 'Kopidlno', search: { q: 'Kopidlno' } },
    { cs: 'Mikulášovice', search: { q: 'Mikulášovice' } },
    { cs: 'Borohrádek', search: { q: 'Borohrádek' } },
    { cs: 'Týnec nad Labem', search: { q: 'Týnec nad Labem' } },
    { cs: 'Nový Knín', search: { q: 'Nový Knín' } },
    { cs: 'Proseč', search: { q: 'Proseč' } },
    { cs: 'Pyšely', search: { q: 'Pyšely' } },
    { cs: 'Horní Jelení', search: { q: 'Horní Jelení' } },
    { cs: 'Hrochův Týnec', search: { q: 'Hrochův Týnec' } },
    { cs: 'Horní Planá', search: { q: 'Horní Planá' } },
    { cs: 'Hroznětín', search: { q: 'Hroznětín' } },
    { cs: 'Svoboda nad Úpou', search: { q: 'Svoboda nad Úpou' } },
    { cs: 'Jistebnice', search: { q: 'Jistebnice' } },
    { cs: 'Hrob', search: { q: 'Hrob' } },
    { cs: 'Zásmuky', search: { q: 'Zásmuky' } },
    { cs: 'Skalná', search: { q: 'Skalná' } },
    { cs: 'Rokytnice v Orlických horách', search: { q: 'Rokytnice v Orlických horách' } },
    { cs: 'Štíty', search: { q: 'Štíty' } },
    { cs: 'Velký Šenov', search: { q: 'Velký Šenov' } },
    { cs: 'Němčice nad Hanou', search: { q: 'Němčice nad Hanou' } },
    { cs: 'Plesná', search: { q: 'Plesná' } },
    { cs: 'Třebenice', search: { q: 'Třebenice' } },
    { cs: 'Libáň', search: { q: 'Libáň' } },
    { cs: 'Smečno', search: { q: 'Smečno' } },
    { cs: 'Bochov', search: { q: 'Bochov' } },
    { cs: 'Kouřim', search: { q: 'Kouřim' } },
    { cs: 'Lučany nad Nisou', search: { q: 'Lučany nad Nisou' } },
    { cs: 'Žandov', search: { q: 'Žandov' } },
    { cs: 'Horní Cerekev', search: { q: 'Horní Cerekev' } },
    { cs: 'Vroutek', search: { q: 'Vroutek' } },
    { cs: 'Hostomice', search: { q: 'Hostomice' } },
    { cs: 'Radnice', search: { q: 'Radnice' } },
    { cs: 'Lomnice nad Lužnicí', search: { q: 'Lomnice nad Lužnicí' } },
    { cs: 'Hrotovice', search: { q: 'Hrotovice' } },
    { cs: 'Černovice', search: { q: 'Černovice' } },
    { cs: 'Bělá nad Radbuzou', search: { q: 'Bělá nad Radbuzou' } },
    { cs: 'Seč', search: { q: 'Seč' } },
    { cs: 'Hoštka', search: { q: 'Hoštka' } },
    { cs: 'Dolní Poustevna', search: { q: 'Dolní Poustevna' } },
    { cs: 'Vlachovo Březí', search: { q: 'Vlachovo Březí' } },
    { cs: 'Dubá', search: { q: 'Dubá' } },
    { cs: 'Ronov nad Doubravou', search: { q: 'Ronov nad Doubravou' } },
    { cs: 'Jesenice', search: { q: 'Jesenice' } },
    { cs: 'Staré Město', search: { q: 'Staré Město' } },
    { cs: 'Nasavrky', search: { q: 'Nasavrky' } },
    { cs: 'Olešnice', search: { q: 'Olešnice' } },
    { cs: 'Švihov', search: { q: 'Švihov' } },
    { cs: 'Plánice', search: { q: 'Plánice' } },
    { cs: 'Oloví', search: { q: 'Oloví' } },
    { cs: 'Rožďalovice', search: { q: 'Rožďalovice' } },
    { cs: 'Bavorov', search: { q: 'Bavorov' } },
    { cs: 'Kladruby', search: { q: 'Kladruby' } },
    { cs: 'Železná Ruda', search: { q: 'Železná Ruda' } },
    { cs: 'Březová nad Svitavou', search: { q: 'Březová nad Svitavou' } },
    { cs: 'Všeruby', search: { q: 'Všeruby' } },
    { cs: 'Mirovice', search: { q: 'Mirovice' } },
    { cs: 'Teplice nad Metují', search: { q: 'Teplice nad Metují' } },
    { cs: 'Jablonec nad Jizerou', search: { q: 'Jablonec nad Jizerou' } },
    { cs: 'Přimda', search: { q: 'Přimda' } },
    { cs: 'Poběžovice', search: { q: 'Poběžovice' } },
    { cs: 'Mýto', search: { q: 'Mýto' } },
    { cs: 'Bystré', search: { q: 'Bystré' } },
    { cs: 'Kožlany', search: { q: 'Kožlany' } },
    { cs: 'Strmilov', search: { q: 'Strmilov' } },
    { cs: 'Mšeno', search: { q: 'Mšeno' } },
    { cs: 'Husinec', search: { q: 'Husinec' } },
    { cs: 'Lázně Kynžvart', search: { q: 'Lázně Kynžvart' } },
    { cs: 'Strážov', search: { q: 'Strážov' } },
    { cs: 'Trhový Štěpánov', search: { q: 'Trhový Štěpánov' } },
    { cs: 'Kašperské Hory', search: { q: 'Kašperské Hory' } },
    { cs: 'Svratka', search: { q: 'Svratka' } },
    { cs: 'Chřibská', search: { q: 'Chřibská' } },
    { cs: 'Harrachov', search: { q: 'Harrachov' } },
    { cs: 'Habry', search: { q: 'Habry' } },
    { cs: 'Železnice', search: { q: 'Železnice' } },
    { cs: 'Kasejovice', search: { q: 'Kasejovice' } },
    { cs: 'Brandýs nad Orlicí', search: { q: 'Brandýs nad Orlicí' } },
    { cs: 'Rovensko pod Troskami', search: { q: 'Rovensko pod Troskami' } },
    { cs: 'Vysoké nad Jizerou', search: { q: 'Vysoké nad Jizerou' } },
    { cs: 'Vidnava', search: { q: 'Vidnava' } },
    { cs: 'Sedlice', search: { q: 'Sedlice' } },
    { cs: 'Mirotice', search: { q: 'Mirotice' } },
    { cs: 'Pilníkov', search: { q: 'Pilníkov' } },
    { cs: 'Hostouň', search: { q: 'Hostouň' } },
    { cs: 'Žulová', search: { q: 'Žulová' } },
    { cs: 'Černošín', search: { q: 'Černošín' } },
    { cs: 'Potštát', search: { q: 'Potštát' } },
    { cs: 'Osečná', search: { q: 'Osečná' } },
    { cs: 'Verneřice', search: { q: 'Verneřice' } },
    { cs: 'Nalžovské Hory', search: { q: 'Nalžovské Hory' } },
    { cs: 'Úsov', search: { q: 'Úsov' } },
    { cs: 'Jevišovice', search: { q: 'Jevišovice' } },
    { cs: 'Manětín', search: { q: 'Manětín' } },
    { cs: 'Měčín', search: { q: 'Měčín' } },
    { cs: 'Krásná Hora nad Vltavou', search: { q: 'Krásná Hora nad Vltavou' } },
    { cs: 'Špindlerův Mlýn', search: { q: 'Špindlerův Mlýn' } },
    { cs: 'Liběchov', search: { q: 'Liběchov' } },
    { cs: 'Červená Řečice', search: { q: 'Červená Řečice' } },
    { cs: 'Blšany', search: { q: 'Blšany' } },
    { cs: 'Bělčice', search: { q: 'Bělčice' } },
    { cs: 'Bečov nad Teplou', search: { q: 'Bečov nad Teplou' } },
    { cs: 'Hartmanice', search: { q: 'Hartmanice' } },
    { cs: 'Bezdružice', search: { q: 'Bezdružice' } },
    { cs: 'Miletín', search: { q: 'Miletín' } },
    { cs: 'Abertamy', search: { q: 'Abertamy' } },
    { cs: 'Stráž nad Nežárkou', search: { q: 'Stráž nad Nežárkou' } },
    { cs: 'Vysoké Veselí', search: { q: 'Vysoké Veselí' } },
    { cs: 'Deštná', search: { q: 'Deštná' } },
    { cs: 'Krásno', search: { q: 'Krásno' } },
    { cs: 'Janské Lázně', search: { q: 'Janské Lázně' } },
    { cs: 'Stárkov', search: { q: 'Stárkov' } },
    { cs: 'Lipnice nad Sázavou', search: { q: 'Lipnice nad Sázavou' } },
    { cs: 'Pec pod Sněžkou', search: { q: 'Pec pod Sněžkou' } },
    { cs: 'Chyše', search: { q: 'Chyše' } },
    { cs: 'Mašťov', search: { q: 'Mašťov' } },
    { cs: 'Ledvice', search: { q: 'Ledvice' } },
    { cs: 'Rabí', search: { q: 'Rabí' } },
    { cs: 'Úterý', search: { q: 'Úterý' } },
    { cs: 'Hora Svaté Kateřiny', search: { q: 'Hora Svaté Kateřiny' } },
    { cs: 'Výsluní', search: { q: 'Výsluní' } },
    { cs: 'Horní Blatná', search: { q: 'Horní Blatná' } },
    { cs: 'Krásné Údolí', search: { q: 'Krásné Údolí' } },
    { cs: 'Rožmberk nad Vltavou', search: { q: 'Rožmberk nad Vltavou' } },
    { cs: 'Andělská Hora', search: { q: 'Andělská Hora' } },
    { cs: 'Janov', search: { q: 'Janov' } },
    { cs: 'Rejštejn', search: { q: 'Rejštejn' } },
    { cs: 'Boží Dar', search: { q: 'Boží Dar' } },
    { cs: 'Loučná pod Klínovcem', search: { q: 'Loučná pod Klínovcem' } },
    { cs: 'Přebuz', search: { q: 'Přebuz' } },
    { cs: 'Hlavní město Praha', search: { q: 'Hlavní město Praha' } },
    { cs: 'Středočeský kraj', search: { q: 'Středočeský kraj' } },
    { cs: 'Jihočeský kraj', search: { q: 'Jihočeský kraj' } },
    { cs: 'Plzeňský kraj', search: { q: 'Plzeňský kraj' } },
    { cs: 'Karlovarský kraj', search: { q: 'Karlovarský kraj' } },
    { cs: 'Ústecký kraj', search: { q: 'Ústecký kraj' } },
    { cs: 'Liberecký kraj', search: { q: 'Liberecký kraj' } },
    { cs: 'Královéhradecký kraj', search: { q: 'Královéhradecký kraj' } },
    { cs: 'Pardubický kraj', search: { q: 'Pardubický kraj' } },
    { cs: 'Kraj Vysočina', search: { q: 'Kraj Vysočina' } },
    { cs: 'Jihomoravský kraj', search: { q: 'Jihomoravský kraj' } },
    { cs: 'Olomoucký kraj', search: { q: 'Olomoucký kraj' } },
    { cs: 'Moravskoslezský kraj', search: { q: 'Moravskoslezský kraj' } },
    { cs: 'Zlínský kraj', search: { q: 'Zlínský kraj' } },
    { cs: '', search: { q: '' } },
    { cs: 'Okres Benešov', search: { q: 'Okres Benešov' } },
    { cs: 'Okres Beroun', search: { q: 'Okres Beroun' } },
    { cs: 'Okres Blansko', search: { q: 'Okres Blansko' } },
    { cs: 'Okres Brno-město', search: { q: 'Okres Brno-město' } },
    { cs: 'Okres Brno-venkov', search: { q: 'Okres Brno-venkov' } },
    { cs: 'Okres Bruntál', search: { q: 'Okres Bruntál' } },
    { cs: 'Okres Břeclav', search: { q: 'Okres Břeclav' } },
    { cs: 'Okres Česká Lípa', search: { q: 'Okres Česká Lípa' } },
    { cs: 'Okres České Budějovice', search: { q: 'Okres České Budějovice' } },
    { cs: 'Okres Český Krumlov', search: { q: 'Okres Český Krumlov' } },
    { cs: 'Okres Děčín', search: { q: 'Okres Děčín' } },
    { cs: 'Okres Domažlice', search: { q: 'Okres Domažlice' } },
    { cs: 'Okres Frýdek-Místek', search: { q: 'Okres Frýdek-Místek' } },
    { cs: 'Okres Havlíčkův Brod', search: { q: 'Okres Havlíčkův Brod' } },
    { cs: 'Okres Hodonín', search: { q: 'Okres Hodonín' } },
    { cs: 'Okres Hradec Králové', search: { q: 'Okres Hradec Králové' } },
    { cs: 'Okres Cheb', search: { q: 'Okres Cheb' } },
    { cs: 'Okres Chomutov', search: { q: 'Okres Chomutov' } },
    { cs: 'Okres Chrudim', search: { q: 'Okres Chrudim' } },
    { cs: 'Okres Jablonec nad Nisou', search: { q: 'Okres Jablonec nad Nisou' } },
    { cs: 'Okres Jeseník', search: { q: 'Okres Jeseník' } },
    { cs: 'Okres Jičín', search: { q: 'Okres Jičín' } },
    { cs: 'Okres Jihlava', search: { q: 'Okres Jihlava' } },
    { cs: 'Okres Jindřichův Hradec', search: { q: 'Okres Jindřichův Hradec' } },
    { cs: 'Okres Karlovy Vary', search: { q: 'Okres Karlovy Vary' } },
    { cs: 'Okres Karviná', search: { q: 'Okres Karviná' } },
    { cs: 'Okres Kladno', search: { q: 'Okres Kladno' } },
    { cs: 'Okres Klatovy', search: { q: 'Okres Klatovy' } },
    { cs: 'Okres Kolín', search: { q: 'Okres Kolín' } },
    { cs: 'Okres Kroměříž', search: { q: 'Okres Kroměříž' } },
    { cs: 'Okres Kutná Hora', search: { q: 'Okres Kutná Hora' } },
    { cs: 'Okres Liberec', search: { q: 'Okres Liberec' } },
    { cs: 'Okres Litoměřice', search: { q: 'Okres Litoměřice' } },
    { cs: 'Okres Louny', search: { q: 'Okres Louny' } },
    { cs: 'Okres Mělník', search: { q: 'Okres Mělník' } },
    { cs: 'Okres Mladá Boleslav', search: { q: 'Okres Mladá Boleslav' } },
    { cs: 'Okres Most', search: { q: 'Okres Most' } },
    { cs: 'Okres Náchod', search: { q: 'Okres Náchod' } },
    { cs: 'Okres Nový Jičín', search: { q: 'Okres Nový Jičín' } },
    { cs: 'Okres Nymburk', search: { q: 'Okres Nymburk' } },
    { cs: 'Okres Olomouc', search: { q: 'Okres Olomouc' } },
    { cs: 'Okres Opava', search: { q: 'Okres Opava' } },
    { cs: 'Okres Ostrava-město', search: { q: 'Okres Ostrava-město' } },
    { cs: 'Okres Pardubice', search: { q: 'Okres Pardubice' } },
    { cs: 'Okres Pelhřimov', search: { q: 'Okres Pelhřimov' } },
    { cs: 'Okres Písek', search: { q: 'Okres Písek' } },
    { cs: 'Okres Plzeň-jih', search: { q: 'Okres Plzeň-jih' } },
    { cs: 'Okres Plzeň-město', search: { q: 'Okres Plzeň-město' } },
    { cs: 'Okres Plzeň-sever', search: { q: 'Okres Plzeň-sever' } },
    { cs: 'Hlavní město Praha', search: { q: 'Hlavní město Praha' } },
    { cs: 'Okres Praha-východ', search: { q: 'Okres Praha-východ' } },
    { cs: 'Okres Praha-západ', search: { q: 'Okres Praha-západ' } },
    { cs: 'Okres Prachatice', search: { q: 'Okres Prachatice' } },
    { cs: 'Okres Prostějov', search: { q: 'Okres Prostějov' } },
    { cs: 'Okres Přerov', search: { q: 'Okres Přerov' } },
    { cs: 'Okres Příbram', search: { q: 'Okres Příbram' } },
    { cs: 'Okres Rakovník', search: { q: 'Okres Rakovník' } },
    { cs: 'Okres Rokycany', search: { q: 'Okres Rokycany' } },
    { cs: 'Okres Rychnov nad Kněžnou', search: { q: 'Okres Rychnov nad Kněžnou' } },
    { cs: 'Okres Semily', search: { q: 'Okres Semily' } },
    { cs: 'Okres Sokolov', search: { q: 'Okres Sokolov' } },
    { cs: 'Okres Strakonice', search: { q: 'Okres Strakonice' } },
    { cs: 'Okres Svitavy', search: { q: 'Okres Svitavy' } },
    { cs: 'Okres Šumperk', search: { q: 'Okres Šumperk' } },
    { cs: 'Okres Tábor', search: { q: 'Okres Tábor' } },
    { cs: 'Okres Tachov', search: { q: 'Okres Tachov' } },
    { cs: 'Okres Teplice', search: { q: 'Okres Teplice' } },
    { cs: 'Okres Trutnov', search: { q: 'Okres Trutnov' } },
    { cs: 'Okres Třebíč', search: { q: 'Okres Třebíč' } },
    { cs: 'Okres Uherské Hradiště', search: { q: 'Okres Uherské Hradiště' } },
    { cs: 'Okres Ústí nad Labem', search: { q: 'Okres Ústí nad Labem' } },
    { cs: 'Okres Ústí nad Orlicí', search: { q: 'Okres Ústí nad Orlicí' } },
    { cs: 'Okres Vsetín', search: { q: 'Okres Vsetín' } },
    { cs: 'Okres Vyškov', search: { q: 'Okres Vyškov' } },
    { cs: 'Okres Zlín', search: { q: 'Okres Zlín' } },
    { cs: 'Okres Znojmo', search: { q: 'Okres Znojmo' } },
    { cs: 'Okres Žďár nad Sázavou', search: { q: 'Okres Žďár nad Sázavou' } },
];
