/**
* 🏭 GENERATED WITH features-generator
* ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution
*/

export const FEATURES: any = [
  // { cs: 'Praha', search: { country: 'czechia', city: 'Praha' } },
  // { cs: 'Brno', search: { country: 'czechia', city: 'Brno' } },
  // { cs: 'Ostrava', search: { country: 'czechia', city: 'Ostrava' } },
  // { cs: 'Plzeň', search: { country: 'czechia', city: 'Plzeň' } },
  // { cs: 'Liberec', search: { country: 'czechia', city: 'Liberec' } },
  // { cs: 'Olomouc', search: { country: 'czechia', city: 'Olomouc' } },
  // { cs: 'České Budějovice', search: { country: 'czechia', city: 'České Budějovice' } },
  // { cs: 'Hradec Králové', search: { country: 'czechia', city: 'Hradec Králové' } },
  // { cs: 'Ústí nad Labem', search: { country: 'czechia', city: 'Ústí nad Labem' } },
  // { cs: 'Pardubice', search: { country: 'czechia', city: 'Pardubice' } },
  // { cs: 'Zlín', search: { country: 'czechia', city: 'Zlín' } },
  // { cs: 'Havířov', search: { country: 'czechia', city: 'Havířov' } },
  // { cs: 'Kladno', search: { country: 'czechia', city: 'Kladno' } },
  // { cs: 'Most', search: { country: 'czechia', city: 'Most' } },
  // { cs: 'Opava', search: { country: 'czechia', city: 'Opava' } },
  // { cs: 'Frýdek-Místek', search: { country: 'czechia', city: 'Frýdek-Místek' } },
  // { cs: 'Jihlava', search: { country: 'czechia', city: 'Jihlava' } },
  // { cs: 'Karviná', search: { country: 'czechia', city: 'Karviná' } },
  // { cs: 'Teplice', search: { country: 'czechia', city: 'Teplice' } },
  // { cs: 'Chomutov', search: { country: 'czechia', city: 'Chomutov' } },
  // { cs: 'Karlovy Vary', search: { country: 'czechia', city: 'Karlovy Vary' } },
  // { cs: 'Děčín', search: { country: 'czechia', city: 'Děčín' } },
  // { cs: 'Jablonec nad Nisou', search: { country: 'czechia', city: 'Jablonec nad Nisou' } },
  // { cs: 'Mladá Boleslav', search: { country: 'czechia', city: 'Mladá Boleslav' } },
  // { cs: 'Prostějov', search: { country: 'czechia', city: 'Prostějov' } },
  // { cs: 'Přerov', search: { country: 'czechia', city: 'Přerov' } },
  // { cs: 'Česká Lípa', search: { country: 'czechia', city: 'Česká Lípa' } },
  // { cs: 'Třebíč', search: { country: 'czechia', city: 'Třebíč' } },
  // { cs: 'Třinec', search: { country: 'czechia', city: 'Třinec' } },
  // { cs: 'Tábor', search: { country: 'czechia', city: 'Tábor' } },
  // { cs: 'Znojmo', search: { country: 'czechia', city: 'Znojmo' } },
  // { cs: 'Kolín', search: { country: 'czechia', city: 'Kolín' } },
  // { cs: 'Příbram', search: { country: 'czechia', city: 'Příbram' } },
  // { cs: 'Cheb', search: { country: 'czechia', city: 'Cheb' } },
  // { cs: 'Písek', search: { country: 'czechia', city: 'Písek' } },
  // { cs: 'Trutnov', search: { country: 'czechia', city: 'Trutnov' } },
  // { cs: 'Kroměříž', search: { country: 'czechia', city: 'Kroměříž' } },
  // { cs: 'Orlová', search: { country: 'czechia', city: 'Orlová' } },
  // { cs: 'Vsetín', search: { country: 'czechia', city: 'Vsetín' } },
  // { cs: 'Šumperk', search: { country: 'czechia', city: 'Šumperk' } },
  // { cs: 'Uherské Hradiště', search: { country: 'czechia', city: 'Uherské Hradiště' } },
  // { cs: 'Břeclav', search: { country: 'czechia', city: 'Břeclav' } },
  // { cs: 'Hodonín', search: { country: 'czechia', city: 'Hodonín' } },
  // { cs: 'Český Těšín', search: { country: 'czechia', city: 'Český Těšín' } },
  // { cs: 'Litoměřice', search: { country: 'czechia', city: 'Litoměřice' } },
  // { cs: 'Litvínov', search: { country: 'czechia', city: 'Litvínov' } },
  // { cs: 'Havlíčkův Brod', search: { country: 'czechia', city: 'Havlíčkův Brod' } },
  // { cs: 'Nový Jičín', search: { country: 'czechia', city: 'Nový Jičín' } },
  // { cs: 'Chrudim', search: { country: 'czechia', city: 'Chrudim' } },
  // { cs: 'Krnov', search: { country: 'czechia', city: 'Krnov' } },
  // { cs: 'Sokolov', search: { country: 'czechia', city: 'Sokolov' } },
  // { cs: 'Strakonice', search: { country: 'czechia', city: 'Strakonice' } },
  // { cs: 'Valašské Meziříčí', search: { country: 'czechia', city: 'Valašské Meziříčí' } },
  // { cs: 'Klatovy', search: { country: 'czechia', city: 'Klatovy' } },
  // { cs: 'Kopřivnice', search: { country: 'czechia', city: 'Kopřivnice' } },
  // { cs: 'Jindřichův Hradec', search: { country: 'czechia', city: 'Jindřichův Hradec' } },
  // { cs: 'Kutná Hora', search: { country: 'czechia', city: 'Kutná Hora' } },
  // { cs: 'Vyškov', search: { country: 'czechia', city: 'Vyškov' } },
  // { cs: 'Žďár nad Sázavou', search: { country: 'czechia', city: 'Žďár nad Sázavou' } },
  // { cs: 'Bohumín', search: { country: 'czechia', city: 'Bohumín' } },
  // { cs: 'Blansko', search: { country: 'czechia', city: 'Blansko' } },
  // { cs: 'Beroun', search: { country: 'czechia', city: 'Beroun' } },
  // { cs: 'Náchod', search: { country: 'czechia', city: 'Náchod' } },
  // { cs: 'Mělník', search: { country: 'czechia', city: 'Mělník' } },
  // { cs: 'Brandýs nad Labem-Stará Boleslav', search: { country: 'czechia', city: 'Brandýs nad Labem-Stará Boleslav' } },
  // { cs: 'Jirkov', search: { country: 'czechia', city: 'Jirkov' } },
  // { cs: 'Žatec', search: { country: 'czechia', city: 'Žatec' } },
  // { cs: 'Kralupy nad Vltavou', search: { country: 'czechia', city: 'Kralupy nad Vltavou' } },
  // { cs: 'Louny', search: { country: 'czechia', city: 'Louny' } },
  // { cs: 'Kadaň', search: { country: 'czechia', city: 'Kadaň' } },
  // { cs: 'Hranice', search: { country: 'czechia', city: 'Hranice' } },
  // { cs: 'Otrokovice', search: { country: 'czechia', city: 'Otrokovice' } },
  // { cs: 'Bílina', search: { country: 'czechia', city: 'Bílina' } },
  // { cs: 'Benešov', search: { country: 'czechia', city: 'Benešov' } },
  // { cs: 'Svitavy', search: { country: 'czechia', city: 'Svitavy' } },
  // { cs: 'Jičín', search: { country: 'czechia', city: 'Jičín' } },
  // { cs: 'Ostrov', search: { country: 'czechia', city: 'Ostrov' } },
  // { cs: 'Uherský Brod', search: { country: 'czechia', city: 'Uherský Brod' } },
  // { cs: 'Rožnov pod Radhoštěm', search: { country: 'czechia', city: 'Rožnov pod Radhoštěm' } },
  // { cs: 'Říčany', search: { country: 'czechia', city: 'Říčany' } },
  // { cs: 'Neratovice', search: { country: 'czechia', city: 'Neratovice' } },
  // { cs: 'Pelhřimov', search: { country: 'czechia', city: 'Pelhřimov' } },
  // { cs: 'Slaný', search: { country: 'czechia', city: 'Slaný' } },
  // { cs: 'Bruntál', search: { country: 'czechia', city: 'Bruntál' } },
  // { cs: 'Rakovník', search: { country: 'czechia', city: 'Rakovník' } },
  // { cs: 'Dvůr Králové nad Labem', search: { country: 'czechia', city: 'Dvůr Králové nad Labem' } },
  // { cs: 'Česká Třebová', search: { country: 'czechia', city: 'Česká Třebová' } },
  // { cs: 'Varnsdorf', search: { country: 'czechia', city: 'Varnsdorf' } },
  // { cs: 'Nymburk', search: { country: 'czechia', city: 'Nymburk' } },
  // { cs: 'Poděbrady', search: { country: 'czechia', city: 'Poděbrady' } },
  // { cs: 'Turnov', search: { country: 'czechia', city: 'Turnov' } },
  // { cs: 'Klášterec nad Ohří', search: { country: 'czechia', city: 'Klášterec nad Ohří' } },
  // { cs: 'Rokycany', search: { country: 'czechia', city: 'Rokycany' } },
  // { cs: 'Ústí nad Orlicí', search: { country: 'czechia', city: 'Ústí nad Orlicí' } },
  // { cs: 'Hlučín', search: { country: 'czechia', city: 'Hlučín' } },
  // { cs: 'Zábřeh', search: { country: 'czechia', city: 'Zábřeh' } },
  // { cs: 'Šternberk', search: { country: 'czechia', city: 'Šternberk' } },
  // { cs: 'Aš', search: { country: 'czechia', city: 'Aš' } },
  // { cs: 'Chodov', search: { country: 'czechia', city: 'Chodov' } },
  // { cs: 'Tachov', search: { country: 'czechia', city: 'Tachov' } },
  // { cs: 'Český Krumlov', search: { country: 'czechia', city: 'Český Krumlov' } },
  // { cs: 'Roudnice nad Labem', search: { country: 'czechia', city: 'Roudnice nad Labem' } },
  // { cs: 'Mariánské Lázně', search: { country: 'czechia', city: 'Mariánské Lázně' } },
  // { cs: 'Krupka', search: { country: 'czechia', city: 'Krupka' } },
  // { cs: 'Jaroměř', search: { country: 'czechia', city: 'Jaroměř' } },
  // { cs: 'Čelákovice', search: { country: 'czechia', city: 'Čelákovice' } },
  // { cs: 'Vrchlabí', search: { country: 'czechia', city: 'Vrchlabí' } },
  // { cs: 'Vysoké Mýto', search: { country: 'czechia', city: 'Vysoké Mýto' } },
  // { cs: 'Milovice', search: { country: 'czechia', city: 'Milovice' } },
  // { cs: 'Boskovice', search: { country: 'czechia', city: 'Boskovice' } },
  // { cs: 'Nový Bor', search: { country: 'czechia', city: 'Nový Bor' } },
  // { cs: 'Holešov', search: { country: 'czechia', city: 'Holešov' } },
  // { cs: 'Vlašim', search: { country: 'czechia', city: 'Vlašim' } },
  // { cs: 'Velké Meziříčí', search: { country: 'czechia', city: 'Velké Meziříčí' } },
  // { cs: 'Uničov', search: { country: 'czechia', city: 'Uničov' } },
  // { cs: 'Kyjov', search: { country: 'czechia', city: 'Kyjov' } },
  // { cs: 'Domažlice', search: { country: 'czechia', city: 'Domažlice' } },
  // { cs: 'Kuřim', search: { country: 'czechia', city: 'Kuřim' } },
  // { cs: 'Jeseník', search: { country: 'czechia', city: 'Jeseník' } },
  // { cs: 'Humpolec', search: { country: 'czechia', city: 'Humpolec' } },
  // { cs: 'Sušice', search: { country: 'czechia', city: 'Sušice' } },
  // { cs: 'Rumburk', search: { country: 'czechia', city: 'Rumburk' } },
  // { cs: 'Rychnov nad Kněžnou', search: { country: 'czechia', city: 'Rychnov nad Kněžnou' } },
  // { cs: 'Veselí nad Moravou', search: { country: 'czechia', city: 'Veselí nad Moravou' } },
  // { cs: 'Frenštát pod Radhoštěm', search: { country: 'czechia', city: 'Frenštát pod Radhoštěm' } },
  // { cs: 'Prachatice', search: { country: 'czechia', city: 'Prachatice' } },
  // { cs: 'Čáslav', search: { country: 'czechia', city: 'Čáslav' } },
  // { cs: 'Litomyšl', search: { country: 'czechia', city: 'Litomyšl' } },
  // { cs: 'Nové Město na Moravě', search: { country: 'czechia', city: 'Nové Město na Moravě' } },
  // { cs: 'Jesenice', search: { country: 'czechia', city: 'Jesenice' } },
  // { cs: 'Králův Dvůr', search: { country: 'czechia', city: 'Králův Dvůr' } },
  // { cs: 'Frýdlant nad Ostravicí', search: { country: 'czechia', city: 'Frýdlant nad Ostravicí' } },
  // { cs: 'Přelouč', search: { country: 'czechia', city: 'Přelouč' } },
  // { cs: 'Ivančice', search: { country: 'czechia', city: 'Ivančice' } },
  // { cs: 'Lysá nad Labem', search: { country: 'czechia', city: 'Lysá nad Labem' } },
  // { cs: 'Lanškroun', search: { country: 'czechia', city: 'Lanškroun' } },
  // { cs: 'Moravská Třebová', search: { country: 'czechia', city: 'Moravská Třebová' } },
  // { cs: 'Litovel', search: { country: 'czechia', city: 'Litovel' } },
  // { cs: 'Hlinsko', search: { country: 'czechia', city: 'Hlinsko' } },
  // { cs: 'Studénka', search: { country: 'czechia', city: 'Studénka' } },
  // { cs: 'Nové Město nad Metují', search: { country: 'czechia', city: 'Nové Město nad Metují' } },
  // { cs: 'Tišnov', search: { country: 'czechia', city: 'Tišnov' } },
  // { cs: 'Mohelnice', search: { country: 'czechia', city: 'Mohelnice' } },
  // { cs: 'Chotěboř', search: { country: 'czechia', city: 'Chotěboř' } },
  // { cs: 'Nová Paka', search: { country: 'czechia', city: 'Nová Paka' } },
  // { cs: 'Hostivice', search: { country: 'czechia', city: 'Hostivice' } },
  // { cs: 'Mnichovo Hradiště', search: { country: 'czechia', city: 'Mnichovo Hradiště' } },
  // { cs: 'Dobříš', search: { country: 'czechia', city: 'Dobříš' } },
  // { cs: 'Polička', search: { country: 'czechia', city: 'Polička' } },
  // { cs: 'Roztoky', search: { country: 'czechia', city: 'Roztoky' } },
  // { cs: 'Lovosice', search: { country: 'czechia', city: 'Lovosice' } },
  // { cs: 'Štětí', search: { country: 'czechia', city: 'Štětí' } },
  // { cs: 'Choceň', search: { country: 'czechia', city: 'Choceň' } },
  // { cs: 'Duchcov', search: { country: 'czechia', city: 'Duchcov' } },
  // { cs: 'Hořice', search: { country: 'czechia', city: 'Hořice' } },
  // { cs: 'Příbor', search: { country: 'czechia', city: 'Příbor' } },
  // { cs: 'Červený Kostelec', search: { country: 'czechia', city: 'Červený Kostelec' } },
  // { cs: 'Semily', search: { country: 'czechia', city: 'Semily' } },
  // { cs: 'Milevsko', search: { country: 'czechia', city: 'Milevsko' } },
  // { cs: 'Třeboň', search: { country: 'czechia', city: 'Třeboň' } },
  // { cs: 'Bystřice pod Hostýnem', search: { country: 'czechia', city: 'Bystřice pod Hostýnem' } },
  // { cs: 'Rýmařov', search: { country: 'czechia', city: 'Rýmařov' } },
  // { cs: 'Bystřice nad Pernštejnem', search: { country: 'czechia', city: 'Bystřice nad Pernštejnem' } },
  // { cs: 'Lipník nad Bečvou', search: { country: 'czechia', city: 'Lipník nad Bečvou' } },
  // { cs: 'Týn nad Vltavou', search: { country: 'czechia', city: 'Týn nad Vltavou' } },
  // { cs: 'Dubí', search: { country: 'czechia', city: 'Dubí' } },
  // { cs: 'Nejdek', search: { country: 'czechia', city: 'Nejdek' } },
  // { cs: 'Hrádek nad Nisou', search: { country: 'czechia', city: 'Hrádek nad Nisou' } },
  // { cs: 'Šlapanice', search: { country: 'czechia', city: 'Šlapanice' } },
  // { cs: 'Stříbro', search: { country: 'czechia', city: 'Stříbro' } },
  // { cs: 'Benátky nad Jizerou', search: { country: 'czechia', city: 'Benátky nad Jizerou' } },
  // { cs: 'Rychvald', search: { country: 'czechia', city: 'Rychvald' } },
  // { cs: 'Mikulov', search: { country: 'czechia', city: 'Mikulov' } },
  // { cs: 'Frýdlant', search: { country: 'czechia', city: 'Frýdlant' } },
  // { cs: 'Vimperk', search: { country: 'czechia', city: 'Vimperk' } },
  // { cs: 'Bílovec', search: { country: 'czechia', city: 'Bílovec' } },
  // { cs: 'Černošice', search: { country: 'czechia', city: 'Černošice' } },
  // { cs: 'Vratimov', search: { country: 'czechia', city: 'Vratimov' } },
  // { cs: 'Petřvald', search: { country: 'czechia', city: 'Petřvald' } },
  // { cs: 'Odry', search: { country: 'czechia', city: 'Odry' } },
  // { cs: 'Broumov', search: { country: 'czechia', city: 'Broumov' } },
  // { cs: 'Moravské Budějovice', search: { country: 'czechia', city: 'Moravské Budějovice' } },
  // { cs: 'Kaplice', search: { country: 'czechia', city: 'Kaplice' } },
  // { cs: 'Dačice', search: { country: 'czechia', city: 'Dačice' } },
  // { cs: 'Sezimovo Ústí', search: { country: 'czechia', city: 'Sezimovo Ústí' } },
  // { cs: 'Napajedla', search: { country: 'czechia', city: 'Napajedla' } },
  // { cs: 'Český Brod', search: { country: 'czechia', city: 'Český Brod' } },
  // { cs: 'Přeštice', search: { country: 'czechia', city: 'Přeštice' } },
  // { cs: 'Slavkov u Brna', search: { country: 'czechia', city: 'Slavkov u Brna' } },
  // { cs: 'Úvaly', search: { country: 'czechia', city: 'Úvaly' } },
  // { cs: 'Vodňany', search: { country: 'czechia', city: 'Vodňany' } },
  // { cs: 'Nýřany', search: { country: 'czechia', city: 'Nýřany' } },
  // { cs: 'Hořovice', search: { country: 'czechia', city: 'Hořovice' } },
  // { cs: 'Soběslav', search: { country: 'czechia', city: 'Soběslav' } },
  // { cs: 'Nový Bydžov', search: { country: 'czechia', city: 'Nový Bydžov' } },
  // { cs: 'Sedlčany', search: { country: 'czechia', city: 'Sedlčany' } },
  // { cs: 'Letovice', search: { country: 'czechia', city: 'Letovice' } },
  // { cs: 'Kraslice', search: { country: 'czechia', city: 'Kraslice' } },
  // { cs: 'Hulín', search: { country: 'czechia', city: 'Hulín' } },
  // { cs: 'Kravaře', search: { country: 'czechia', city: 'Kravaře' } },
  // { cs: 'Dobruška', search: { country: 'czechia', city: 'Dobruška' } },
  // { cs: 'Holice', search: { country: 'czechia', city: 'Holice' } },
  // { cs: 'Staré Město', search: { country: 'czechia', city: 'Staré Město' } },
  // { cs: 'Blatná', search: { country: 'czechia', city: 'Blatná' } },
  // { cs: 'Bučovice', search: { country: 'czechia', city: 'Bučovice' } },
  // { cs: 'Letohrad', search: { country: 'czechia', city: 'Letohrad' } },
  // { cs: 'Světlá nad Sázavou', search: { country: 'czechia', city: 'Světlá nad Sázavou' } },
  // { cs: 'Šenov', search: { country: 'czechia', city: 'Šenov' } },
  // { cs: 'Podbořany', search: { country: 'czechia', city: 'Podbořany' } },
  // { cs: 'Mimoň', search: { country: 'czechia', city: 'Mimoň' } },
  // { cs: 'Rosice', search: { country: 'czechia', city: 'Rosice' } },
  // { cs: 'Veselí nad Lužnicí', search: { country: 'czechia', city: 'Veselí nad Lužnicí' } },
  // { cs: 'Dubňany', search: { country: 'czechia', city: 'Dubňany' } },
  // { cs: 'Slavičín', search: { country: 'czechia', city: 'Slavičín' } },
  // { cs: 'Chrastava', search: { country: 'czechia', city: 'Chrastava' } },
  // { cs: 'Odolena Voda', search: { country: 'czechia', city: 'Odolena Voda' } },
  // { cs: 'Kostelec nad Orlicí', search: { country: 'czechia', city: 'Kostelec nad Orlicí' } },
  // { cs: 'Dobřany', search: { country: 'czechia', city: 'Dobřany' } },
  // { cs: 'Tanvald', search: { country: 'czechia', city: 'Tanvald' } },
  // { cs: 'Mníšek pod Brdy', search: { country: 'czechia', city: 'Mníšek pod Brdy' } },
  // { cs: 'Hronov', search: { country: 'czechia', city: 'Hronov' } },
  // { cs: 'Týniště nad Orlicí', search: { country: 'czechia', city: 'Týniště nad Orlicí' } },
  // { cs: 'Žamberk', search: { country: 'czechia', city: 'Žamberk' } },
  // { cs: 'Železný Brod', search: { country: 'czechia', city: 'Železný Brod' } },
  // { cs: 'Hustopeče', search: { country: 'czechia', city: 'Hustopeče' } },
  // { cs: 'Kojetín', search: { country: 'czechia', city: 'Kojetín' } },
  // { cs: 'Rousínov', search: { country: 'czechia', city: 'Rousínov' } },
  // { cs: 'Šluknov', search: { country: 'czechia', city: 'Šluknov' } },
  // { cs: 'Třebechovice pod Orebem', search: { country: 'czechia', city: 'Třebechovice pod Orebem' } },
  // { cs: 'Týnec nad Sázavou', search: { country: 'czechia', city: 'Týnec nad Sázavou' } },
  // { cs: 'Moravský Krumlov', search: { country: 'czechia', city: 'Moravský Krumlov' } },
  // { cs: 'Třešť', search: { country: 'czechia', city: 'Třešť' } },
  // { cs: 'Úpice', search: { country: 'czechia', city: 'Úpice' } },
  // { cs: 'Vítkov', search: { country: 'czechia', city: 'Vítkov' } },
  // { cs: 'Nové Strašecí', search: { country: 'czechia', city: 'Nové Strašecí' } },
  // { cs: 'Chlumec nad Cidlinou', search: { country: 'czechia', city: 'Chlumec nad Cidlinou' } },
  // { cs: 'Fulnek', search: { country: 'czechia', city: 'Fulnek' } },
  // { cs: 'Brumov-Bylnice', search: { country: 'czechia', city: 'Brumov-Bylnice' } },
  // { cs: 'Zubří', search: { country: 'czechia', city: 'Zubří' } },
  // { cs: 'Lomnice nad Popelkou', search: { country: 'czechia', city: 'Lomnice nad Popelkou' } },
  // { cs: 'Kunovice', search: { country: 'czechia', city: 'Kunovice' } },
  // { cs: 'Hradec nad Moravicí', search: { country: 'czechia', city: 'Hradec nad Moravicí' } },
  // { cs: 'Strážnice', search: { country: 'czechia', city: 'Strážnice' } },
  // { cs: 'Hluboká nad Vltavou', search: { country: 'czechia', city: 'Hluboká nad Vltavou' } },
  // { cs: 'Jablunkov', search: { country: 'czechia', city: 'Jablunkov' } },
  // { cs: 'Jilemnice', search: { country: 'czechia', city: 'Jilemnice' } },
  // { cs: 'Františkovy Lázně', search: { country: 'czechia', city: 'Františkovy Lázně' } },
  // { cs: 'Modřice', search: { country: 'czechia', city: 'Modřice' } },
  // { cs: 'Stochov', search: { country: 'czechia', city: 'Stochov' } },
  // { cs: 'Planá', search: { country: 'czechia', city: 'Planá' } },
  // { cs: 'Horní Slavkov', search: { country: 'czechia', city: 'Horní Slavkov' } },
  // { cs: 'Trhové Sviny', search: { country: 'czechia', city: 'Trhové Sviny' } },
  // { cs: 'Telč', search: { country: 'czechia', city: 'Telč' } },
  // { cs: 'Pohořelice', search: { country: 'czechia', city: 'Pohořelice' } },
  // { cs: 'Velká Bíteš', search: { country: 'czechia', city: 'Velká Bíteš' } },
  // { cs: 'Horažďovice', search: { country: 'czechia', city: 'Horažďovice' } },
  // { cs: 'Polná', search: { country: 'czechia', city: 'Polná' } },
  // { cs: 'Česká Kamenice', search: { country: 'czechia', city: 'Česká Kamenice' } },
  // { cs: 'Doksy', search: { country: 'czechia', city: 'Doksy' } },
  // { cs: 'Kosmonosy', search: { country: 'czechia', city: 'Kosmonosy' } },
  // { cs: 'Starý Plzenec', search: { country: 'czechia', city: 'Starý Plzenec' } },
  // { cs: 'Rudná', search: { country: 'czechia', city: 'Rudná' } },
  // { cs: 'Holýšov', search: { country: 'czechia', city: 'Holýšov' } },
  // { cs: 'Kdyně', search: { country: 'czechia', city: 'Kdyně' } },
  // { cs: 'Bakov nad Jizerou', search: { country: 'czechia', city: 'Bakov nad Jizerou' } },
  // { cs: 'Třemošná', search: { country: 'czechia', city: 'Třemošná' } },
  // { cs: 'Jílové', search: { country: 'czechia', city: 'Jílové' } },
  // { cs: 'Luhačovice', search: { country: 'czechia', city: 'Luhačovice' } },
  // { cs: 'Skuteč', search: { country: 'czechia', city: 'Skuteč' } },
  // { cs: 'Česká Skalice', search: { country: 'czechia', city: 'Česká Skalice' } },
  // { cs: 'Horšovský Týn', search: { country: 'czechia', city: 'Horšovský Týn' } },
  // { cs: 'Bechyně', search: { country: 'czechia', city: 'Bechyně' } },
  // { cs: 'Ledeč nad Sázavou', search: { country: 'czechia', city: 'Ledeč nad Sázavou' } },
  // { cs: 'Vrbno pod Pradědem', search: { country: 'czechia', city: 'Vrbno pod Pradědem' } },
  // { cs: 'Nýrsko', search: { country: 'czechia', city: 'Nýrsko' } },
  // { cs: 'Valašské Klobouky', search: { country: 'czechia', city: 'Valašské Klobouky' } },
  // { cs: 'Jílové u Prahy', search: { country: 'czechia', city: 'Jílové u Prahy' } },
  // { cs: 'Meziboří', search: { country: 'czechia', city: 'Meziboří' } },
  // { cs: 'Chropyně', search: { country: 'czechia', city: 'Chropyně' } },
  // { cs: 'Vizovice', search: { country: 'czechia', city: 'Vizovice' } },
  // { cs: 'Habartov', search: { country: 'czechia', city: 'Habartov' } },
  // { cs: 'Zruč nad Sázavou', search: { country: 'czechia', city: 'Zruč nad Sázavou' } },
  // { cs: 'Náměšť nad Oslavou', search: { country: 'czechia', city: 'Náměšť nad Oslavou' } },
  // { cs: 'Unhošť', search: { country: 'czechia', city: 'Unhošť' } },
  // { cs: 'Pečky', search: { country: 'czechia', city: 'Pečky' } },
  // { cs: 'Heřmanův Městec', search: { country: 'czechia', city: 'Heřmanův Městec' } },
  // { cs: 'Protivín', search: { country: 'czechia', city: 'Protivín' } },
  // { cs: 'Bělá pod Bezdězem', search: { country: 'czechia', city: 'Bělá pod Bezdězem' } },
  // { cs: 'Kynšperk nad Ohří', search: { country: 'czechia', city: 'Kynšperk nad Ohří' } },
  // { cs: 'Oslavany', search: { country: 'czechia', city: 'Oslavany' } },
  // { cs: 'Postoloprty', search: { country: 'czechia', city: 'Postoloprty' } },
  // { cs: 'Osek', search: { country: 'czechia', city: 'Osek' } },
  // { cs: 'Pacov', search: { country: 'czechia', city: 'Pacov' } },
  // { cs: 'Vamberk', search: { country: 'czechia', city: 'Vamberk' } },
  // { cs: 'Vracov', search: { country: 'czechia', city: 'Vracov' } },
  // { cs: 'Votice', search: { country: 'czechia', city: 'Votice' } },
  // { cs: 'Adamov', search: { country: 'czechia', city: 'Adamov' } },
  // { cs: 'Lišov', search: { country: 'czechia', city: 'Lišov' } },
  // { cs: 'Cvikov', search: { country: 'czechia', city: 'Cvikov' } },
  // { cs: 'Klimkovice', search: { country: 'czechia', city: 'Klimkovice' } },
  // { cs: 'Bor', search: { country: 'czechia', city: 'Bor' } },
  // { cs: 'Bystřice', search: { country: 'czechia', city: 'Bystřice' } },
  // { cs: 'Bzenec', search: { country: 'czechia', city: 'Bzenec' } },
  // { cs: 'Bojkovice', search: { country: 'czechia', city: 'Bojkovice' } },
  // { cs: 'Hostinné', search: { country: 'czechia', city: 'Hostinné' } },
  // { cs: 'Hluk', search: { country: 'czechia', city: 'Hluk' } },
  // { cs: 'Chlumec', search: { country: 'czechia', city: 'Chlumec' } },
  // { cs: 'Rožmitál pod Třemšínem', search: { country: 'czechia', city: 'Rožmitál pod Třemšínem' } },
  // { cs: 'Planá nad Lužnicí', search: { country: 'czechia', city: 'Planá nad Lužnicí' } },
  // { cs: 'Kostelec nad Labem', search: { country: 'czechia', city: 'Kostelec nad Labem' } },
  // { cs: 'Uherský Ostroh', search: { country: 'czechia', city: 'Uherský Ostroh' } },
  // { cs: 'Slatiňany', search: { country: 'czechia', city: 'Slatiňany' } },
  // { cs: 'Zdice', search: { country: 'czechia', city: 'Zdice' } },
  // { cs: 'Borovany', search: { country: 'czechia', city: 'Borovany' } },
  // { cs: 'Králíky', search: { country: 'czechia', city: 'Králíky' } },
  // { cs: 'Nová Role', search: { country: 'czechia', city: 'Nová Role' } },
  // { cs: 'Jaroměřice nad Rokytnou', search: { country: 'czechia', city: 'Jaroměřice nad Rokytnou' } },
  // { cs: 'Horní Bříza', search: { country: 'czechia', city: 'Horní Bříza' } },
  // { cs: 'Brušperk', search: { country: 'czechia', city: 'Brušperk' } },
  // { cs: 'Blovice', search: { country: 'czechia', city: 'Blovice' } },
  // { cs: 'Dolní Benešov', search: { country: 'czechia', city: 'Dolní Benešov' } },
  // { cs: 'Sezemice', search: { country: 'czechia', city: 'Sezemice' } },
  // { cs: 'Police nad Metují', search: { country: 'czechia', city: 'Police nad Metují' } },
  // { cs: 'Jemnice', search: { country: 'czechia', city: 'Jemnice' } },
  // { cs: 'Přibyslav', search: { country: 'czechia', city: 'Přibyslav' } },
  // { cs: 'Rajhrad', search: { country: 'czechia', city: 'Rajhrad' } },
  // { cs: 'Mnichovice', search: { country: 'czechia', city: 'Mnichovice' } },
  // { cs: 'Kamenický Šenov', search: { country: 'czechia', city: 'Kamenický Šenov' } },
  // { cs: 'Paskov', search: { country: 'czechia', city: 'Paskov' } },
  // { cs: 'Velké Bílovice', search: { country: 'czechia', city: 'Velké Bílovice' } },
  // { cs: 'Stráž pod Ralskem', search: { country: 'czechia', city: 'Stráž pod Ralskem' } },
  // { cs: 'Velešín', search: { country: 'czechia', city: 'Velešín' } },
  // { cs: 'Větřní', search: { country: 'czechia', city: 'Větřní' } },
  // { cs: 'Židlochovice', search: { country: 'czechia', city: 'Židlochovice' } },
  // { cs: 'Kostelec nad Černými lesy', search: { country: 'czechia', city: 'Kostelec nad Černými lesy' } },
  // { cs: 'Brtnice', search: { country: 'czechia', city: 'Brtnice' } },
  // { cs: 'Smržovka', search: { country: 'czechia', city: 'Smržovka' } },
  // { cs: 'Sázava', search: { country: 'czechia', city: 'Sázava' } },
  // { cs: 'Rájec-Jestřebí', search: { country: 'czechia', city: 'Rájec-Jestřebí' } },
  // { cs: 'Kamenice nad Lipou', search: { country: 'czechia', city: 'Kamenice nad Lipou' } },
  // { cs: 'Zbýšov', search: { country: 'czechia', city: 'Zbýšov' } },
  // { cs: 'Dobřichovice', search: { country: 'czechia', city: 'Dobřichovice' } },
  // { cs: 'Volary', search: { country: 'czechia', city: 'Volary' } },
  // { cs: 'Nepomuk', search: { country: 'czechia', city: 'Nepomuk' } },
  // { cs: 'Fryšták', search: { country: 'czechia', city: 'Fryšták' } },
  // { cs: 'Zlaté Hory', search: { country: 'czechia', city: 'Zlaté Hory' } },
  // { cs: 'Lanžhot', search: { country: 'czechia', city: 'Lanžhot' } },
  // { cs: 'Nové Město pod Smrkem', search: { country: 'czechia', city: 'Nové Město pod Smrkem' } },
  // { cs: 'Lom', search: { country: 'czechia', city: 'Lom' } },
  // { cs: 'Lázně Bělohrad', search: { country: 'czechia', city: 'Lázně Bělohrad' } },
  // { cs: 'Klecany', search: { country: 'czechia', city: 'Klecany' } },
  // { cs: 'Benešov nad Ploučnicí', search: { country: 'czechia', city: 'Benešov nad Ploučnicí' } },
  // { cs: 'Jablonné v Podještědí', search: { country: 'czechia', city: 'Jablonné v Podještědí' } },
  // { cs: 'Toužim', search: { country: 'czechia', city: 'Toužim' } },
  // { cs: 'Buštěhrad', search: { country: 'czechia', city: 'Buštěhrad' } },
  // { cs: 'Velké Opatovice', search: { country: 'czechia', city: 'Velké Opatovice' } },
  // { cs: 'Řevnice', search: { country: 'czechia', city: 'Řevnice' } },
  // { cs: 'Jiříkov', search: { country: 'czechia', city: 'Jiříkov' } },
  // { cs: 'Valtice', search: { country: 'czechia', city: 'Valtice' } },
  // { cs: 'Stod', search: { country: 'czechia', city: 'Stod' } },
  // { cs: 'Suchdol nad Lužnicí', search: { country: 'czechia', city: 'Suchdol nad Lužnicí' } },
  // { cs: 'Lázně Bohdaneč', search: { country: 'czechia', city: 'Lázně Bohdaneč' } },
  // { cs: 'Zliv', search: { country: 'czechia', city: 'Zliv' } },
  // { cs: 'Štěpánov', search: { country: 'czechia', city: 'Štěpánov' } },
  // { cs: 'Březnice', search: { country: 'czechia', city: 'Březnice' } },
  // { cs: 'České Velenice', search: { country: 'czechia', city: 'České Velenice' } },
  // { cs: 'Velká Bystřice', search: { country: 'czechia', city: 'Velká Bystřice' } },
  // { cs: 'Libochovice', search: { country: 'czechia', city: 'Libochovice' } },
  // { cs: 'Město Albrechtice', search: { country: 'czechia', city: 'Město Albrechtice' } },
  // { cs: 'Libčice nad Vltavou', search: { country: 'czechia', city: 'Libčice nad Vltavou' } },
  // { cs: 'Štramberk', search: { country: 'czechia', city: 'Štramberk' } },
  // { cs: 'Kralovice', search: { country: 'czechia', city: 'Kralovice' } },
  // { cs: 'Dobrovice', search: { country: 'czechia', city: 'Dobrovice' } },
  // { cs: 'Veverská Bítýška', search: { country: 'czechia', city: 'Veverská Bítýška' } },
  // { cs: 'Krásná Lípa', search: { country: 'czechia', city: 'Krásná Lípa' } },
  // { cs: 'Újezd u Brna', search: { country: 'czechia', city: 'Újezd u Brna' } },
  // { cs: 'Libušín', search: { country: 'czechia', city: 'Libušín' } },
  // { cs: 'Trmice', search: { country: 'czechia', city: 'Trmice' } },
  // { cs: 'Staňkov', search: { country: 'czechia', city: 'Staňkov' } },
  // { cs: 'Hrušovany nad Jevišovkou', search: { country: 'czechia', city: 'Hrušovany nad Jevišovkou' } },
  // { cs: 'Nová Bystřice', search: { country: 'czechia', city: 'Nová Bystřice' } },
  // { cs: 'Sadská', search: { country: 'czechia', city: 'Sadská' } },
  // { cs: 'Košťany', search: { country: 'czechia', city: 'Košťany' } },
  // { cs: 'Chrast', search: { country: 'czechia', city: 'Chrast' } },
  // { cs: 'Jablonné nad Orlicí', search: { country: 'czechia', city: 'Jablonné nad Orlicí' } },
  // { cs: 'Ždírec nad Doubravou', search: { country: 'czechia', city: 'Ždírec nad Doubravou' } },
  // { cs: 'Žacléř', search: { country: 'czechia', city: 'Žacléř' } },
  // { cs: 'Uhlířské Janovice', search: { country: 'czechia', city: 'Uhlířské Janovice' } },
  // { cs: 'Velké Pavlovice', search: { country: 'czechia', city: 'Velké Pavlovice' } },
  // { cs: 'Desná', search: { country: 'czechia', city: 'Desná' } },
  // { cs: 'Opočno', search: { country: 'czechia', city: 'Opočno' } },
  // { cs: 'Loket', search: { country: 'czechia', city: 'Loket' } },
  // { cs: 'Velvary', search: { country: 'czechia', city: 'Velvary' } },
  // { cs: 'Kaznějov', search: { country: 'czechia', city: 'Kaznějov' } },
  // { cs: 'Břidličná', search: { country: 'czechia', city: 'Břidličná' } },
  // { cs: 'Třemošnice', search: { country: 'czechia', city: 'Třemošnice' } },
  // { cs: 'Hanušovice', search: { country: 'czechia', city: 'Hanušovice' } },
  // { cs: 'Podivín', search: { country: 'czechia', city: 'Podivín' } },
  // { cs: 'Miroslav', search: { country: 'czechia', city: 'Miroslav' } },
  // { cs: 'Volyně', search: { country: 'czechia', city: 'Volyně' } },
  // { cs: 'Hodkovice nad Mohelkou', search: { country: 'czechia', city: 'Hodkovice nad Mohelkou' } },
  // { cs: 'Rtyně v Podkrkonoší', search: { country: 'czechia', city: 'Rtyně v Podkrkonoší' } },
  // { cs: 'Teplá', search: { country: 'czechia', city: 'Teplá' } },
  // { cs: 'Morkovice-Slížany', search: { country: 'czechia', city: 'Morkovice-Slížany' } },
  // { cs: 'Loštice', search: { country: 'czechia', city: 'Loštice' } },
  // { cs: 'Slušovice', search: { country: 'czechia', city: 'Slušovice' } },
  // { cs: 'Úštěk', search: { country: 'czechia', city: 'Úštěk' } },
  // { cs: 'Chvaletice', search: { country: 'czechia', city: 'Chvaletice' } },
  // { cs: 'Ivanovice na Hané', search: { country: 'czechia', city: 'Ivanovice na Hané' } },
  // { cs: 'Smiřice', search: { country: 'czechia', city: 'Smiřice' } },
  // { cs: 'Žirovnice', search: { country: 'czechia', city: 'Žirovnice' } },
  // { cs: 'Moravský Beroun', search: { country: 'czechia', city: 'Moravský Beroun' } },
  // { cs: 'Budišov nad Budišovkou', search: { country: 'czechia', city: 'Budišov nad Budišovkou' } },
  // { cs: 'Rotava', search: { country: 'czechia', city: 'Rotava' } },
  // { cs: 'Kostelec na Hané', search: { country: 'czechia', city: 'Kostelec na Hané' } },
  // { cs: 'Spálené Poříčí', search: { country: 'czechia', city: 'Spálené Poříčí' } },
  // { cs: 'Vejprty', search: { country: 'czechia', city: 'Vejprty' } },
  // { cs: 'Sedlec-Prčice', search: { country: 'czechia', city: 'Sedlec-Prčice' } },
  // { cs: 'Terezín', search: { country: 'czechia', city: 'Terezín' } },
  // { cs: 'Zákupy', search: { country: 'czechia', city: 'Zákupy' } },
  // { cs: 'Raspenava', search: { country: 'czechia', city: 'Raspenava' } },
  // { cs: 'Hrádek', search: { country: 'czechia', city: 'Hrádek' } },
  // { cs: 'Dolní Bousov', search: { country: 'czechia', city: 'Dolní Bousov' } },
  // { cs: 'Český Dub', search: { country: 'czechia', city: 'Český Dub' } },
  // { cs: 'Kunštát', search: { country: 'czechia', city: 'Kunštát' } },
  // { cs: 'Jevíčko', search: { country: 'czechia', city: 'Jevíčko' } },
  // { cs: 'Městec Králové', search: { country: 'czechia', city: 'Městec Králové' } },
  // { cs: 'Rychnov u Jablonce nad Nisou', search: { country: 'czechia', city: 'Rychnov u Jablonce nad Nisou' } },
  // { cs: 'Plasy', search: { country: 'czechia', city: 'Plasy' } },
  // { cs: 'Konice', search: { country: 'czechia', city: 'Konice' } },
  // { cs: 'Hejnice', search: { country: 'czechia', city: 'Hejnice' } },
  // { cs: 'Javorník', search: { country: 'czechia', city: 'Javorník' } },
  // { cs: 'Mladá Vožice', search: { country: 'czechia', city: 'Mladá Vožice' } },
  // { cs: 'Koryčany', search: { country: 'czechia', city: 'Koryčany' } },
  // { cs: 'Golčův Jeníkov', search: { country: 'czechia', city: 'Golčův Jeníkov' } },
  // { cs: 'Kelč', search: { country: 'czechia', city: 'Kelč' } },
  // { cs: 'Velké Hamry', search: { country: 'czechia', city: 'Velké Hamry' } },
  // { cs: 'Neveklov', search: { country: 'czechia', city: 'Neveklov' } },
  // { cs: 'Březová', search: { country: 'czechia', city: 'Březová' } },
  // { cs: 'Vyšší Brod', search: { country: 'czechia', city: 'Vyšší Brod' } },
  // { cs: 'Luže', search: { country: 'czechia', city: 'Luže' } },
  // { cs: 'Nové Sedlo', search: { country: 'czechia', city: 'Nové Sedlo' } },
  // { cs: 'Rokytnice nad Jizerou', search: { country: 'czechia', city: 'Rokytnice nad Jizerou' } },
  // { cs: 'Rudolfov', search: { country: 'czechia', city: 'Rudolfov' } },
  // { cs: 'Netolice', search: { country: 'czechia', city: 'Netolice' } },
  // { cs: 'Počátky', search: { country: 'czechia', city: 'Počátky' } },
  // { cs: 'Chabařovice', search: { country: 'czechia', city: 'Chabařovice' } },
  // { cs: 'Nové Hrady', search: { country: 'czechia', city: 'Nové Hrady' } },
  // { cs: 'Zbiroh', search: { country: 'czechia', city: 'Zbiroh' } },
  // { cs: 'Ždánice', search: { country: 'czechia', city: 'Ždánice' } },
  // { cs: 'Klobouky u Brna', search: { country: 'czechia', city: 'Klobouky u Brna' } },
  // { cs: 'Bohušovice nad Ohří', search: { country: 'czechia', city: 'Bohušovice nad Ohří' } },
  // { cs: 'Chýnov', search: { country: 'czechia', city: 'Chýnov' } },
  // { cs: 'Dolní Kounice', search: { country: 'czechia', city: 'Dolní Kounice' } },
  // { cs: 'Tovačov', search: { country: 'czechia', city: 'Tovačov' } },
  // { cs: 'Karolinka', search: { country: 'czechia', city: 'Karolinka' } },
  // { cs: 'Jáchymov', search: { country: 'czechia', city: 'Jáchymov' } },
  // { cs: 'Sobotka', search: { country: 'czechia', city: 'Sobotka' } },
  // { cs: 'Dašice', search: { country: 'czechia', city: 'Dašice' } },
  // { cs: 'Meziměstí', search: { country: 'czechia', city: 'Meziměstí' } },
  // { cs: 'Kryry', search: { country: 'czechia', city: 'Kryry' } },
  // { cs: 'Nechanice', search: { country: 'czechia', city: 'Nechanice' } },
  // { cs: 'Slavonice', search: { country: 'czechia', city: 'Slavonice' } },
  // { cs: 'Janovice nad Úhlavou', search: { country: 'czechia', city: 'Janovice nad Úhlavou' } },
  // { cs: 'Plumlov', search: { country: 'czechia', city: 'Plumlov' } },
  // { cs: 'Mirošov', search: { country: 'czechia', city: 'Mirošov' } },
  // { cs: 'Nová Včelnice', search: { country: 'czechia', city: 'Nová Včelnice' } },
  // { cs: 'Veltrusy', search: { country: 'czechia', city: 'Veltrusy' } },
  // { cs: 'Žlutice', search: { country: 'czechia', city: 'Žlutice' } },
  // { cs: 'Solnice', search: { country: 'czechia', city: 'Solnice' } },
  // { cs: 'Horní Jiřetín', search: { country: 'czechia', city: 'Horní Jiřetín' } },
  // { cs: 'Horní Benešov', search: { country: 'czechia', city: 'Horní Benešov' } },
  // { cs: 'Kardašova Řečice', search: { country: 'czechia', city: 'Kardašova Řečice' } },
  // { cs: 'Žebrák', search: { country: 'czechia', city: 'Žebrák' } },
  // { cs: 'Město Touškov', search: { country: 'czechia', city: 'Město Touškov' } },
  // { cs: 'Hranice', search: { country: 'czechia', city: 'Hranice' } },
  // { cs: 'Budyně nad Ohří', search: { country: 'czechia', city: 'Budyně nad Ohří' } },
  // { cs: 'Luby', search: { country: 'czechia', city: 'Luby' } },
  // { cs: 'Ralsko', search: { country: 'czechia', city: 'Ralsko' } },
  // { cs: 'Kopidlno', search: { country: 'czechia', city: 'Kopidlno' } },
  // { cs: 'Mikulášovice', search: { country: 'czechia', city: 'Mikulášovice' } },
  // { cs: 'Borohrádek', search: { country: 'czechia', city: 'Borohrádek' } },
  // { cs: 'Týnec nad Labem', search: { country: 'czechia', city: 'Týnec nad Labem' } },
  // { cs: 'Nový Knín', search: { country: 'czechia', city: 'Nový Knín' } },
  // { cs: 'Proseč', search: { country: 'czechia', city: 'Proseč' } },
  // { cs: 'Pyšely', search: { country: 'czechia', city: 'Pyšely' } },
  // { cs: 'Horní Jelení', search: { country: 'czechia', city: 'Horní Jelení' } },
  // { cs: 'Hrochův Týnec', search: { country: 'czechia', city: 'Hrochův Týnec' } },
  // { cs: 'Horní Planá', search: { country: 'czechia', city: 'Horní Planá' } },
  // { cs: 'Hroznětín', search: { country: 'czechia', city: 'Hroznětín' } },
  // { cs: 'Svoboda nad Úpou', search: { country: 'czechia', city: 'Svoboda nad Úpou' } },
  // { cs: 'Jistebnice', search: { country: 'czechia', city: 'Jistebnice' } },
  // { cs: 'Hrob', search: { country: 'czechia', city: 'Hrob' } },
  // { cs: 'Zásmuky', search: { country: 'czechia', city: 'Zásmuky' } },
  // { cs: 'Skalná', search: { country: 'czechia', city: 'Skalná' } },
  // { cs: 'Rokytnice v Orlických horách', search: { country: 'czechia', city: 'Rokytnice v Orlických horách' } },
  // { cs: 'Štíty', search: { country: 'czechia', city: 'Štíty' } },
  // { cs: 'Velký Šenov', search: { country: 'czechia', city: 'Velký Šenov' } },
  // { cs: 'Němčice nad Hanou', search: { country: 'czechia', city: 'Němčice nad Hanou' } },
  // { cs: 'Plesná', search: { country: 'czechia', city: 'Plesná' } },
  // { cs: 'Třebenice', search: { country: 'czechia', city: 'Třebenice' } },
  // { cs: 'Libáň', search: { country: 'czechia', city: 'Libáň' } },
  // { cs: 'Smečno', search: { country: 'czechia', city: 'Smečno' } },
  // { cs: 'Bochov', search: { country: 'czechia', city: 'Bochov' } },
  // { cs: 'Kouřim', search: { country: 'czechia', city: 'Kouřim' } },
  // { cs: 'Lučany nad Nisou', search: { country: 'czechia', city: 'Lučany nad Nisou' } },
  // { cs: 'Žandov', search: { country: 'czechia', city: 'Žandov' } },
  // { cs: 'Horní Cerekev', search: { country: 'czechia', city: 'Horní Cerekev' } },
  // { cs: 'Vroutek', search: { country: 'czechia', city: 'Vroutek' } },
  // { cs: 'Hostomice', search: { country: 'czechia', city: 'Hostomice' } },
  // { cs: 'Radnice', search: { country: 'czechia', city: 'Radnice' } },
  // { cs: 'Lomnice nad Lužnicí', search: { country: 'czechia', city: 'Lomnice nad Lužnicí' } },
  // { cs: 'Hrotovice', search: { country: 'czechia', city: 'Hrotovice' } },
  // { cs: 'Černovice', search: { country: 'czechia', city: 'Černovice' } },
  // { cs: 'Bělá nad Radbuzou', search: { country: 'czechia', city: 'Bělá nad Radbuzou' } },
  // { cs: 'Seč', search: { country: 'czechia', city: 'Seč' } },
  // { cs: 'Hoštka', search: { country: 'czechia', city: 'Hoštka' } },
  // { cs: 'Dolní Poustevna', search: { country: 'czechia', city: 'Dolní Poustevna' } },
  // { cs: 'Vlachovo Březí', search: { country: 'czechia', city: 'Vlachovo Březí' } },
  // { cs: 'Dubá', search: { country: 'czechia', city: 'Dubá' } },
  // { cs: 'Ronov nad Doubravou', search: { country: 'czechia', city: 'Ronov nad Doubravou' } },
  // { cs: 'Jesenice', search: { country: 'czechia', city: 'Jesenice' } },
  // { cs: 'Staré Město', search: { country: 'czechia', city: 'Staré Město' } },
  // { cs: 'Nasavrky', search: { country: 'czechia', city: 'Nasavrky' } },
  // { cs: 'Olešnice', search: { country: 'czechia', city: 'Olešnice' } },
  // { cs: 'Švihov', search: { country: 'czechia', city: 'Švihov' } },
  // { cs: 'Plánice', search: { country: 'czechia', city: 'Plánice' } },
  // { cs: 'Oloví', search: { country: 'czechia', city: 'Oloví' } },
  // { cs: 'Rožďalovice', search: { country: 'czechia', city: 'Rožďalovice' } },
  // { cs: 'Bavorov', search: { country: 'czechia', city: 'Bavorov' } },
  // { cs: 'Kladruby', search: { country: 'czechia', city: 'Kladruby' } },
  // { cs: 'Železná Ruda', search: { country: 'czechia', city: 'Železná Ruda' } },
  // { cs: 'Březová nad Svitavou', search: { country: 'czechia', city: 'Březová nad Svitavou' } },
  // { cs: 'Všeruby', search: { country: 'czechia', city: 'Všeruby' } },
  // { cs: 'Mirovice', search: { country: 'czechia', city: 'Mirovice' } },
  // { cs: 'Teplice nad Metují', search: { country: 'czechia', city: 'Teplice nad Metují' } },
  // { cs: 'Jablonec nad Jizerou', search: { country: 'czechia', city: 'Jablonec nad Jizerou' } },
  // { cs: 'Přimda', search: { country: 'czechia', city: 'Přimda' } },
  // { cs: 'Poběžovice', search: { country: 'czechia', city: 'Poběžovice' } },
  // { cs: 'Mýto', search: { country: 'czechia', city: 'Mýto' } },
  // { cs: 'Bystré', search: { country: 'czechia', city: 'Bystré' } },
  // { cs: 'Kožlany', search: { country: 'czechia', city: 'Kožlany' } },
  // { cs: 'Strmilov', search: { country: 'czechia', city: 'Strmilov' } },
  // { cs: 'Mšeno', search: { country: 'czechia', city: 'Mšeno' } },
  // { cs: 'Husinec', search: { country: 'czechia', city: 'Husinec' } },
  // { cs: 'Lázně Kynžvart', search: { country: 'czechia', city: 'Lázně Kynžvart' } },
  // { cs: 'Strážov', search: { country: 'czechia', city: 'Strážov' } },
  // { cs: 'Trhový Štěpánov', search: { country: 'czechia', city: 'Trhový Štěpánov' } },
  // { cs: 'Kašperské Hory', search: { country: 'czechia', city: 'Kašperské Hory' } },
  // { cs: 'Svratka', search: { country: 'czechia', city: 'Svratka' } },
  // { cs: 'Chřibská', search: { country: 'czechia', city: 'Chřibská' } },
  // { cs: 'Harrachov', search: { country: 'czechia', city: 'Harrachov' } },
  // { cs: 'Habry', search: { country: 'czechia', city: 'Habry' } },
  // { cs: 'Železnice', search: { country: 'czechia', city: 'Železnice' } },
  // { cs: 'Kasejovice', search: { country: 'czechia', city: 'Kasejovice' } },
  // { cs: 'Brandýs nad Orlicí', search: { country: 'czechia', city: 'Brandýs nad Orlicí' } },
  // { cs: 'Rovensko pod Troskami', search: { country: 'czechia', city: 'Rovensko pod Troskami' } },
  // { cs: 'Vysoké nad Jizerou', search: { country: 'czechia', city: 'Vysoké nad Jizerou' } },
  // { cs: 'Vidnava', search: { country: 'czechia', city: 'Vidnava' } },
  // { cs: 'Sedlice', search: { country: 'czechia', city: 'Sedlice' } },
  // { cs: 'Mirotice', search: { country: 'czechia', city: 'Mirotice' } },
  // { cs: 'Pilníkov', search: { country: 'czechia', city: 'Pilníkov' } },
  // { cs: 'Hostouň', search: { country: 'czechia', city: 'Hostouň' } },
  // { cs: 'Žulová', search: { country: 'czechia', city: 'Žulová' } },
  // { cs: 'Černošín', search: { country: 'czechia', city: 'Černošín' } },
  // { cs: 'Potštát', search: { country: 'czechia', city: 'Potštát' } },
  // { cs: 'Osečná', search: { country: 'czechia', city: 'Osečná' } },
  // { cs: 'Verneřice', search: { country: 'czechia', city: 'Verneřice' } },
  // { cs: 'Nalžovské Hory', search: { country: 'czechia', city: 'Nalžovské Hory' } },
  // { cs: 'Úsov', search: { country: 'czechia', city: 'Úsov' } },
  // { cs: 'Jevišovice', search: { country: 'czechia', city: 'Jevišovice' } },
  // { cs: 'Manětín', search: { country: 'czechia', city: 'Manětín' } },
  // { cs: 'Měčín', search: { country: 'czechia', city: 'Měčín' } },
  // { cs: 'Krásná Hora nad Vltavou', search: { country: 'czechia', city: 'Krásná Hora nad Vltavou' } },
  // { cs: 'Špindlerův Mlýn', search: { country: 'czechia', city: 'Špindlerův Mlýn' } },
  // { cs: 'Liběchov', search: { country: 'czechia', city: 'Liběchov' } },
  // { cs: 'Červená Řečice', search: { country: 'czechia', city: 'Červená Řečice' } },
  // { cs: 'Blšany', search: { country: 'czechia', city: 'Blšany' } },
  // { cs: 'Bělčice', search: { country: 'czechia', city: 'Bělčice' } },
  // { cs: 'Bečov nad Teplou', search: { country: 'czechia', city: 'Bečov nad Teplou' } },
  // { cs: 'Hartmanice', search: { country: 'czechia', city: 'Hartmanice' } },
  // { cs: 'Bezdružice', search: { country: 'czechia', city: 'Bezdružice' } },
  // { cs: 'Miletín', search: { country: 'czechia', city: 'Miletín' } },
  // { cs: 'Abertamy', search: { country: 'czechia', city: 'Abertamy' } },
  // { cs: 'Stráž nad Nežárkou', search: { country: 'czechia', city: 'Stráž nad Nežárkou' } },
  // { cs: 'Vysoké Veselí', search: { country: 'czechia', city: 'Vysoké Veselí' } },
  // { cs: 'Deštná', search: { country: 'czechia', city: 'Deštná' } },
  // { cs: 'Krásno', search: { country: 'czechia', city: 'Krásno' } },
  // { cs: 'Janské Lázně', search: { country: 'czechia', city: 'Janské Lázně' } },
  // { cs: 'Stárkov', search: { country: 'czechia', city: 'Stárkov' } },
  // { cs: 'Lipnice nad Sázavou', search: { country: 'czechia', city: 'Lipnice nad Sázavou' } },
  // { cs: 'Pec pod Sněžkou', search: { country: 'czechia', city: 'Pec pod Sněžkou' } },
  // { cs: 'Chyše', search: { country: 'czechia', city: 'Chyše' } },
  // { cs: 'Mašťov', search: { country: 'czechia', city: 'Mašťov' } },
  // { cs: 'Ledvice', search: { country: 'czechia', city: 'Ledvice' } },
  // { cs: 'Rabí', search: { country: 'czechia', city: 'Rabí' } },
  // { cs: 'Úterý', search: { country: 'czechia', city: 'Úterý' } },
  // { cs: 'Hora Svaté Kateřiny', search: { country: 'czechia', city: 'Hora Svaté Kateřiny' } },
  // { cs: 'Výsluní', search: { country: 'czechia', city: 'Výsluní' } },
  // { cs: 'Horní Blatná', search: { country: 'czechia', city: 'Horní Blatná' } },
  // { cs: 'Krásné Údolí', search: { country: 'czechia', city: 'Krásné Údolí' } },
  // { cs: 'Rožmberk nad Vltavou', search: { country: 'czechia', city: 'Rožmberk nad Vltavou' } },
  // { cs: 'Andělská Hora', search: { country: 'czechia', city: 'Andělská Hora' } },
  // { cs: 'Janov', search: { country: 'czechia', city: 'Janov' } },
  // { cs: 'Rejštejn', search: { country: 'czechia', city: 'Rejštejn' } },
  // { cs: 'Boží Dar', search: { country: 'czechia', city: 'Boží Dar' } },
  // { cs: 'Loučná pod Klínovcem', search: { country: 'czechia', city: 'Loučná pod Klínovcem' } },
  // { cs: 'Přebuz', search: { country: 'czechia', city: 'Přebuz' } }
];