/**
 * 🏭 GENERATED WITH features-generator
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution
 */

export const FEATURES: any = [
    { cs: 'world', search: { q: 'world' } },
    { cs: 'China', search: { q: 'China' } },
    { cs: 'India', search: { q: 'India' } },
    { cs: 'United States', search: { q: 'United States' } },
    { cs: 'Indonesia', search: { q: 'Indonesia' } },
    { cs: 'Pakistan', search: { q: 'Pakistan' } },
    { cs: 'Brazil', search: { q: 'Brazil' } },
    { cs: 'Nigeria', search: { q: 'Nigeria' } },
    { cs: 'Bangladesh', search: { q: 'Bangladesh' } },
    { cs: 'Russia', search: { q: 'Russia' } },
    { cs: 'Mexico', search: { q: 'Mexico' } },
    { cs: 'Japan', search: { q: 'Japan' } },
    { cs: 'Ethiopia', search: { q: 'Ethiopia' } },
    { cs: 'Philippines', search: { q: 'Philippines' } },
    { cs: 'Egypt', search: { q: 'Egypt' } },
    { cs: 'Vietnam', search: { q: 'Vietnam' } },
    { cs: 'DR Congo', search: { q: 'DR Congo' } },
    { cs: 'Iran', search: { q: 'Iran' } },
    { cs: 'Turkey', search: { q: 'Turkey' } },
    { cs: 'Germany', search: { q: 'Germany' } },
    { cs: 'France', search: { q: 'France' } },
    { cs: 'United Kingdom', search: { q: 'United Kingdom' } },
    { cs: 'Thailand', search: { q: 'Thailand' } },
    { cs: 'South Africa', search: { q: 'South Africa' } },
    { cs: 'Tanzania', search: { q: 'Tanzania' } },
    { cs: 'Italy', search: { q: 'Italy' } },
    { cs: 'Myanmar', search: { q: 'Myanmar' } },
    { cs: 'South Korea', search: { q: 'South Korea' } },
    { cs: 'Colombia', search: { q: 'Colombia' } },
    { cs: 'Kenya', search: { q: 'Kenya' } },
    { cs: 'Spain', search: { q: 'Spain' } },
    { cs: 'Argentina', search: { q: 'Argentina' } },
    { cs: 'Algeria', search: { q: 'Algeria' } },
    { cs: 'Sudan', search: { q: 'Sudan' } },
    { cs: 'Uganda', search: { q: 'Uganda' } },
    { cs: 'Iraq', search: { q: 'Iraq' } },
    { cs: 'Ukraine', search: { q: 'Ukraine' } },
    { cs: 'Canada', search: { q: 'Canada' } },
    { cs: 'Poland', search: { q: 'Poland' } },
    { cs: 'Morocco', search: { q: 'Morocco' } },
    { cs: 'Uzbekistan', search: { q: 'Uzbekistan' } },
    { cs: 'Saudi Arabia', search: { q: 'Saudi Arabia' } },
    { cs: 'Peru', search: { q: 'Peru' } },
    { cs: 'Afghanistan', search: { q: 'Afghanistan' } },
    { cs: 'Malaysia', search: { q: 'Malaysia' } },
    { cs: 'Angola', search: { q: 'Angola' } },
    { cs: 'Mozambique', search: { q: 'Mozambique' } },
    { cs: 'Ghana', search: { q: 'Ghana' } },
    { cs: 'Yemen', search: { q: 'Yemen' } },
    { cs: 'Nepal', search: { q: 'Nepal' } },
    { cs: 'Venezuela', search: { q: 'Venezuela' } },
    { cs: 'Ivory Coast', search: { q: 'Ivory Coast' } },
    { cs: 'Madagascar', search: { q: 'Madagascar' } },
    { cs: 'Australia', search: { q: 'Australia' } },
    { cs: 'North Korea', search: { q: 'North Korea' } },
    { cs: 'Cameroon', search: { q: 'Cameroon' } },
    { cs: 'Niger', search: { q: 'Niger' } },
    { cs: 'Taiwan', search: { q: 'Taiwan' } },
    { cs: 'Sri Lanka', search: { q: 'Sri Lanka' } },
    { cs: 'Burkina Faso', search: { q: 'Burkina Faso' } },
    { cs: 'Mali', search: { q: 'Mali' } },
    { cs: 'Chile', search: { q: 'Chile' } },
    { cs: 'Romania', search: { q: 'Romania' } },
    { cs: 'Kazakhstan', search: { q: 'Kazakhstan' } },
    { cs: 'Malawi', search: { q: 'Malawi' } },
    { cs: 'Zambia', search: { q: 'Zambia' } },
    { cs: 'Syria', search: { q: 'Syria' } },
    { cs: 'Ecuador', search: { q: 'Ecuador' } },
    { cs: 'Netherlands', search: { q: 'Netherlands' } },
    { cs: 'Senegal', search: { q: 'Senegal' } },
    { cs: 'Guatemala', search: { q: 'Guatemala' } },
    { cs: 'Chad', search: { q: 'Chad' } },
    { cs: 'Somalia', search: { q: 'Somalia' } },
    { cs: 'Zimbabwe', search: { q: 'Zimbabwe' } },
    { cs: 'Cambodia', search: { q: 'Cambodia' } },
    { cs: 'South Sudan', search: { q: 'South Sudan' } },
    { cs: 'Rwanda', search: { q: 'Rwanda' } },
    { cs: 'Guinea', search: { q: 'Guinea' } },
    { cs: 'Burundi', search: { q: 'Burundi' } },
    { cs: 'Benin', search: { q: 'Benin' } },
    { cs: 'Bolivia', search: { q: 'Bolivia' } },
    { cs: 'Tunisia', search: { q: 'Tunisia' } },
    { cs: 'Haiti', search: { q: 'Haiti' } },
    { cs: 'Belgium', search: { q: 'Belgium' } },
    { cs: 'Cuba', search: { q: 'Cuba' } },
    { cs: 'Jordan', search: { q: 'Jordan' } },
    { cs: 'Greece', search: { q: 'Greece' } },
    { cs: 'Dominican Republic', search: { q: 'Dominican Republic' } },
    { cs: 'Czech Republic', search: { q: 'Czech Republic' } },
    { cs: 'Sweden', search: { q: 'Sweden' } },
    { cs: 'Portugal', search: { q: 'Portugal' } },
    { cs: 'Azerbaijan', search: { q: 'Azerbaijan' } },
    { cs: 'Hungary', search: { q: 'Hungary' } },
    { cs: 'Tajikistan', search: { q: 'Tajikistan' } },
    { cs: 'United Arab Emirates', search: { q: 'United Arab Emirates' } },
    { cs: 'Israel', search: { q: 'Israel' } },
    { cs: 'Honduras', search: { q: 'Honduras' } },
    { cs: 'Belarus', search: { q: 'Belarus' } },
    { cs: 'Papua New Guinea', search: { q: 'Papua New Guinea' } },
    { cs: 'Austria', search: { q: 'Austria' } },
    { cs: 'Switzerland', search: { q: 'Switzerland' } },
    { cs: 'Sierra Leone', search: { q: 'Sierra Leone' } },
    { cs: 'Togo', search: { q: 'Togo' } },
    { cs: 'Hong Kong (China)', search: { q: 'Hong Kong (China)' } },
    { cs: 'Paraguay', search: { q: 'Paraguay' } },
    { cs: 'Laos', search: { q: 'Laos' } },
    { cs: 'Libya', search: { q: 'Libya' } },
    { cs: 'Serbia', search: { q: 'Serbia' } },
    { cs: 'El Salvador', search: { q: 'El Salvador' } },
    { cs: 'Lebanon', search: { q: 'Lebanon' } },
    { cs: 'Kyrgyzstan', search: { q: 'Kyrgyzstan' } },
    { cs: 'Nicaragua', search: { q: 'Nicaragua' } },
    { cs: 'Bulgaria', search: { q: 'Bulgaria' } },
    { cs: 'Turkmenistan', search: { q: 'Turkmenistan' } },
    { cs: 'Denmark', search: { q: 'Denmark' } },
    { cs: 'Congo', search: { q: 'Congo' } },
    { cs: 'Central African Republic', search: { q: 'Central African Republic' } },
    { cs: 'Finland', search: { q: 'Finland' } },
    { cs: 'Singapore', search: { q: 'Singapore' } },
    { cs: 'Slovakia', search: { q: 'Slovakia' } },
    { cs: 'Norway', search: { q: 'Norway' } },
    { cs: 'Palestine', search: { q: 'Palestine' } },
    { cs: 'Costa Rica', search: { q: 'Costa Rica' } },
    { cs: 'New Zealand', search: { q: 'New Zealand' } },
    { cs: 'Ireland', search: { q: 'Ireland' } },
    { cs: 'Kuwait', search: { q: 'Kuwait' } },
    { cs: 'Liberia', search: { q: 'Liberia' } },
    { cs: 'Oman', search: { q: 'Oman' } },
    { cs: 'Panama', search: { q: 'Panama' } },
    { cs: 'Mauritania', search: { q: 'Mauritania' } },
    { cs: 'Croatia', search: { q: 'Croatia' } },
    { cs: 'Georgia', search: { q: 'Georgia' } },
    { cs: 'Eritrea', search: { q: 'Eritrea' } },
    { cs: 'Uruguay', search: { q: 'Uruguay' } },
    { cs: 'Mongolia', search: { q: 'Mongolia' } },
    { cs: 'Bosnia and Herzegovina', search: { q: 'Bosnia and Herzegovina' } },
    { cs: 'Puerto Rico (United States)', search: { q: 'Puerto Rico (United States)' } },
    { cs: 'Armenia', search: { q: 'Armenia' } },
    { cs: 'Albania', search: { q: 'Albania' } },
    { cs: 'Qatar', search: { q: 'Qatar' } },
    { cs: 'Lithuania', search: { q: 'Lithuania' } },
    { cs: 'Jamaica', search: { q: 'Jamaica' } },
    { cs: 'Moldova', search: { q: 'Moldova' } },
    { cs: 'Namibia', search: { q: 'Namibia' } },
    { cs: 'Gambia', search: { q: 'Gambia' } },
    { cs: 'Botswana', search: { q: 'Botswana' } },
    { cs: 'Gabon', search: { q: 'Gabon' } },
    { cs: 'Lesotho', search: { q: 'Lesotho' } },
    { cs: 'Slovenia', search: { q: 'Slovenia' } },
    { cs: 'Latvia', search: { q: 'Latvia' } },
    { cs: 'North Macedonia', search: { q: 'North Macedonia' } },
    { cs: 'Kosovo', search: { q: 'Kosovo' } },
    { cs: 'Guinea-Bissau', search: { q: 'Guinea-Bissau' } },
    { cs: 'Equatorial Guinea', search: { q: 'Equatorial Guinea' } },
    { cs: 'Bahrain', search: { q: 'Bahrain' } },
    { cs: 'Trinidad and Tobago', search: { q: 'Trinidad and Tobago' } },
    { cs: 'Estonia', search: { q: 'Estonia' } },
    { cs: 'East Timor', search: { q: 'East Timor' } },
    { cs: 'Mauritius', search: { q: 'Mauritius' } },
    { cs: 'Eswatini', search: { q: 'Eswatini' } },
    { cs: 'Djibouti', search: { q: 'Djibouti' } },
    { cs: 'Fiji', search: { q: 'Fiji' } },
    { cs: 'Cyprus', search: { q: 'Cyprus' } },
    { cs: 'Comoros', search: { q: 'Comoros' } },
    { cs: 'Bhutan', search: { q: 'Bhutan' } },
    { cs: 'Guyana', search: { q: 'Guyana' } },
    { cs: 'Solomon Islands', search: { q: 'Solomon Islands' } },
    { cs: 'Macau (China)', search: { q: 'Macau (China)' } },
    { cs: 'Luxembourg', search: { q: 'Luxembourg' } },
    { cs: 'Montenegro', search: { q: 'Montenegro' } },
    { cs: 'Western Sahara', search: { q: 'Western Sahara' } },
    { cs: 'Suriname', search: { q: 'Suriname' } },
    { cs: 'Cape Verde', search: { q: 'Cape Verde' } },
    { cs: 'Malta', search: { q: 'Malta' } },
    { cs: 'Belize', search: { q: 'Belize' } },
    { cs: 'Brunei', search: { q: 'Brunei' } },
    { cs: 'Bahamas', search: { q: 'Bahamas' } },
    { cs: 'Maldives', search: { q: 'Maldives' } },
    { cs: 'Northern Cyprus', search: { q: 'Northern Cyprus' } },
    { cs: 'Iceland', search: { q: 'Iceland' } },
    { cs: 'Transnistria', search: { q: 'Transnistria' } },
    { cs: 'Vanuatu', search: { q: 'Vanuatu' } },
    { cs: 'Barbados', search: { q: 'Barbados' } },
    { cs: 'French Polynesia (France)', search: { q: 'French Polynesia (France)' } },
    { cs: 'New Caledonia (France)', search: { q: 'New Caledonia (France)' } },
    { cs: 'Abkhazia', search: { q: 'Abkhazia' } },
    { cs: 'São Tomé and Príncipe', search: { q: 'São Tomé and Príncipe' } },
    { cs: 'Samoa', search: { q: 'Samoa' } },
    { cs: 'Saint Lucia', search: { q: 'Saint Lucia' } },
    { cs: 'Guam (United States)', search: { q: 'Guam (United States)' } },
    { cs: 'Curaçao (Netherlands)', search: { q: 'Curaçao (Netherlands)' } },
    { cs: 'Republic of Artsakh', search: { q: 'Republic of Artsakh' } },
    { cs: 'Kiribati', search: { q: 'Kiribati' } },
    { cs: 'Grenada', search: { q: 'Grenada' } },
    { cs: 'Aruba (Netherlands)', search: { q: 'Aruba (Netherlands)' } },
    { cs: 'Saint Vincent and the Grenadines', search: { q: 'Saint Vincent and the Grenadines' } },
    { cs: 'Jersey (British Crown Dependency)', search: { q: 'Jersey (British Crown Dependency)' } },
    { cs: 'Micronesia', search: { q: 'Micronesia' } },
    { cs: 'Tonga', search: { q: 'Tonga' } },
    { cs: 'Antigua and Barbuda', search: { q: 'Antigua and Barbuda' } },
    { cs: 'Seychelles', search: { q: 'Seychelles' } },
    { cs: 'U.S. Virgin Islands (United States)', search: { q: 'U.S. Virgin Islands (United States)' } },
    { cs: 'Isle of Man (British Crown Dependency)', search: { q: 'Isle of Man (British Crown Dependency)' } },
    { cs: 'Andorra', search: { q: 'Andorra' } },
    { cs: 'Dominica', search: { q: 'Dominica' } },
    { cs: 'Cayman Islands (United Kingdom)', search: { q: 'Cayman Islands (United Kingdom)' } },
    { cs: 'Bermuda (United Kingdom)', search: { q: 'Bermuda (United Kingdom)' } },
    { cs: 'Guernsey (British Crown Dependency)', search: { q: 'Guernsey (British Crown Dependency)' } },
    { cs: 'Greenland (Denmark)', search: { q: 'Greenland (Denmark)' } },
    { cs: 'Marshall Islands', search: { q: 'Marshall Islands' } },
    { cs: 'Saint Kitts and Nevis', search: { q: 'Saint Kitts and Nevis' } },
    { cs: 'Faroe Islands (Denmark)', search: { q: 'Faroe Islands (Denmark)' } },
    { cs: 'South Ossetia', search: { q: 'South Ossetia' } },
    { cs: 'American Samoa (United States)', search: { q: 'American Samoa (United States)' } },
    { cs: 'Northern Mariana Islands (United States)', search: { q: 'Northern Mariana Islands (United States)' } },
    { cs: 'Turks and Caicos Islands (United Kingdom)', search: { q: 'Turks and Caicos Islands (United Kingdom)' } },
    { cs: 'Sint Maarten (Netherlands)', search: { q: 'Sint Maarten (Netherlands)' } },
    { cs: 'Liechtenstein', search: { q: 'Liechtenstein' } },
    { cs: 'Monaco', search: { q: 'Monaco' } },
    { cs: 'Gibraltar (United Kingdom)', search: { q: 'Gibraltar (United Kingdom)' } },
    { cs: 'San Marino', search: { q: 'San Marino' } },
    { cs: 'Saint Martin (France)', search: { q: 'Saint Martin (France)' } },
    { cs: 'Åland (Finland)', search: { q: 'Åland (Finland)' } },
    { cs: 'British Virgin Islands (United Kingdom)', search: { q: 'British Virgin Islands (United Kingdom)' } },
    { cs: 'Palau', search: { q: 'Palau' } },
    { cs: 'Cook Islands (New Zealand)', search: { q: 'Cook Islands (New Zealand)' } },
    { cs: 'Anguilla (United Kingdom)', search: { q: 'Anguilla (United Kingdom)' } },
    { cs: 'Nauru', search: { q: 'Nauru' } },
    { cs: 'Wallis and Futuna (France)', search: { q: 'Wallis and Futuna (France)' } },
    { cs: 'Tuvalu', search: { q: 'Tuvalu' } },
    { cs: 'Saint Barthélemy (France)', search: { q: 'Saint Barthélemy (France)' } },
    {
        cs: 'Saint Helena, Ascension and Tristan da Cunha (United Kingdom)',
        search: { q: 'Saint Helena, Ascension and Tristan da Cunha (United Kingdom)' },
    },
    { cs: 'Saint Pierre and Miquelon (France)', search: { q: 'Saint Pierre and Miquelon (France)' } },
    { cs: 'Montserrat (United Kingdom)', search: { q: 'Montserrat (United Kingdom)' } },
    { cs: 'Falkland Islands (United Kingdom)', search: { q: 'Falkland Islands (United Kingdom)' } },
    { cs: 'Christmas Island (Australia)', search: { q: 'Christmas Island (Australia)' } },
    { cs: 'Norfolk Island (Australia)', search: { q: 'Norfolk Island (Australia)' } },
    { cs: 'Niue (New Zealand)', search: { q: 'Niue (New Zealand)' } },
    { cs: 'Tokelau (New Zealand)', search: { q: 'Tokelau (New Zealand)' } },
    { cs: 'Vatican City', search: { q: 'Vatican City' } },
    { cs: 'Cocos (Keeling) Islands (Australia)', search: { q: 'Cocos (Keeling) Islands (Australia)' } },
    { cs: 'Pitcairn Islands (United Kingdom)', search: { q: 'Pitcairn Islands (United Kingdom)' } },
    { cs: 'Praha', search: { country: 'czechia', q: 'Praha' } },
    { cs: 'Brno', search: { country: 'czechia', q: 'Brno' } },
    { cs: 'Ostrava', search: { country: 'czechia', q: 'Ostrava' } },
    { cs: 'Plzeň', search: { country: 'czechia', q: 'Plzeň' } },
    { cs: 'Liberec', search: { country: 'czechia', q: 'Liberec' } },
    { cs: 'Olomouc', search: { country: 'czechia', q: 'Olomouc' } },
    { cs: 'České Budějovice', search: { country: 'czechia', q: 'České Budějovice' } },
    { cs: 'Hradec Králové', search: { country: 'czechia', q: 'Hradec Králové' } },
    { cs: 'Ústí nad Labem', search: { country: 'czechia', q: 'Ústí nad Labem' } },
    { cs: 'Pardubice', search: { country: 'czechia', q: 'Pardubice' } },
    { cs: 'Zlín', search: { country: 'czechia', q: 'Zlín' } },
    { cs: 'Havířov', search: { country: 'czechia', q: 'Havířov' } },
    { cs: 'Kladno', search: { country: 'czechia', q: 'Kladno' } },
    { cs: 'Most', search: { country: 'czechia', q: 'Most' } },
    { cs: 'Opava', search: { country: 'czechia', q: 'Opava' } },
    { cs: 'Frýdek-Místek', search: { country: 'czechia', q: 'Frýdek-Místek' } },
    { cs: 'Jihlava', search: { country: 'czechia', q: 'Jihlava' } },
    { cs: 'Karviná', search: { country: 'czechia', q: 'Karviná' } },
    { cs: 'Teplice', search: { country: 'czechia', q: 'Teplice' } },
    { cs: 'Chomutov', search: { country: 'czechia', q: 'Chomutov' } },
    { cs: 'Karlovy Vary', search: { country: 'czechia', q: 'Karlovy Vary' } },
    { cs: 'Děčín', search: { country: 'czechia', q: 'Děčín' } },
    { cs: 'Jablonec nad Nisou', search: { country: 'czechia', q: 'Jablonec nad Nisou' } },
    { cs: 'Mladá Boleslav', search: { country: 'czechia', q: 'Mladá Boleslav' } },
    { cs: 'Prostějov', search: { country: 'czechia', q: 'Prostějov' } },
    { cs: 'Přerov', search: { country: 'czechia', q: 'Přerov' } },
    { cs: 'Česká Lípa', search: { country: 'czechia', q: 'Česká Lípa' } },
    { cs: 'Třebíč', search: { country: 'czechia', q: 'Třebíč' } },
    { cs: 'Třinec', search: { country: 'czechia', q: 'Třinec' } },
    { cs: 'Tábor', search: { country: 'czechia', q: 'Tábor' } },
    { cs: 'Znojmo', search: { country: 'czechia', q: 'Znojmo' } },
    { cs: 'Kolín', search: { country: 'czechia', q: 'Kolín' } },
    { cs: 'Příbram', search: { country: 'czechia', q: 'Příbram' } },
    { cs: 'Cheb', search: { country: 'czechia', q: 'Cheb' } },
    { cs: 'Písek', search: { country: 'czechia', q: 'Písek' } },
    { cs: 'Trutnov', search: { country: 'czechia', q: 'Trutnov' } },
    { cs: 'Kroměříž', search: { country: 'czechia', q: 'Kroměříž' } },
    { cs: 'Orlová', search: { country: 'czechia', q: 'Orlová' } },
    { cs: 'Vsetín', search: { country: 'czechia', q: 'Vsetín' } },
    { cs: 'Šumperk', search: { country: 'czechia', q: 'Šumperk' } },
    { cs: 'Uherské Hradiště', search: { country: 'czechia', q: 'Uherské Hradiště' } },
    { cs: 'Břeclav', search: { country: 'czechia', q: 'Břeclav' } },
    { cs: 'Hodonín', search: { country: 'czechia', q: 'Hodonín' } },
    { cs: 'Český Těšín', search: { country: 'czechia', q: 'Český Těšín' } },
    { cs: 'Litoměřice', search: { country: 'czechia', q: 'Litoměřice' } },
    { cs: 'Litvínov', search: { country: 'czechia', q: 'Litvínov' } },
    { cs: 'Havlíčkův Brod', search: { country: 'czechia', q: 'Havlíčkův Brod' } },
    { cs: 'Nový Jičín', search: { country: 'czechia', q: 'Nový Jičín' } },
    { cs: 'Chrudim', search: { country: 'czechia', q: 'Chrudim' } },
    { cs: 'Krnov', search: { country: 'czechia', q: 'Krnov' } },
    { cs: 'Sokolov', search: { country: 'czechia', q: 'Sokolov' } },
    { cs: 'Strakonice', search: { country: 'czechia', q: 'Strakonice' } },
    { cs: 'Valašské Meziříčí', search: { country: 'czechia', q: 'Valašské Meziříčí' } },
    { cs: 'Klatovy', search: { country: 'czechia', q: 'Klatovy' } },
    { cs: 'Kopřivnice', search: { country: 'czechia', q: 'Kopřivnice' } },
    { cs: 'Jindřichův Hradec', search: { country: 'czechia', q: 'Jindřichův Hradec' } },
    { cs: 'Kutná Hora', search: { country: 'czechia', q: 'Kutná Hora' } },
    { cs: 'Vyškov', search: { country: 'czechia', q: 'Vyškov' } },
    { cs: 'Žďár nad Sázavou', search: { country: 'czechia', q: 'Žďár nad Sázavou' } },
    { cs: 'Bohumín', search: { country: 'czechia', q: 'Bohumín' } },
    { cs: 'Blansko', search: { country: 'czechia', q: 'Blansko' } },
    { cs: 'Beroun', search: { country: 'czechia', q: 'Beroun' } },
    { cs: 'Náchod', search: { country: 'czechia', q: 'Náchod' } },
    { cs: 'Mělník', search: { country: 'czechia', q: 'Mělník' } },
    { cs: 'Brandýs nad Labem-Stará Boleslav', search: { country: 'czechia', q: 'Brandýs nad Labem-Stará Boleslav' } },
    { cs: 'Jirkov', search: { country: 'czechia', q: 'Jirkov' } },
    { cs: 'Žatec', search: { country: 'czechia', q: 'Žatec' } },
    { cs: 'Kralupy nad Vltavou', search: { country: 'czechia', q: 'Kralupy nad Vltavou' } },
    { cs: 'Louny', search: { country: 'czechia', q: 'Louny' } },
    { cs: 'Kadaň', search: { country: 'czechia', q: 'Kadaň' } },
    { cs: 'Hranice', search: { country: 'czechia', q: 'Hranice' } },
    { cs: 'Otrokovice', search: { country: 'czechia', q: 'Otrokovice' } },
    { cs: 'Bílina', search: { country: 'czechia', q: 'Bílina' } },
    { cs: 'Benešov', search: { country: 'czechia', q: 'Benešov' } },
    { cs: 'Svitavy', search: { country: 'czechia', q: 'Svitavy' } },
    { cs: 'Jičín', search: { country: 'czechia', q: 'Jičín' } },
    { cs: 'Ostrov', search: { country: 'czechia', q: 'Ostrov' } },
    { cs: 'Uherský Brod', search: { country: 'czechia', q: 'Uherský Brod' } },
    { cs: 'Rožnov pod Radhoštěm', search: { country: 'czechia', q: 'Rožnov pod Radhoštěm' } },
    { cs: 'Říčany', search: { country: 'czechia', q: 'Říčany' } },
    { cs: 'Neratovice', search: { country: 'czechia', q: 'Neratovice' } },
    { cs: 'Pelhřimov', search: { country: 'czechia', q: 'Pelhřimov' } },
    { cs: 'Slaný', search: { country: 'czechia', q: 'Slaný' } },
    { cs: 'Bruntál', search: { country: 'czechia', q: 'Bruntál' } },
    { cs: 'Rakovník', search: { country: 'czechia', q: 'Rakovník' } },
    { cs: 'Dvůr Králové nad Labem', search: { country: 'czechia', q: 'Dvůr Králové nad Labem' } },
    { cs: 'Česká Třebová', search: { country: 'czechia', q: 'Česká Třebová' } },
    { cs: 'Varnsdorf', search: { country: 'czechia', q: 'Varnsdorf' } },
    { cs: 'Nymburk', search: { country: 'czechia', q: 'Nymburk' } },
    { cs: 'Poděbrady', search: { country: 'czechia', q: 'Poděbrady' } },
    { cs: 'Turnov', search: { country: 'czechia', q: 'Turnov' } },
    { cs: 'Klášterec nad Ohří', search: { country: 'czechia', q: 'Klášterec nad Ohří' } },
    { cs: 'Rokycany', search: { country: 'czechia', q: 'Rokycany' } },
    { cs: 'Ústí nad Orlicí', search: { country: 'czechia', q: 'Ústí nad Orlicí' } },
    { cs: 'Hlučín', search: { country: 'czechia', q: 'Hlučín' } },
    { cs: 'Zábřeh', search: { country: 'czechia', q: 'Zábřeh' } },
    { cs: 'Šternberk', search: { country: 'czechia', q: 'Šternberk' } },
    { cs: 'Aš', search: { country: 'czechia', q: 'Aš' } },
    { cs: 'Chodov', search: { country: 'czechia', q: 'Chodov' } },
    { cs: 'Tachov', search: { country: 'czechia', q: 'Tachov' } },
    { cs: 'Český Krumlov', search: { country: 'czechia', q: 'Český Krumlov' } },
    { cs: 'Roudnice nad Labem', search: { country: 'czechia', q: 'Roudnice nad Labem' } },
    { cs: 'Mariánské Lázně', search: { country: 'czechia', q: 'Mariánské Lázně' } },
    { cs: 'Krupka', search: { country: 'czechia', q: 'Krupka' } },
    { cs: 'Jaroměř', search: { country: 'czechia', q: 'Jaroměř' } },
    { cs: 'Čelákovice', search: { country: 'czechia', q: 'Čelákovice' } },
    { cs: 'Vrchlabí', search: { country: 'czechia', q: 'Vrchlabí' } },
    { cs: 'Vysoké Mýto', search: { country: 'czechia', q: 'Vysoké Mýto' } },
    { cs: 'Milovice', search: { country: 'czechia', q: 'Milovice' } },
    { cs: 'Boskovice', search: { country: 'czechia', q: 'Boskovice' } },
    { cs: 'Nový Bor', search: { country: 'czechia', q: 'Nový Bor' } },
    { cs: 'Holešov', search: { country: 'czechia', q: 'Holešov' } },
    { cs: 'Vlašim', search: { country: 'czechia', q: 'Vlašim' } },
    { cs: 'Velké Meziříčí', search: { country: 'czechia', q: 'Velké Meziříčí' } },
    { cs: 'Uničov', search: { country: 'czechia', q: 'Uničov' } },
    { cs: 'Kyjov', search: { country: 'czechia', q: 'Kyjov' } },
    { cs: 'Domažlice', search: { country: 'czechia', q: 'Domažlice' } },
    { cs: 'Kuřim', search: { country: 'czechia', q: 'Kuřim' } },
    { cs: 'Jeseník', search: { country: 'czechia', q: 'Jeseník' } },
    { cs: 'Humpolec', search: { country: 'czechia', q: 'Humpolec' } },
    { cs: 'Sušice', search: { country: 'czechia', q: 'Sušice' } },
    { cs: 'Rumburk', search: { country: 'czechia', q: 'Rumburk' } },
    { cs: 'Rychnov nad Kněžnou', search: { country: 'czechia', q: 'Rychnov nad Kněžnou' } },
    { cs: 'Veselí nad Moravou', search: { country: 'czechia', q: 'Veselí nad Moravou' } },
    { cs: 'Frenštát pod Radhoštěm', search: { country: 'czechia', q: 'Frenštát pod Radhoštěm' } },
    { cs: 'Prachatice', search: { country: 'czechia', q: 'Prachatice' } },
    { cs: 'Čáslav', search: { country: 'czechia', q: 'Čáslav' } },
    { cs: 'Litomyšl', search: { country: 'czechia', q: 'Litomyšl' } },
    { cs: 'Nové Město na Moravě', search: { country: 'czechia', q: 'Nové Město na Moravě' } },
    { cs: 'Jesenice', search: { country: 'czechia', q: 'Jesenice' } },
    { cs: 'Králův Dvůr', search: { country: 'czechia', q: 'Králův Dvůr' } },
    { cs: 'Frýdlant nad Ostravicí', search: { country: 'czechia', q: 'Frýdlant nad Ostravicí' } },
    { cs: 'Přelouč', search: { country: 'czechia', q: 'Přelouč' } },
    { cs: 'Ivančice', search: { country: 'czechia', q: 'Ivančice' } },
    { cs: 'Lysá nad Labem', search: { country: 'czechia', q: 'Lysá nad Labem' } },
    { cs: 'Lanškroun', search: { country: 'czechia', q: 'Lanškroun' } },
    { cs: 'Moravská Třebová', search: { country: 'czechia', q: 'Moravská Třebová' } },
    { cs: 'Litovel', search: { country: 'czechia', q: 'Litovel' } },
    { cs: 'Hlinsko', search: { country: 'czechia', q: 'Hlinsko' } },
    { cs: 'Studénka', search: { country: 'czechia', q: 'Studénka' } },
    { cs: 'Nové Město nad Metují', search: { country: 'czechia', q: 'Nové Město nad Metují' } },
    { cs: 'Tišnov', search: { country: 'czechia', q: 'Tišnov' } },
    { cs: 'Mohelnice', search: { country: 'czechia', q: 'Mohelnice' } },
    { cs: 'Chotěboř', search: { country: 'czechia', q: 'Chotěboř' } },
    { cs: 'Nová Paka', search: { country: 'czechia', q: 'Nová Paka' } },
    { cs: 'Hostivice', search: { country: 'czechia', q: 'Hostivice' } },
    { cs: 'Mnichovo Hradiště', search: { country: 'czechia', q: 'Mnichovo Hradiště' } },
    { cs: 'Dobříš', search: { country: 'czechia', q: 'Dobříš' } },
    { cs: 'Polička', search: { country: 'czechia', q: 'Polička' } },
    { cs: 'Roztoky', search: { country: 'czechia', q: 'Roztoky' } },
    { cs: 'Lovosice', search: { country: 'czechia', q: 'Lovosice' } },
    { cs: 'Štětí', search: { country: 'czechia', q: 'Štětí' } },
    { cs: 'Choceň', search: { country: 'czechia', q: 'Choceň' } },
    { cs: 'Duchcov', search: { country: 'czechia', q: 'Duchcov' } },
    { cs: 'Hořice', search: { country: 'czechia', q: 'Hořice' } },
    { cs: 'Příbor', search: { country: 'czechia', q: 'Příbor' } },
    { cs: 'Červený Kostelec', search: { country: 'czechia', q: 'Červený Kostelec' } },
    { cs: 'Semily', search: { country: 'czechia', q: 'Semily' } },
    { cs: 'Milevsko', search: { country: 'czechia', q: 'Milevsko' } },
    { cs: 'Třeboň', search: { country: 'czechia', q: 'Třeboň' } },
    { cs: 'Bystřice pod Hostýnem', search: { country: 'czechia', q: 'Bystřice pod Hostýnem' } },
    { cs: 'Rýmařov', search: { country: 'czechia', q: 'Rýmařov' } },
    { cs: 'Bystřice nad Pernštejnem', search: { country: 'czechia', q: 'Bystřice nad Pernštejnem' } },
    { cs: 'Lipník nad Bečvou', search: { country: 'czechia', q: 'Lipník nad Bečvou' } },
    { cs: 'Týn nad Vltavou', search: { country: 'czechia', q: 'Týn nad Vltavou' } },
    { cs: 'Dubí', search: { country: 'czechia', q: 'Dubí' } },
    { cs: 'Nejdek', search: { country: 'czechia', q: 'Nejdek' } },
    { cs: 'Hrádek nad Nisou', search: { country: 'czechia', q: 'Hrádek nad Nisou' } },
    { cs: 'Šlapanice', search: { country: 'czechia', q: 'Šlapanice' } },
    { cs: 'Stříbro', search: { country: 'czechia', q: 'Stříbro' } },
    { cs: 'Benátky nad Jizerou', search: { country: 'czechia', q: 'Benátky nad Jizerou' } },
    { cs: 'Rychvald', search: { country: 'czechia', q: 'Rychvald' } },
    { cs: 'Mikulov', search: { country: 'czechia', q: 'Mikulov' } },
    { cs: 'Frýdlant', search: { country: 'czechia', q: 'Frýdlant' } },
    { cs: 'Vimperk', search: { country: 'czechia', q: 'Vimperk' } },
    { cs: 'Bílovec', search: { country: 'czechia', q: 'Bílovec' } },
    { cs: 'Černošice', search: { country: 'czechia', q: 'Černošice' } },
    { cs: 'Vratimov', search: { country: 'czechia', q: 'Vratimov' } },
    { cs: 'Petřvald', search: { country: 'czechia', q: 'Petřvald' } },
    { cs: 'Odry', search: { country: 'czechia', q: 'Odry' } },
    { cs: 'Broumov', search: { country: 'czechia', q: 'Broumov' } },
    { cs: 'Moravské Budějovice', search: { country: 'czechia', q: 'Moravské Budějovice' } },
    { cs: 'Kaplice', search: { country: 'czechia', q: 'Kaplice' } },
    { cs: 'Dačice', search: { country: 'czechia', q: 'Dačice' } },
    { cs: 'Sezimovo Ústí', search: { country: 'czechia', q: 'Sezimovo Ústí' } },
    { cs: 'Napajedla', search: { country: 'czechia', q: 'Napajedla' } },
    { cs: 'Český Brod', search: { country: 'czechia', q: 'Český Brod' } },
    { cs: 'Přeštice', search: { country: 'czechia', q: 'Přeštice' } },
    { cs: 'Slavkov u Brna', search: { country: 'czechia', q: 'Slavkov u Brna' } },
    { cs: 'Úvaly', search: { country: 'czechia', q: 'Úvaly' } },
    { cs: 'Vodňany', search: { country: 'czechia', q: 'Vodňany' } },
    { cs: 'Nýřany', search: { country: 'czechia', q: 'Nýřany' } },
    { cs: 'Hořovice', search: { country: 'czechia', q: 'Hořovice' } },
    { cs: 'Soběslav', search: { country: 'czechia', q: 'Soběslav' } },
    { cs: 'Nový Bydžov', search: { country: 'czechia', q: 'Nový Bydžov' } },
    { cs: 'Sedlčany', search: { country: 'czechia', q: 'Sedlčany' } },
    { cs: 'Letovice', search: { country: 'czechia', q: 'Letovice' } },
    { cs: 'Kraslice', search: { country: 'czechia', q: 'Kraslice' } },
    { cs: 'Hulín', search: { country: 'czechia', q: 'Hulín' } },
    { cs: 'Kravaře', search: { country: 'czechia', q: 'Kravaře' } },
    { cs: 'Dobruška', search: { country: 'czechia', q: 'Dobruška' } },
    { cs: 'Holice', search: { country: 'czechia', q: 'Holice' } },
    { cs: 'Staré Město', search: { country: 'czechia', q: 'Staré Město' } },
    { cs: 'Blatná', search: { country: 'czechia', q: 'Blatná' } },
    { cs: 'Bučovice', search: { country: 'czechia', q: 'Bučovice' } },
    { cs: 'Letohrad', search: { country: 'czechia', q: 'Letohrad' } },
    { cs: 'Světlá nad Sázavou', search: { country: 'czechia', q: 'Světlá nad Sázavou' } },
    { cs: 'Šenov', search: { country: 'czechia', q: 'Šenov' } },
    { cs: 'Podbořany', search: { country: 'czechia', q: 'Podbořany' } },
    { cs: 'Mimoň', search: { country: 'czechia', q: 'Mimoň' } },
    { cs: 'Rosice', search: { country: 'czechia', q: 'Rosice' } },
    { cs: 'Veselí nad Lužnicí', search: { country: 'czechia', q: 'Veselí nad Lužnicí' } },
    { cs: 'Dubňany', search: { country: 'czechia', q: 'Dubňany' } },
    { cs: 'Slavičín', search: { country: 'czechia', q: 'Slavičín' } },
    { cs: 'Chrastava', search: { country: 'czechia', q: 'Chrastava' } },
    { cs: 'Odolena Voda', search: { country: 'czechia', q: 'Odolena Voda' } },
    { cs: 'Kostelec nad Orlicí', search: { country: 'czechia', q: 'Kostelec nad Orlicí' } },
    { cs: 'Dobřany', search: { country: 'czechia', q: 'Dobřany' } },
    { cs: 'Tanvald', search: { country: 'czechia', q: 'Tanvald' } },
    { cs: 'Mníšek pod Brdy', search: { country: 'czechia', q: 'Mníšek pod Brdy' } },
    { cs: 'Hronov', search: { country: 'czechia', q: 'Hronov' } },
    { cs: 'Týniště nad Orlicí', search: { country: 'czechia', q: 'Týniště nad Orlicí' } },
    { cs: 'Žamberk', search: { country: 'czechia', q: 'Žamberk' } },
    { cs: 'Železný Brod', search: { country: 'czechia', q: 'Železný Brod' } },
    { cs: 'Hustopeče', search: { country: 'czechia', q: 'Hustopeče' } },
    { cs: 'Kojetín', search: { country: 'czechia', q: 'Kojetín' } },
    { cs: 'Rousínov', search: { country: 'czechia', q: 'Rousínov' } },
    { cs: 'Šluknov', search: { country: 'czechia', q: 'Šluknov' } },
    { cs: 'Třebechovice pod Orebem', search: { country: 'czechia', q: 'Třebechovice pod Orebem' } },
    { cs: 'Týnec nad Sázavou', search: { country: 'czechia', q: 'Týnec nad Sázavou' } },
    { cs: 'Moravský Krumlov', search: { country: 'czechia', q: 'Moravský Krumlov' } },
    { cs: 'Třešť', search: { country: 'czechia', q: 'Třešť' } },
    { cs: 'Úpice', search: { country: 'czechia', q: 'Úpice' } },
    { cs: 'Vítkov', search: { country: 'czechia', q: 'Vítkov' } },
    { cs: 'Nové Strašecí', search: { country: 'czechia', q: 'Nové Strašecí' } },
    { cs: 'Chlumec nad Cidlinou', search: { country: 'czechia', q: 'Chlumec nad Cidlinou' } },
    { cs: 'Fulnek', search: { country: 'czechia', q: 'Fulnek' } },
    { cs: 'Brumov-Bylnice', search: { country: 'czechia', q: 'Brumov-Bylnice' } },
    { cs: 'Zubří', search: { country: 'czechia', q: 'Zubří' } },
    { cs: 'Lomnice nad Popelkou', search: { country: 'czechia', q: 'Lomnice nad Popelkou' } },
    { cs: 'Kunovice', search: { country: 'czechia', q: 'Kunovice' } },
    { cs: 'Hradec nad Moravicí', search: { country: 'czechia', q: 'Hradec nad Moravicí' } },
    { cs: 'Strážnice', search: { country: 'czechia', q: 'Strážnice' } },
    { cs: 'Hluboká nad Vltavou', search: { country: 'czechia', q: 'Hluboká nad Vltavou' } },
    { cs: 'Jablunkov', search: { country: 'czechia', q: 'Jablunkov' } },
    { cs: 'Jilemnice', search: { country: 'czechia', q: 'Jilemnice' } },
    { cs: 'Františkovy Lázně', search: { country: 'czechia', q: 'Františkovy Lázně' } },
    { cs: 'Modřice', search: { country: 'czechia', q: 'Modřice' } },
    { cs: 'Stochov', search: { country: 'czechia', q: 'Stochov' } },
    { cs: 'Planá', search: { country: 'czechia', q: 'Planá' } },
    { cs: 'Horní Slavkov', search: { country: 'czechia', q: 'Horní Slavkov' } },
    { cs: 'Trhové Sviny', search: { country: 'czechia', q: 'Trhové Sviny' } },
    { cs: 'Telč', search: { country: 'czechia', q: 'Telč' } },
    { cs: 'Pohořelice', search: { country: 'czechia', q: 'Pohořelice' } },
    { cs: 'Velká Bíteš', search: { country: 'czechia', q: 'Velká Bíteš' } },
    { cs: 'Horažďovice', search: { country: 'czechia', q: 'Horažďovice' } },
    { cs: 'Polná', search: { country: 'czechia', q: 'Polná' } },
    { cs: 'Česká Kamenice', search: { country: 'czechia', q: 'Česká Kamenice' } },
    { cs: 'Doksy', search: { country: 'czechia', q: 'Doksy' } },
    { cs: 'Kosmonosy', search: { country: 'czechia', q: 'Kosmonosy' } },
    { cs: 'Starý Plzenec', search: { country: 'czechia', q: 'Starý Plzenec' } },
    { cs: 'Rudná', search: { country: 'czechia', q: 'Rudná' } },
    { cs: 'Holýšov', search: { country: 'czechia', q: 'Holýšov' } },
    { cs: 'Kdyně', search: { country: 'czechia', q: 'Kdyně' } },
    { cs: 'Bakov nad Jizerou', search: { country: 'czechia', q: 'Bakov nad Jizerou' } },
    { cs: 'Třemošná', search: { country: 'czechia', q: 'Třemošná' } },
    { cs: 'Jílové', search: { country: 'czechia', q: 'Jílové' } },
    { cs: 'Luhačovice', search: { country: 'czechia', q: 'Luhačovice' } },
    { cs: 'Skuteč', search: { country: 'czechia', q: 'Skuteč' } },
    { cs: 'Česká Skalice', search: { country: 'czechia', q: 'Česká Skalice' } },
    { cs: 'Horšovský Týn', search: { country: 'czechia', q: 'Horšovský Týn' } },
    { cs: 'Bechyně', search: { country: 'czechia', q: 'Bechyně' } },
    { cs: 'Ledeč nad Sázavou', search: { country: 'czechia', q: 'Ledeč nad Sázavou' } },
    { cs: 'Vrbno pod Pradědem', search: { country: 'czechia', q: 'Vrbno pod Pradědem' } },
    { cs: 'Nýrsko', search: { country: 'czechia', q: 'Nýrsko' } },
    { cs: 'Valašské Klobouky', search: { country: 'czechia', q: 'Valašské Klobouky' } },
    { cs: 'Jílové u Prahy', search: { country: 'czechia', q: 'Jílové u Prahy' } },
    { cs: 'Meziboří', search: { country: 'czechia', q: 'Meziboří' } },
    { cs: 'Chropyně', search: { country: 'czechia', q: 'Chropyně' } },
    { cs: 'Vizovice', search: { country: 'czechia', q: 'Vizovice' } },
    { cs: 'Habartov', search: { country: 'czechia', q: 'Habartov' } },
    { cs: 'Zruč nad Sázavou', search: { country: 'czechia', q: 'Zruč nad Sázavou' } },
    { cs: 'Náměšť nad Oslavou', search: { country: 'czechia', q: 'Náměšť nad Oslavou' } },
    { cs: 'Unhošť', search: { country: 'czechia', q: 'Unhošť' } },
    { cs: 'Pečky', search: { country: 'czechia', q: 'Pečky' } },
    { cs: 'Heřmanův Městec', search: { country: 'czechia', q: 'Heřmanův Městec' } },
    { cs: 'Protivín', search: { country: 'czechia', q: 'Protivín' } },
    { cs: 'Bělá pod Bezdězem', search: { country: 'czechia', q: 'Bělá pod Bezdězem' } },
    { cs: 'Kynšperk nad Ohří', search: { country: 'czechia', q: 'Kynšperk nad Ohří' } },
    { cs: 'Oslavany', search: { country: 'czechia', q: 'Oslavany' } },
    { cs: 'Postoloprty', search: { country: 'czechia', q: 'Postoloprty' } },
    { cs: 'Osek', search: { country: 'czechia', q: 'Osek' } },
    { cs: 'Pacov', search: { country: 'czechia', q: 'Pacov' } },
    { cs: 'Vamberk', search: { country: 'czechia', q: 'Vamberk' } },
    { cs: 'Vracov', search: { country: 'czechia', q: 'Vracov' } },
    { cs: 'Votice', search: { country: 'czechia', q: 'Votice' } },
    { cs: 'Adamov', search: { country: 'czechia', q: 'Adamov' } },
    { cs: 'Lišov', search: { country: 'czechia', q: 'Lišov' } },
    { cs: 'Cvikov', search: { country: 'czechia', q: 'Cvikov' } },
    { cs: 'Klimkovice', search: { country: 'czechia', q: 'Klimkovice' } },
    { cs: 'Bor', search: { country: 'czechia', q: 'Bor' } },
    { cs: 'Bystřice', search: { country: 'czechia', q: 'Bystřice' } },
    { cs: 'Bzenec', search: { country: 'czechia', q: 'Bzenec' } },
    { cs: 'Bojkovice', search: { country: 'czechia', q: 'Bojkovice' } },
    { cs: 'Hostinné', search: { country: 'czechia', q: 'Hostinné' } },
    { cs: 'Hluk', search: { country: 'czechia', q: 'Hluk' } },
    { cs: 'Chlumec', search: { country: 'czechia', q: 'Chlumec' } },
    { cs: 'Rožmitál pod Třemšínem', search: { country: 'czechia', q: 'Rožmitál pod Třemšínem' } },
    { cs: 'Planá nad Lužnicí', search: { country: 'czechia', q: 'Planá nad Lužnicí' } },
    { cs: 'Kostelec nad Labem', search: { country: 'czechia', q: 'Kostelec nad Labem' } },
    { cs: 'Uherský Ostroh', search: { country: 'czechia', q: 'Uherský Ostroh' } },
    { cs: 'Slatiňany', search: { country: 'czechia', q: 'Slatiňany' } },
    { cs: 'Zdice', search: { country: 'czechia', q: 'Zdice' } },
    { cs: 'Borovany', search: { country: 'czechia', q: 'Borovany' } },
    { cs: 'Králíky', search: { country: 'czechia', q: 'Králíky' } },
    { cs: 'Nová Role', search: { country: 'czechia', q: 'Nová Role' } },
    { cs: 'Jaroměřice nad Rokytnou', search: { country: 'czechia', q: 'Jaroměřice nad Rokytnou' } },
    { cs: 'Horní Bříza', search: { country: 'czechia', q: 'Horní Bříza' } },
    { cs: 'Brušperk', search: { country: 'czechia', q: 'Brušperk' } },
    { cs: 'Blovice', search: { country: 'czechia', q: 'Blovice' } },
    { cs: 'Dolní Benešov', search: { country: 'czechia', q: 'Dolní Benešov' } },
    { cs: 'Sezemice', search: { country: 'czechia', q: 'Sezemice' } },
    { cs: 'Police nad Metují', search: { country: 'czechia', q: 'Police nad Metují' } },
    { cs: 'Jemnice', search: { country: 'czechia', q: 'Jemnice' } },
    { cs: 'Přibyslav', search: { country: 'czechia', q: 'Přibyslav' } },
    { cs: 'Rajhrad', search: { country: 'czechia', q: 'Rajhrad' } },
    { cs: 'Mnichovice', search: { country: 'czechia', q: 'Mnichovice' } },
    { cs: 'Kamenický Šenov', search: { country: 'czechia', q: 'Kamenický Šenov' } },
    { cs: 'Paskov', search: { country: 'czechia', q: 'Paskov' } },
    { cs: 'Velké Bílovice', search: { country: 'czechia', q: 'Velké Bílovice' } },
    { cs: 'Stráž pod Ralskem', search: { country: 'czechia', q: 'Stráž pod Ralskem' } },
    { cs: 'Velešín', search: { country: 'czechia', q: 'Velešín' } },
    { cs: 'Větřní', search: { country: 'czechia', q: 'Větřní' } },
    { cs: 'Židlochovice', search: { country: 'czechia', q: 'Židlochovice' } },
    { cs: 'Kostelec nad Černými lesy', search: { country: 'czechia', q: 'Kostelec nad Černými lesy' } },
    { cs: 'Brtnice', search: { country: 'czechia', q: 'Brtnice' } },
    { cs: 'Smržovka', search: { country: 'czechia', q: 'Smržovka' } },
    { cs: 'Sázava', search: { country: 'czechia', q: 'Sázava' } },
    { cs: 'Rájec-Jestřebí', search: { country: 'czechia', q: 'Rájec-Jestřebí' } },
    { cs: 'Kamenice nad Lipou', search: { country: 'czechia', q: 'Kamenice nad Lipou' } },
    { cs: 'Zbýšov', search: { country: 'czechia', q: 'Zbýšov' } },
    { cs: 'Dobřichovice', search: { country: 'czechia', q: 'Dobřichovice' } },
    { cs: 'Volary', search: { country: 'czechia', q: 'Volary' } },
    { cs: 'Nepomuk', search: { country: 'czechia', q: 'Nepomuk' } },
    { cs: 'Fryšták', search: { country: 'czechia', q: 'Fryšták' } },
    { cs: 'Zlaté Hory', search: { country: 'czechia', q: 'Zlaté Hory' } },
    { cs: 'Lanžhot', search: { country: 'czechia', q: 'Lanžhot' } },
    { cs: 'Nové Město pod Smrkem', search: { country: 'czechia', q: 'Nové Město pod Smrkem' } },
    { cs: 'Lom', search: { country: 'czechia', q: 'Lom' } },
    { cs: 'Lázně Bělohrad', search: { country: 'czechia', q: 'Lázně Bělohrad' } },
    { cs: 'Klecany', search: { country: 'czechia', q: 'Klecany' } },
    { cs: 'Benešov nad Ploučnicí', search: { country: 'czechia', q: 'Benešov nad Ploučnicí' } },
    { cs: 'Jablonné v Podještědí', search: { country: 'czechia', q: 'Jablonné v Podještědí' } },
    { cs: 'Toužim', search: { country: 'czechia', q: 'Toužim' } },
    { cs: 'Buštěhrad', search: { country: 'czechia', q: 'Buštěhrad' } },
    { cs: 'Velké Opatovice', search: { country: 'czechia', q: 'Velké Opatovice' } },
    { cs: 'Řevnice', search: { country: 'czechia', q: 'Řevnice' } },
    { cs: 'Jiříkov', search: { country: 'czechia', q: 'Jiříkov' } },
    { cs: 'Valtice', search: { country: 'czechia', q: 'Valtice' } },
    { cs: 'Stod', search: { country: 'czechia', q: 'Stod' } },
    { cs: 'Suchdol nad Lužnicí', search: { country: 'czechia', q: 'Suchdol nad Lužnicí' } },
    { cs: 'Lázně Bohdaneč', search: { country: 'czechia', q: 'Lázně Bohdaneč' } },
    { cs: 'Zliv', search: { country: 'czechia', q: 'Zliv' } },
    { cs: 'Štěpánov', search: { country: 'czechia', q: 'Štěpánov' } },
    { cs: 'Březnice', search: { country: 'czechia', q: 'Březnice' } },
    { cs: 'České Velenice', search: { country: 'czechia', q: 'České Velenice' } },
    { cs: 'Velká Bystřice', search: { country: 'czechia', q: 'Velká Bystřice' } },
    { cs: 'Libochovice', search: { country: 'czechia', q: 'Libochovice' } },
    { cs: 'Město Albrechtice', search: { country: 'czechia', q: 'Město Albrechtice' } },
    { cs: 'Libčice nad Vltavou', search: { country: 'czechia', q: 'Libčice nad Vltavou' } },
    { cs: 'Štramberk', search: { country: 'czechia', q: 'Štramberk' } },
    { cs: 'Kralovice', search: { country: 'czechia', q: 'Kralovice' } },
    { cs: 'Dobrovice', search: { country: 'czechia', q: 'Dobrovice' } },
    { cs: 'Veverská Bítýška', search: { country: 'czechia', q: 'Veverská Bítýška' } },
    { cs: 'Krásná Lípa', search: { country: 'czechia', q: 'Krásná Lípa' } },
    { cs: 'Újezd u Brna', search: { country: 'czechia', q: 'Újezd u Brna' } },
    { cs: 'Libušín', search: { country: 'czechia', q: 'Libušín' } },
    { cs: 'Trmice', search: { country: 'czechia', q: 'Trmice' } },
    { cs: 'Staňkov', search: { country: 'czechia', q: 'Staňkov' } },
    { cs: 'Hrušovany nad Jevišovkou', search: { country: 'czechia', q: 'Hrušovany nad Jevišovkou' } },
    { cs: 'Nová Bystřice', search: { country: 'czechia', q: 'Nová Bystřice' } },
    { cs: 'Sadská', search: { country: 'czechia', q: 'Sadská' } },
    { cs: 'Košťany', search: { country: 'czechia', q: 'Košťany' } },
    { cs: 'Chrast', search: { country: 'czechia', q: 'Chrast' } },
    { cs: 'Jablonné nad Orlicí', search: { country: 'czechia', q: 'Jablonné nad Orlicí' } },
    { cs: 'Ždírec nad Doubravou', search: { country: 'czechia', q: 'Ždírec nad Doubravou' } },
    { cs: 'Žacléř', search: { country: 'czechia', q: 'Žacléř' } },
    { cs: 'Uhlířské Janovice', search: { country: 'czechia', q: 'Uhlířské Janovice' } },
    { cs: 'Velké Pavlovice', search: { country: 'czechia', q: 'Velké Pavlovice' } },
    { cs: 'Desná', search: { country: 'czechia', q: 'Desná' } },
    { cs: 'Opočno', search: { country: 'czechia', q: 'Opočno' } },
    { cs: 'Loket', search: { country: 'czechia', q: 'Loket' } },
    { cs: 'Velvary', search: { country: 'czechia', q: 'Velvary' } },
    { cs: 'Kaznějov', search: { country: 'czechia', q: 'Kaznějov' } },
    { cs: 'Břidličná', search: { country: 'czechia', q: 'Břidličná' } },
    { cs: 'Třemošnice', search: { country: 'czechia', q: 'Třemošnice' } },
    { cs: 'Hanušovice', search: { country: 'czechia', q: 'Hanušovice' } },
    { cs: 'Podivín', search: { country: 'czechia', q: 'Podivín' } },
    { cs: 'Miroslav', search: { country: 'czechia', q: 'Miroslav' } },
    { cs: 'Volyně', search: { country: 'czechia', q: 'Volyně' } },
    { cs: 'Hodkovice nad Mohelkou', search: { country: 'czechia', q: 'Hodkovice nad Mohelkou' } },
    { cs: 'Rtyně v Podkrkonoší', search: { country: 'czechia', q: 'Rtyně v Podkrkonoší' } },
    { cs: 'Teplá', search: { country: 'czechia', q: 'Teplá' } },
    { cs: 'Morkovice-Slížany', search: { country: 'czechia', q: 'Morkovice-Slížany' } },
    { cs: 'Loštice', search: { country: 'czechia', q: 'Loštice' } },
    { cs: 'Slušovice', search: { country: 'czechia', q: 'Slušovice' } },
    { cs: 'Úštěk', search: { country: 'czechia', q: 'Úštěk' } },
    { cs: 'Chvaletice', search: { country: 'czechia', q: 'Chvaletice' } },
    { cs: 'Ivanovice na Hané', search: { country: 'czechia', q: 'Ivanovice na Hané' } },
    { cs: 'Smiřice', search: { country: 'czechia', q: 'Smiřice' } },
    { cs: 'Žirovnice', search: { country: 'czechia', q: 'Žirovnice' } },
    { cs: 'Moravský Beroun', search: { country: 'czechia', q: 'Moravský Beroun' } },
    { cs: 'Budišov nad Budišovkou', search: { country: 'czechia', q: 'Budišov nad Budišovkou' } },
    { cs: 'Rotava', search: { country: 'czechia', q: 'Rotava' } },
    { cs: 'Kostelec na Hané', search: { country: 'czechia', q: 'Kostelec na Hané' } },
    { cs: 'Spálené Poříčí', search: { country: 'czechia', q: 'Spálené Poříčí' } },
    { cs: 'Vejprty', search: { country: 'czechia', q: 'Vejprty' } },
    { cs: 'Sedlec-Prčice', search: { country: 'czechia', q: 'Sedlec-Prčice' } },
    { cs: 'Terezín', search: { country: 'czechia', q: 'Terezín' } },
    { cs: 'Zákupy', search: { country: 'czechia', q: 'Zákupy' } },
    { cs: 'Raspenava', search: { country: 'czechia', q: 'Raspenava' } },
    { cs: 'Hrádek', search: { country: 'czechia', q: 'Hrádek' } },
    { cs: 'Dolní Bousov', search: { country: 'czechia', q: 'Dolní Bousov' } },
    { cs: 'Český Dub', search: { country: 'czechia', q: 'Český Dub' } },
    { cs: 'Kunštát', search: { country: 'czechia', q: 'Kunštát' } },
    { cs: 'Jevíčko', search: { country: 'czechia', q: 'Jevíčko' } },
    { cs: 'Městec Králové', search: { country: 'czechia', q: 'Městec Králové' } },
    { cs: 'Rychnov u Jablonce nad Nisou', search: { country: 'czechia', q: 'Rychnov u Jablonce nad Nisou' } },
    { cs: 'Plasy', search: { country: 'czechia', q: 'Plasy' } },
    { cs: 'Konice', search: { country: 'czechia', q: 'Konice' } },
    { cs: 'Hejnice', search: { country: 'czechia', q: 'Hejnice' } },
    { cs: 'Javorník', search: { country: 'czechia', q: 'Javorník' } },
    { cs: 'Mladá Vožice', search: { country: 'czechia', q: 'Mladá Vožice' } },
    { cs: 'Koryčany', search: { country: 'czechia', q: 'Koryčany' } },
    { cs: 'Golčův Jeníkov', search: { country: 'czechia', q: 'Golčův Jeníkov' } },
    { cs: 'Kelč', search: { country: 'czechia', q: 'Kelč' } },
    { cs: 'Velké Hamry', search: { country: 'czechia', q: 'Velké Hamry' } },
    { cs: 'Neveklov', search: { country: 'czechia', q: 'Neveklov' } },
    { cs: 'Březová', search: { country: 'czechia', q: 'Březová' } },
    { cs: 'Vyšší Brod', search: { country: 'czechia', q: 'Vyšší Brod' } },
    { cs: 'Luže', search: { country: 'czechia', q: 'Luže' } },
    { cs: 'Nové Sedlo', search: { country: 'czechia', q: 'Nové Sedlo' } },
    { cs: 'Rokytnice nad Jizerou', search: { country: 'czechia', q: 'Rokytnice nad Jizerou' } },
    { cs: 'Rudolfov', search: { country: 'czechia', q: 'Rudolfov' } },
    { cs: 'Netolice', search: { country: 'czechia', q: 'Netolice' } },
    { cs: 'Počátky', search: { country: 'czechia', q: 'Počátky' } },
    { cs: 'Chabařovice', search: { country: 'czechia', q: 'Chabařovice' } },
    { cs: 'Nové Hrady', search: { country: 'czechia', q: 'Nové Hrady' } },
    { cs: 'Zbiroh', search: { country: 'czechia', q: 'Zbiroh' } },
    { cs: 'Ždánice', search: { country: 'czechia', q: 'Ždánice' } },
    { cs: 'Klobouky u Brna', search: { country: 'czechia', q: 'Klobouky u Brna' } },
    { cs: 'Bohušovice nad Ohří', search: { country: 'czechia', q: 'Bohušovice nad Ohří' } },
    { cs: 'Chýnov', search: { country: 'czechia', q: 'Chýnov' } },
    { cs: 'Dolní Kounice', search: { country: 'czechia', q: 'Dolní Kounice' } },
    { cs: 'Tovačov', search: { country: 'czechia', q: 'Tovačov' } },
    { cs: 'Karolinka', search: { country: 'czechia', q: 'Karolinka' } },
    { cs: 'Jáchymov', search: { country: 'czechia', q: 'Jáchymov' } },
    { cs: 'Sobotka', search: { country: 'czechia', q: 'Sobotka' } },
    { cs: 'Dašice', search: { country: 'czechia', q: 'Dašice' } },
    { cs: 'Meziměstí', search: { country: 'czechia', q: 'Meziměstí' } },
    { cs: 'Kryry', search: { country: 'czechia', q: 'Kryry' } },
    { cs: 'Nechanice', search: { country: 'czechia', q: 'Nechanice' } },
    { cs: 'Slavonice', search: { country: 'czechia', q: 'Slavonice' } },
    { cs: 'Janovice nad Úhlavou', search: { country: 'czechia', q: 'Janovice nad Úhlavou' } },
    { cs: 'Plumlov', search: { country: 'czechia', q: 'Plumlov' } },
    { cs: 'Mirošov', search: { country: 'czechia', q: 'Mirošov' } },
    { cs: 'Nová Včelnice', search: { country: 'czechia', q: 'Nová Včelnice' } },
    { cs: 'Veltrusy', search: { country: 'czechia', q: 'Veltrusy' } },
    { cs: 'Žlutice', search: { country: 'czechia', q: 'Žlutice' } },
    { cs: 'Solnice', search: { country: 'czechia', q: 'Solnice' } },
    { cs: 'Horní Jiřetín', search: { country: 'czechia', q: 'Horní Jiřetín' } },
    { cs: 'Horní Benešov', search: { country: 'czechia', q: 'Horní Benešov' } },
    { cs: 'Kardašova Řečice', search: { country: 'czechia', q: 'Kardašova Řečice' } },
    { cs: 'Žebrák', search: { country: 'czechia', q: 'Žebrák' } },
    { cs: 'Město Touškov', search: { country: 'czechia', q: 'Město Touškov' } },
    { cs: 'Hranice', search: { country: 'czechia', q: 'Hranice' } },
    { cs: 'Budyně nad Ohří', search: { country: 'czechia', q: 'Budyně nad Ohří' } },
    { cs: 'Luby', search: { country: 'czechia', q: 'Luby' } },
    { cs: 'Ralsko', search: { country: 'czechia', q: 'Ralsko' } },
    { cs: 'Kopidlno', search: { country: 'czechia', q: 'Kopidlno' } },
    { cs: 'Mikulášovice', search: { country: 'czechia', q: 'Mikulášovice' } },
    { cs: 'Borohrádek', search: { country: 'czechia', q: 'Borohrádek' } },
    { cs: 'Týnec nad Labem', search: { country: 'czechia', q: 'Týnec nad Labem' } },
    { cs: 'Nový Knín', search: { country: 'czechia', q: 'Nový Knín' } },
    { cs: 'Proseč', search: { country: 'czechia', q: 'Proseč' } },
    { cs: 'Pyšely', search: { country: 'czechia', q: 'Pyšely' } },
    { cs: 'Horní Jelení', search: { country: 'czechia', q: 'Horní Jelení' } },
    { cs: 'Hrochův Týnec', search: { country: 'czechia', q: 'Hrochův Týnec' } },
    { cs: 'Horní Planá', search: { country: 'czechia', q: 'Horní Planá' } },
    { cs: 'Hroznětín', search: { country: 'czechia', q: 'Hroznětín' } },
    { cs: 'Svoboda nad Úpou', search: { country: 'czechia', q: 'Svoboda nad Úpou' } },
    { cs: 'Jistebnice', search: { country: 'czechia', q: 'Jistebnice' } },
    { cs: 'Hrob', search: { country: 'czechia', q: 'Hrob' } },
    { cs: 'Zásmuky', search: { country: 'czechia', q: 'Zásmuky' } },
    { cs: 'Skalná', search: { country: 'czechia', q: 'Skalná' } },
    { cs: 'Rokytnice v Orlických horách', search: { country: 'czechia', q: 'Rokytnice v Orlických horách' } },
    { cs: 'Štíty', search: { country: 'czechia', q: 'Štíty' } },
    { cs: 'Velký Šenov', search: { country: 'czechia', q: 'Velký Šenov' } },
    { cs: 'Němčice nad Hanou', search: { country: 'czechia', q: 'Němčice nad Hanou' } },
    { cs: 'Plesná', search: { country: 'czechia', q: 'Plesná' } },
    { cs: 'Třebenice', search: { country: 'czechia', q: 'Třebenice' } },
    { cs: 'Libáň', search: { country: 'czechia', q: 'Libáň' } },
    { cs: 'Smečno', search: { country: 'czechia', q: 'Smečno' } },
    { cs: 'Bochov', search: { country: 'czechia', q: 'Bochov' } },
    { cs: 'Kouřim', search: { country: 'czechia', q: 'Kouřim' } },
    { cs: 'Lučany nad Nisou', search: { country: 'czechia', q: 'Lučany nad Nisou' } },
    { cs: 'Žandov', search: { country: 'czechia', q: 'Žandov' } },
    { cs: 'Horní Cerekev', search: { country: 'czechia', q: 'Horní Cerekev' } },
    { cs: 'Vroutek', search: { country: 'czechia', q: 'Vroutek' } },
    { cs: 'Hostomice', search: { country: 'czechia', q: 'Hostomice' } },
    { cs: 'Radnice', search: { country: 'czechia', q: 'Radnice' } },
    { cs: 'Lomnice nad Lužnicí', search: { country: 'czechia', q: 'Lomnice nad Lužnicí' } },
    { cs: 'Hrotovice', search: { country: 'czechia', q: 'Hrotovice' } },
    { cs: 'Černovice', search: { country: 'czechia', q: 'Černovice' } },
    { cs: 'Bělá nad Radbuzou', search: { country: 'czechia', q: 'Bělá nad Radbuzou' } },
    { cs: 'Seč', search: { country: 'czechia', q: 'Seč' } },
    { cs: 'Hoštka', search: { country: 'czechia', q: 'Hoštka' } },
    { cs: 'Dolní Poustevna', search: { country: 'czechia', q: 'Dolní Poustevna' } },
    { cs: 'Vlachovo Březí', search: { country: 'czechia', q: 'Vlachovo Březí' } },
    { cs: 'Dubá', search: { country: 'czechia', q: 'Dubá' } },
    { cs: 'Ronov nad Doubravou', search: { country: 'czechia', q: 'Ronov nad Doubravou' } },
    { cs: 'Jesenice', search: { country: 'czechia', q: 'Jesenice' } },
    { cs: 'Staré Město', search: { country: 'czechia', q: 'Staré Město' } },
    { cs: 'Nasavrky', search: { country: 'czechia', q: 'Nasavrky' } },
    { cs: 'Olešnice', search: { country: 'czechia', q: 'Olešnice' } },
    { cs: 'Švihov', search: { country: 'czechia', q: 'Švihov' } },
    { cs: 'Plánice', search: { country: 'czechia', q: 'Plánice' } },
    { cs: 'Oloví', search: { country: 'czechia', q: 'Oloví' } },
    { cs: 'Rožďalovice', search: { country: 'czechia', q: 'Rožďalovice' } },
    { cs: 'Bavorov', search: { country: 'czechia', q: 'Bavorov' } },
    { cs: 'Kladruby', search: { country: 'czechia', q: 'Kladruby' } },
    { cs: 'Železná Ruda', search: { country: 'czechia', q: 'Železná Ruda' } },
    { cs: 'Březová nad Svitavou', search: { country: 'czechia', q: 'Březová nad Svitavou' } },
    { cs: 'Všeruby', search: { country: 'czechia', q: 'Všeruby' } },
    { cs: 'Mirovice', search: { country: 'czechia', q: 'Mirovice' } },
    { cs: 'Teplice nad Metují', search: { country: 'czechia', q: 'Teplice nad Metují' } },
    { cs: 'Jablonec nad Jizerou', search: { country: 'czechia', q: 'Jablonec nad Jizerou' } },
    { cs: 'Přimda', search: { country: 'czechia', q: 'Přimda' } },
    { cs: 'Poběžovice', search: { country: 'czechia', q: 'Poběžovice' } },
    { cs: 'Mýto', search: { country: 'czechia', q: 'Mýto' } },
    { cs: 'Bystré', search: { country: 'czechia', q: 'Bystré' } },
    { cs: 'Kožlany', search: { country: 'czechia', q: 'Kožlany' } },
    { cs: 'Strmilov', search: { country: 'czechia', q: 'Strmilov' } },
    { cs: 'Mšeno', search: { country: 'czechia', q: 'Mšeno' } },
    { cs: 'Husinec', search: { country: 'czechia', q: 'Husinec' } },
    { cs: 'Lázně Kynžvart', search: { country: 'czechia', q: 'Lázně Kynžvart' } },
    { cs: 'Strážov', search: { country: 'czechia', q: 'Strážov' } },
    { cs: 'Trhový Štěpánov', search: { country: 'czechia', q: 'Trhový Štěpánov' } },
    { cs: 'Kašperské Hory', search: { country: 'czechia', q: 'Kašperské Hory' } },
    { cs: 'Svratka', search: { country: 'czechia', q: 'Svratka' } },
    { cs: 'Chřibská', search: { country: 'czechia', q: 'Chřibská' } },
    { cs: 'Harrachov', search: { country: 'czechia', q: 'Harrachov' } },
    { cs: 'Habry', search: { country: 'czechia', q: 'Habry' } },
    { cs: 'Železnice', search: { country: 'czechia', q: 'Železnice' } },
    { cs: 'Kasejovice', search: { country: 'czechia', q: 'Kasejovice' } },
    { cs: 'Brandýs nad Orlicí', search: { country: 'czechia', q: 'Brandýs nad Orlicí' } },
    { cs: 'Rovensko pod Troskami', search: { country: 'czechia', q: 'Rovensko pod Troskami' } },
    { cs: 'Vysoké nad Jizerou', search: { country: 'czechia', q: 'Vysoké nad Jizerou' } },
    { cs: 'Vidnava', search: { country: 'czechia', q: 'Vidnava' } },
    { cs: 'Sedlice', search: { country: 'czechia', q: 'Sedlice' } },
    { cs: 'Mirotice', search: { country: 'czechia', q: 'Mirotice' } },
    { cs: 'Pilníkov', search: { country: 'czechia', q: 'Pilníkov' } },
    { cs: 'Hostouň', search: { country: 'czechia', q: 'Hostouň' } },
    { cs: 'Žulová', search: { country: 'czechia', q: 'Žulová' } },
    { cs: 'Černošín', search: { country: 'czechia', q: 'Černošín' } },
    { cs: 'Potštát', search: { country: 'czechia', q: 'Potštát' } },
    { cs: 'Osečná', search: { country: 'czechia', q: 'Osečná' } },
    { cs: 'Verneřice', search: { country: 'czechia', q: 'Verneřice' } },
    { cs: 'Nalžovské Hory', search: { country: 'czechia', q: 'Nalžovské Hory' } },
    { cs: 'Úsov', search: { country: 'czechia', q: 'Úsov' } },
    { cs: 'Jevišovice', search: { country: 'czechia', q: 'Jevišovice' } },
    { cs: 'Manětín', search: { country: 'czechia', q: 'Manětín' } },
    { cs: 'Měčín', search: { country: 'czechia', q: 'Měčín' } },
    { cs: 'Krásná Hora nad Vltavou', search: { country: 'czechia', q: 'Krásná Hora nad Vltavou' } },
    { cs: 'Špindlerův Mlýn', search: { country: 'czechia', q: 'Špindlerův Mlýn' } },
    { cs: 'Liběchov', search: { country: 'czechia', q: 'Liběchov' } },
    { cs: 'Červená Řečice', search: { country: 'czechia', q: 'Červená Řečice' } },
    { cs: 'Blšany', search: { country: 'czechia', q: 'Blšany' } },
    { cs: 'Bělčice', search: { country: 'czechia', q: 'Bělčice' } },
    { cs: 'Bečov nad Teplou', search: { country: 'czechia', q: 'Bečov nad Teplou' } },
    { cs: 'Hartmanice', search: { country: 'czechia', q: 'Hartmanice' } },
    { cs: 'Bezdružice', search: { country: 'czechia', q: 'Bezdružice' } },
    { cs: 'Miletín', search: { country: 'czechia', q: 'Miletín' } },
    { cs: 'Abertamy', search: { country: 'czechia', q: 'Abertamy' } },
    { cs: 'Stráž nad Nežárkou', search: { country: 'czechia', q: 'Stráž nad Nežárkou' } },
    { cs: 'Vysoké Veselí', search: { country: 'czechia', q: 'Vysoké Veselí' } },
    { cs: 'Deštná', search: { country: 'czechia', q: 'Deštná' } },
    { cs: 'Krásno', search: { country: 'czechia', q: 'Krásno' } },
    { cs: 'Janské Lázně', search: { country: 'czechia', q: 'Janské Lázně' } },
    { cs: 'Stárkov', search: { country: 'czechia', q: 'Stárkov' } },
    { cs: 'Lipnice nad Sázavou', search: { country: 'czechia', q: 'Lipnice nad Sázavou' } },
    { cs: 'Pec pod Sněžkou', search: { country: 'czechia', q: 'Pec pod Sněžkou' } },
    { cs: 'Chyše', search: { country: 'czechia', q: 'Chyše' } },
    { cs: 'Mašťov', search: { country: 'czechia', q: 'Mašťov' } },
    { cs: 'Ledvice', search: { country: 'czechia', q: 'Ledvice' } },
    { cs: 'Rabí', search: { country: 'czechia', q: 'Rabí' } },
    { cs: 'Úterý', search: { country: 'czechia', q: 'Úterý' } },
    { cs: 'Hora Svaté Kateřiny', search: { country: 'czechia', q: 'Hora Svaté Kateřiny' } },
    { cs: 'Výsluní', search: { country: 'czechia', q: 'Výsluní' } },
    { cs: 'Horní Blatná', search: { country: 'czechia', q: 'Horní Blatná' } },
    { cs: 'Krásné Údolí', search: { country: 'czechia', q: 'Krásné Údolí' } },
    { cs: 'Rožmberk nad Vltavou', search: { country: 'czechia', q: 'Rožmberk nad Vltavou' } },
    { cs: 'Andělská Hora', search: { country: 'czechia', q: 'Andělská Hora' } },
    { cs: 'Janov', search: { country: 'czechia', q: 'Janov' } },
    { cs: 'Rejštejn', search: { country: 'czechia', q: 'Rejštejn' } },
    { cs: 'Boží Dar', search: { country: 'czechia', q: 'Boží Dar' } },
    { cs: 'Loučná pod Klínovcem', search: { country: 'czechia', q: 'Loučná pod Klínovcem' } },
    { cs: 'Přebuz', search: { country: 'czechia', q: 'Přebuz' } },
    { cs: 'Hlavní město Praha', search: { country: 'czechia', q: 'Hlavní město Praha' } },
    { cs: 'Středočeský kraj', search: { country: 'czechia', q: 'Středočeský kraj' } },
    { cs: 'Jihočeský kraj', search: { country: 'czechia', q: 'Jihočeský kraj' } },
    { cs: 'Plzeňský kraj', search: { country: 'czechia', q: 'Plzeňský kraj' } },
    { cs: 'Karlovarský kraj', search: { country: 'czechia', q: 'Karlovarský kraj' } },
    { cs: 'Ústecký kraj', search: { country: 'czechia', q: 'Ústecký kraj' } },
    { cs: 'Liberecký kraj', search: { country: 'czechia', q: 'Liberecký kraj' } },
    { cs: 'Královéhradecký kraj', search: { country: 'czechia', q: 'Královéhradecký kraj' } },
    { cs: 'Pardubický kraj', search: { country: 'czechia', q: 'Pardubický kraj' } },
    { cs: 'Kraj Vysočina', search: { country: 'czechia', q: 'Kraj Vysočina' } },
    { cs: 'Jihomoravský kraj', search: { country: 'czechia', q: 'Jihomoravský kraj' } },
    { cs: 'Olomoucký kraj', search: { country: 'czechia', q: 'Olomoucký kraj' } },
    { cs: 'Moravskoslezský kraj', search: { country: 'czechia', q: 'Moravskoslezský kraj' } },
    { cs: 'Zlínský kraj', search: { country: 'czechia', q: 'Zlínský kraj' } },
    { cs: '', search: { country: 'czechia', q: '' } },
    { cs: 'Okres Benešov', search: { country: 'czechia', q: 'Okres Benešov' } },
    { cs: 'Okres Beroun', search: { country: 'czechia', q: 'Okres Beroun' } },
    { cs: 'Okres Blansko', search: { country: 'czechia', q: 'Okres Blansko' } },
    { cs: 'Okres Brno-město', search: { country: 'czechia', q: 'Okres Brno-město' } },
    { cs: 'Okres Brno-venkov', search: { country: 'czechia', q: 'Okres Brno-venkov' } },
    { cs: 'Okres Bruntál', search: { country: 'czechia', q: 'Okres Bruntál' } },
    { cs: 'Okres Břeclav', search: { country: 'czechia', q: 'Okres Břeclav' } },
    { cs: 'Okres Česká Lípa', search: { country: 'czechia', q: 'Okres Česká Lípa' } },
    { cs: 'Okres České Budějovice', search: { country: 'czechia', q: 'Okres České Budějovice' } },
    { cs: 'Okres Český Krumlov', search: { country: 'czechia', q: 'Okres Český Krumlov' } },
    { cs: 'Okres Děčín', search: { country: 'czechia', q: 'Okres Děčín' } },
    { cs: 'Okres Domažlice', search: { country: 'czechia', q: 'Okres Domažlice' } },
    { cs: 'Okres Frýdek-Místek', search: { country: 'czechia', q: 'Okres Frýdek-Místek' } },
    { cs: 'Okres Havlíčkův Brod', search: { country: 'czechia', q: 'Okres Havlíčkův Brod' } },
    { cs: 'Okres Hodonín', search: { country: 'czechia', q: 'Okres Hodonín' } },
    { cs: 'Okres Hradec Králové', search: { country: 'czechia', q: 'Okres Hradec Králové' } },
    { cs: 'Okres Cheb', search: { country: 'czechia', q: 'Okres Cheb' } },
    { cs: 'Okres Chomutov', search: { country: 'czechia', q: 'Okres Chomutov' } },
    { cs: 'Okres Chrudim', search: { country: 'czechia', q: 'Okres Chrudim' } },
    { cs: 'Okres Jablonec nad Nisou', search: { country: 'czechia', q: 'Okres Jablonec nad Nisou' } },
    { cs: 'Okres Jeseník', search: { country: 'czechia', q: 'Okres Jeseník' } },
    { cs: 'Okres Jičín', search: { country: 'czechia', q: 'Okres Jičín' } },
    { cs: 'Okres Jihlava', search: { country: 'czechia', q: 'Okres Jihlava' } },
    { cs: 'Okres Jindřichův Hradec', search: { country: 'czechia', q: 'Okres Jindřichův Hradec' } },
    { cs: 'Okres Karlovy Vary', search: { country: 'czechia', q: 'Okres Karlovy Vary' } },
    { cs: 'Okres Karviná', search: { country: 'czechia', q: 'Okres Karviná' } },
    { cs: 'Okres Kladno', search: { country: 'czechia', q: 'Okres Kladno' } },
    { cs: 'Okres Klatovy', search: { country: 'czechia', q: 'Okres Klatovy' } },
    { cs: 'Okres Kolín', search: { country: 'czechia', q: 'Okres Kolín' } },
    { cs: 'Okres Kroměříž', search: { country: 'czechia', q: 'Okres Kroměříž' } },
    { cs: 'Okres Kutná Hora', search: { country: 'czechia', q: 'Okres Kutná Hora' } },
    { cs: 'Okres Liberec', search: { country: 'czechia', q: 'Okres Liberec' } },
    { cs: 'Okres Litoměřice', search: { country: 'czechia', q: 'Okres Litoměřice' } },
    { cs: 'Okres Louny', search: { country: 'czechia', q: 'Okres Louny' } },
    { cs: 'Okres Mělník', search: { country: 'czechia', q: 'Okres Mělník' } },
    { cs: 'Okres Mladá Boleslav', search: { country: 'czechia', q: 'Okres Mladá Boleslav' } },
    { cs: 'Okres Most', search: { country: 'czechia', q: 'Okres Most' } },
    { cs: 'Okres Náchod', search: { country: 'czechia', q: 'Okres Náchod' } },
    { cs: 'Okres Nový Jičín', search: { country: 'czechia', q: 'Okres Nový Jičín' } },
    { cs: 'Okres Nymburk', search: { country: 'czechia', q: 'Okres Nymburk' } },
    { cs: 'Okres Olomouc', search: { country: 'czechia', q: 'Okres Olomouc' } },
    { cs: 'Okres Opava', search: { country: 'czechia', q: 'Okres Opava' } },
    { cs: 'Okres Ostrava-město', search: { country: 'czechia', q: 'Okres Ostrava-město' } },
    { cs: 'Okres Pardubice', search: { country: 'czechia', q: 'Okres Pardubice' } },
    { cs: 'Okres Pelhřimov', search: { country: 'czechia', q: 'Okres Pelhřimov' } },
    { cs: 'Okres Písek', search: { country: 'czechia', q: 'Okres Písek' } },
    { cs: 'Okres Plzeň-jih', search: { country: 'czechia', q: 'Okres Plzeň-jih' } },
    { cs: 'Okres Plzeň-město', search: { country: 'czechia', q: 'Okres Plzeň-město' } },
    { cs: 'Okres Plzeň-sever', search: { country: 'czechia', q: 'Okres Plzeň-sever' } },
    { cs: 'Hlavní město Praha', search: { country: 'czechia', q: 'Hlavní město Praha' } },
    { cs: 'Okres Praha-východ', search: { country: 'czechia', q: 'Okres Praha-východ' } },
    { cs: 'Okres Praha-západ', search: { country: 'czechia', q: 'Okres Praha-západ' } },
    { cs: 'Okres Prachatice', search: { country: 'czechia', q: 'Okres Prachatice' } },
    { cs: 'Okres Prostějov', search: { country: 'czechia', q: 'Okres Prostějov' } },
    { cs: 'Okres Přerov', search: { country: 'czechia', q: 'Okres Přerov' } },
    { cs: 'Okres Příbram', search: { country: 'czechia', q: 'Okres Příbram' } },
    { cs: 'Okres Rakovník', search: { country: 'czechia', q: 'Okres Rakovník' } },
    { cs: 'Okres Rokycany', search: { country: 'czechia', q: 'Okres Rokycany' } },
    { cs: 'Okres Rychnov nad Kněžnou', search: { country: 'czechia', q: 'Okres Rychnov nad Kněžnou' } },
    { cs: 'Okres Semily', search: { country: 'czechia', q: 'Okres Semily' } },
    { cs: 'Okres Sokolov', search: { country: 'czechia', q: 'Okres Sokolov' } },
    { cs: 'Okres Strakonice', search: { country: 'czechia', q: 'Okres Strakonice' } },
    { cs: 'Okres Svitavy', search: { country: 'czechia', q: 'Okres Svitavy' } },
    { cs: 'Okres Šumperk', search: { country: 'czechia', q: 'Okres Šumperk' } },
    { cs: 'Okres Tábor', search: { country: 'czechia', q: 'Okres Tábor' } },
    { cs: 'Okres Tachov', search: { country: 'czechia', q: 'Okres Tachov' } },
    { cs: 'Okres Teplice', search: { country: 'czechia', q: 'Okres Teplice' } },
    { cs: 'Okres Trutnov', search: { country: 'czechia', q: 'Okres Trutnov' } },
    { cs: 'Okres Třebíč', search: { country: 'czechia', q: 'Okres Třebíč' } },
    { cs: 'Okres Uherské Hradiště', search: { country: 'czechia', q: 'Okres Uherské Hradiště' } },
    { cs: 'Okres Ústí nad Labem', search: { country: 'czechia', q: 'Okres Ústí nad Labem' } },
    { cs: 'Okres Ústí nad Orlicí', search: { country: 'czechia', q: 'Okres Ústí nad Orlicí' } },
    { cs: 'Okres Vsetín', search: { country: 'czechia', q: 'Okres Vsetín' } },
    { cs: 'Okres Vyškov', search: { country: 'czechia', q: 'Okres Vyškov' } },
    { cs: 'Okres Zlín', search: { country: 'czechia', q: 'Okres Zlín' } },
    { cs: 'Okres Znojmo', search: { country: 'czechia', q: 'Okres Znojmo' } },
    { cs: 'Okres Žďár nad Sázavou', search: { country: 'czechia', q: 'Okres Žďár nad Sázavou' } },
];
